.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/imu/packages/microstrain/src/3dm_gx5_15_node.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/imu/packages/microstrain/src/3dm_gx5_15_node.cpp \- ROS Node for \fBMicrostrain\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'microstrain\&.h'\fP
.br
\fC#include <ros/ros\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ROS Node for \fBMicrostrain\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Brian S\&. Bingham 
.PP
Yuki Kitsukawa 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP

.PP
Definition in file \fB3dm_gx5_15_node\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 39 of file 3dm_gx5_15_node\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
