.TH "_base_device_info_field" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_base_device_info_field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_base\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBfirmware_version\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBmodel_name\fP [\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"
.br
.ti -1c
.RI "\fBu16\fP \fBmodel_number\fP [\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"
.br
.ti -1c
.RI "\fBu16\fP \fBserial_number\fP [\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"
.br
.ti -1c
.RI "\fBu16\fP \fBlotnumber\fP [\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"
.br
.ti -1c
.RI "\fBu16\fP \fBdevice_options\fP [\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file mip_sdk_base\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu16\fP _base_device_info_field::device_options[\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"

.PP
Definition at line 115 of file mip_sdk_base\&.h\&.
.SS "\fBu16\fP _base_device_info_field::firmware_version"

.PP
Definition at line 110 of file mip_sdk_base\&.h\&.
.SS "\fBu16\fP _base_device_info_field::lotnumber[\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"

.PP
Definition at line 114 of file mip_sdk_base\&.h\&.
.SS "\fBu16\fP _base_device_info_field::model_name[\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"

.PP
Definition at line 111 of file mip_sdk_base\&.h\&.
.SS "\fBu16\fP _base_device_info_field::model_number[\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"

.PP
Definition at line 112 of file mip_sdk_base\&.h\&.
.SS "\fBu16\fP _base_device_info_field::serial_number[\fBBASE_DEVICE_INFO_PARAM_LENGTH\fP]"

.PP
Definition at line 113 of file mip_sdk_base\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
