.TH "_gx3_45_diagnostic_status_field" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_gx3_45_diagnostic_status_field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_gx3_45\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBdevice_model\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBstatus_selector\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBcom_mode\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBcom_device\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBsettings_flags\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBcom1_port_state\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_baudrate\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_read_overruns\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBusb_port_state\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_port_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_port_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_port_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_port_read_overruns\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBgps_driver_state\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBgps_port_state\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBgps_port_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBgps_port_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBgps_port_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBgps_port_read_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBgps_messages_processed\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBgps_messages_delayed\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBimu_driver_state\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBimu_port_state\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_port_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_port_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_port_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_port_read_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_messages_processed\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_messages_delayed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file mip_gx3_45\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::com1_port_baudrate"

.PP
Definition at line 106 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::com1_port_bytes_read"

.PP
Definition at line 107 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::com1_port_bytes_written"

.PP
Definition at line 107 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::com1_port_read_overruns"

.PP
Definition at line 108 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::com1_port_state"

.PP
Definition at line 105 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::com1_port_write_overruns"

.PP
Definition at line 108 of file mip_gx3_45\&.h\&.
.SS "\fBu8\fP _gx3_45_diagnostic_status_field::com_device"

.PP
Definition at line 102 of file mip_gx3_45\&.h\&.
.SS "\fBu8\fP _gx3_45_diagnostic_status_field::com_mode"

.PP
Definition at line 101 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::device_model"

.PP
Definition at line 99 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::gps_driver_state"

.PP
Definition at line 114 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::gps_messages_delayed"

.PP
Definition at line 119 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::gps_messages_processed"

.PP
Definition at line 118 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::gps_port_bytes_read"

.PP
Definition at line 116 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::gps_port_bytes_written"

.PP
Definition at line 116 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::gps_port_read_overruns"

.PP
Definition at line 117 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::gps_port_state"

.PP
Definition at line 115 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::gps_port_write_overruns"

.PP
Definition at line 117 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::imu_driver_state"

.PP
Definition at line 121 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::imu_messages_delayed"

.PP
Definition at line 126 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::imu_messages_processed"

.PP
Definition at line 125 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::imu_port_bytes_read"

.PP
Definition at line 123 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::imu_port_bytes_written"

.PP
Definition at line 123 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::imu_port_read_overruns"

.PP
Definition at line 124 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::imu_port_state"

.PP
Definition at line 122 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::imu_port_write_overruns"

.PP
Definition at line 124 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::settings_flags"

.PP
Definition at line 103 of file mip_gx3_45\&.h\&.
.SS "\fBu8\fP _gx3_45_diagnostic_status_field::status_selector"

.PP
Definition at line 100 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::usb_port_bytes_read"

.PP
Definition at line 111 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::usb_port_bytes_written"

.PP
Definition at line 111 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::usb_port_read_overruns"

.PP
Definition at line 112 of file mip_gx3_45\&.h\&.
.SS "\fBu16\fP _gx3_45_diagnostic_status_field::usb_port_state"

.PP
Definition at line 110 of file mip_gx3_45\&.h\&.
.SS "\fBu32\fP _gx3_45_diagnostic_status_field::usb_port_write_overruns"

.PP
Definition at line 112 of file mip_gx3_45\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
