.TH "_gx4_15_diagnostic_status_field" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_gx4_15_diagnostic_status_field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_gx4_15\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBdevice_model\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBstatus_selector\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBstatus_flags\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBsystem_timer_ms\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBnum_pps_triggers\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBlast_pps_trigger_ms\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBimu_stream_enabled\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBfilter_stream_enabled\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_dropped_packets\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBfilter_dropped_packets\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom1_port_read_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBusb_read_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_parser_errors\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_message_count\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBimu_last_message_ms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file mip_gx4_15\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::com1_port_bytes_read"

.PP
Definition at line 116 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::com1_port_bytes_written"

.PP
Definition at line 116 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::com1_port_read_overruns"

.PP
Definition at line 117 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::com1_port_write_overruns"

.PP
Definition at line 117 of file mip_gx4_15\&.h\&.
.SS "\fBu16\fP _gx4_15_diagnostic_status_field::device_model"

.PP
Definition at line 95 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::filter_dropped_packets"

.PP
Definition at line 113 of file mip_gx4_15\&.h\&.
.SS "\fBu8\fP _gx4_15_diagnostic_status_field::filter_stream_enabled"

.PP
Definition at line 109 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::imu_dropped_packets"

.PP
Definition at line 112 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::imu_last_message_ms"

.PP
Definition at line 126 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::imu_message_count"

.PP
Definition at line 125 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::imu_parser_errors"

.PP
Definition at line 124 of file mip_gx4_15\&.h\&.
.SS "\fBu8\fP _gx4_15_diagnostic_status_field::imu_stream_enabled"

.PP
Definition at line 108 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::last_pps_trigger_ms"

.PP
Definition at line 105 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::num_pps_triggers"

.PP
Definition at line 104 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::status_flags"

.PP
Definition at line 98 of file mip_gx4_15\&.h\&.
.SS "\fBu8\fP _gx4_15_diagnostic_status_field::status_selector"

.PP
Definition at line 96 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::system_timer_ms"

.PP
Definition at line 101 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::usb_bytes_read"

.PP
Definition at line 120 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::usb_bytes_written"

.PP
Definition at line 120 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::usb_read_overruns"

.PP
Definition at line 121 of file mip_gx4_15\&.h\&.
.SS "\fBu32\fP _gx4_15_diagnostic_status_field::usb_write_overruns"

.PP
Definition at line 121 of file mip_gx4_15\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
