.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_utility/include/op_utility Directory Reference" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_utility/include/op_utility Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDataRW\&.h\fP"
.br
.RI "\fI\fBFile\fP operations for loading vector map files, loading kml map files and writing log \&.csv files\&. \fP"
.ti -1c
.RI "file \fBUtilityH\&.h\fP"
.br
.RI "\fIGeneral Math and Control utility functions\&. \fP"
.in -1c
