.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner Directory Reference" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBehaviorPrediction\&.h\fP"
.br
.RI "\fIPredict detected vehicles's possible trajectories, these trajectories extracted from the vector map\&. \fP"
.ti -1c
.RI "file \fBBehaviorStateMachine\&.h\fP"
.br
.RI "\fIOpenPlanner's state machine implementation for different driving behaviors\&. \fP"
.ti -1c
.RI "file \fBDecisionMaker\&.h\fP"
.br
.RI "\fIInitialize behaviors state machine, and calculate required parameters for the state machine transition conditions\&. \fP"
.ti -1c
.RI "file \fBLocalPlannerH\&.h\fP"
.br
.RI "\fIOpenPlanner's local planing functions combines in one process, used in simulation vehicle and OpenPlanner old implementation like dp_planner node\&. \fP"
.ti -1c
.RI "file \fBMappingHelpers\&.h\fP"
.br
.RI "\fIHelper functions for mapping operation such as (load and initialize vector maps , convert map from one format to another, \&.\&. ) \fP"
.ti -1c
.RI "file \fBMatrixOperations\&.h\fP"
.br
.RI "\fISimple matrix operations\&. \fP"
.ti -1c
.RI "file \fBPassiveDecisionMaker\&.h\fP"
.br
.ti -1c
.RI "file \fBPlannerCommonDef\&.h\fP"
.br
.RI "\fIDefinition file for control related data types\&. \fP"
.ti -1c
.RI "file \fBPlannerH\&.h\fP"
.br
.RI "\fIMain functions for path generation (global and local) \fP"
.ti -1c
.RI "file \fBPlanningHelpers\&.h\fP"
.br
.RI "\fIHelper functions for planning algorithms\&. \fP"
.ti -1c
.RI "file \fBRoadNetwork\&.h\fP"
.br
.RI "\fIDefinition of OpenPlanner's data types\&. \fP"
.ti -1c
.RI "file \fBSimuDecisionMaker\&.h\fP"
.br
.RI "\fIDecision Maker for Simulated Vehicles\&. \fP"
.ti -1c
.RI "file \fBTrajectoryCosts\&.h\fP"
.br
.RI "\fICalculate collision costs for roll out trajectory for free trajectory evaluation for dp_planner\&. \fP"
.ti -1c
.RI "file \fBTrajectoryDynamicCosts\&.h\fP"
.br
.RI "\fICalculate collision costs for roll out trajectory for free trajectory evaluation for OpenPlanner local planner version 1\&.5+\&. \fP"
.in -1c
