.TH "_mip_filter_accel_magnitude_error_adaptive_measurement_command" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_filter_accel_magnitude_error_adaptive_measurement_command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_filter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBenable\fP"
.br
.ti -1c
.RI "float \fBlow_pass_cutoff\fP"
.br
.ti -1c
.RI "float \fBlow_limit\fP"
.br
.ti -1c
.RI "float \fBhigh_limit\fP"
.br
.ti -1c
.RI "float \fBlow_limit_1sigma\fP"
.br
.ti -1c
.RI "float \fBhigh_limit_1sigma\fP"
.br
.ti -1c
.RI "float \fBmin_1sigma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 382 of file mip_sdk_filter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP _mip_filter_accel_magnitude_error_adaptive_measurement_command::enable"

.PP
Definition at line 384 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_accel_magnitude_error_adaptive_measurement_command::high_limit"

.PP
Definition at line 386 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_accel_magnitude_error_adaptive_measurement_command::high_limit_1sigma"

.PP
Definition at line 387 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_accel_magnitude_error_adaptive_measurement_command::low_limit"

.PP
Definition at line 386 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_accel_magnitude_error_adaptive_measurement_command::low_limit_1sigma"

.PP
Definition at line 387 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_accel_magnitude_error_adaptive_measurement_command::low_pass_cutoff"

.PP
Definition at line 385 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_accel_magnitude_error_adaptive_measurement_command::min_1sigma"

.PP
Definition at line 388 of file mip_sdk_filter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
