.TH "_mip_ahrs_raw_mag" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_ahrs_raw_mag \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_ahrs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBraw_mag\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file mip_sdk_ahrs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float _mip_ahrs_raw_mag::raw_mag[3]"

.PP
Definition at line 116 of file mip_sdk_ahrs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
