.TH "_mip_filter_ned_velocity" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_filter_ned_velocity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_filter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBnorth\fP"
.br
.ti -1c
.RI "float \fBeast\fP"
.br
.ti -1c
.RI "float \fBdown\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 440 of file mip_sdk_filter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float _mip_filter_ned_velocity::down"

.PP
Definition at line 442 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_ned_velocity::east"

.PP
Definition at line 442 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_ned_velocity::north"

.PP
Definition at line 442 of file mip_sdk_filter\&.h\&.
.SS "\fBu16\fP _mip_filter_ned_velocity::valid_flags"

.PP
Definition at line 443 of file mip_sdk_filter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
