.TH "_mip_gps_ned_vel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_gps_ned_vel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBv\fP [3]"
.br
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "float \fBground_speed\fP"
.br
.ti -1c
.RI "float \fBheading\fP"
.br
.ti -1c
.RI "float \fBspeed_accuracy\fP"
.br
.ti -1c
.RI "float \fBheading_accuracy\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 302 of file mip_sdk_gps\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float _mip_gps_ned_vel::ground_speed"

.PP
Definition at line 306 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_ned_vel::heading"

.PP
Definition at line 307 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_ned_vel::heading_accuracy"

.PP
Definition at line 309 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_ned_vel::speed"

.PP
Definition at line 305 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_ned_vel::speed_accuracy"

.PP
Definition at line 308 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_ned_vel::v[3]"

.PP
Definition at line 304 of file mip_sdk_gps\&.h\&.
.SS "\fBu16\fP _mip_gps_ned_vel::valid_flags"

.PP
Definition at line 310 of file mip_sdk_gps\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
