.TH "_mip_filter_attitude_euler_angles" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_filter_attitude_euler_angles \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_filter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBroll\fP"
.br
.ti -1c
.RI "float \fBpitch\fP"
.br
.ti -1c
.RI "float \fByaw\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 464 of file mip_sdk_filter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float _mip_filter_attitude_euler_angles::pitch"

.PP
Definition at line 466 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_attitude_euler_angles::roll"

.PP
Definition at line 466 of file mip_sdk_filter\&.h\&.
.SS "\fBu16\fP _mip_filter_attitude_euler_angles::valid_flags"

.PP
Definition at line 467 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_attitude_euler_angles::yaw"

.PP
Definition at line 466 of file mip_sdk_filter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
