.TH "_mip_gps_dgps_channel_status" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_gps_dgps_channel_status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBsv_id\fP"
.br
.ti -1c
.RI "float \fBage\fP"
.br
.ti -1c
.RI "float \fBpseudorange_correction\fP"
.br
.ti -1c
.RI "float \fBpseudorange_rate_correction\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 440 of file mip_sdk_gps\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float _mip_gps_dgps_channel_status::age"

.PP
Definition at line 443 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_dgps_channel_status::pseudorange_correction"

.PP
Definition at line 444 of file mip_sdk_gps\&.h\&.
.SS "float _mip_gps_dgps_channel_status::pseudorange_rate_correction"

.PP
Definition at line 445 of file mip_sdk_gps\&.h\&.
.SS "\fBu8\fP _mip_gps_dgps_channel_status::sv_id"

.PP
Definition at line 442 of file mip_sdk_gps\&.h\&.
.SS "\fBu16\fP _mip_gps_dgps_channel_status::valid_flags"

.PP
Definition at line 446 of file mip_sdk_gps\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
