.TH "_mip_filter_gyro_bias" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_filter_gyro_bias \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_filter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 472 of file mip_sdk_filter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu16\fP _mip_filter_gyro_bias::valid_flags"

.PP
Definition at line 475 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_gyro_bias::x"

.PP
Definition at line 474 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_gyro_bias::y"

.PP
Definition at line 474 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_gyro_bias::z"

.PP
Definition at line 474 of file mip_sdk_filter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
