.TH "_mip_gps_hw_status" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_gps_hw_status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBsensor_state\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBantenna_state\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBantenna_power\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 413 of file mip_sdk_gps\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP _mip_gps_hw_status::antenna_power"

.PP
Definition at line 417 of file mip_sdk_gps\&.h\&.
.SS "\fBu8\fP _mip_gps_hw_status::antenna_state"

.PP
Definition at line 416 of file mip_sdk_gps\&.h\&.
.SS "\fBu8\fP _mip_gps_hw_status::sensor_state"

.PP
Definition at line 415 of file mip_sdk_gps\&.h\&.
.SS "\fBu16\fP _mip_gps_hw_status::valid_flags"

.PP
Definition at line 418 of file mip_sdk_gps\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
