.TH "_mip_filter_zero_update_command" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_filter_zero_update_command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_filter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBenable\fP"
.br
.ti -1c
.RI "float \fBthreshold\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 357 of file mip_sdk_filter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP _mip_filter_zero_update_command::enable"

.PP
Definition at line 359 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_zero_update_command::threshold"

.PP
Definition at line 360 of file mip_sdk_filter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
