.TH "_mip_header" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBsync1\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBsync2\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBdescriptor_set\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBpayload_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 137 of file mip\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP _mip_header::descriptor_set"

.PP
Definition at line 140 of file mip\&.h\&.
.SS "\fBu8\fP _mip_header::payload_size"

.PP
Definition at line 140 of file mip\&.h\&.
.SS "\fBu8\fP _mip_header::sync1"

.PP
Definition at line 139 of file mip\&.h\&.
.SS "\fBu8\fP _mip_header::sync2"

.PP
Definition at line 139 of file mip\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
