.TH "_mip_ahrs_1pps_timestamp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_ahrs_1pps_timestamp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_ahrs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBseconds\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBnanoseconds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file mip_sdk_ahrs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP _mip_ahrs_1pps_timestamp::flags"

.PP
Definition at line 210 of file mip_sdk_ahrs\&.h\&.
.SS "\fBu32\fP _mip_ahrs_1pps_timestamp::nanoseconds"

.PP
Definition at line 211 of file mip_sdk_ahrs\&.h\&.
.SS "\fBu32\fP _mip_ahrs_1pps_timestamp::seconds"

.PP
Definition at line 211 of file mip_sdk_ahrs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
