.TH "_mip_gps_dgps_info" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_gps_dgps_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_gps\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBage\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBbase_station_id\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBbase_station_status\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBnum_dgps_channels\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 426 of file mip_sdk_gps\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float _mip_gps_dgps_info::age"

.PP
Definition at line 428 of file mip_sdk_gps\&.h\&.
.SS "\fBs16\fP _mip_gps_dgps_info::base_station_id"

.PP
Definition at line 429 of file mip_sdk_gps\&.h\&.
.SS "\fBs16\fP _mip_gps_dgps_info::base_station_status"

.PP
Definition at line 430 of file mip_sdk_gps\&.h\&.
.SS "\fBu16\fP _mip_gps_dgps_info::num_dgps_channels"

.PP
Definition at line 431 of file mip_sdk_gps\&.h\&.
.SS "\fBu16\fP _mip_gps_dgps_info::valid_flags"

.PP
Definition at line 432 of file mip_sdk_gps\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
