.TH "_mip_filter_external_heading_with_time_command" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mip_filter_external_heading_with_time_command \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_sdk_filter\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBgps_tow\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBgps_week_number\fP"
.br
.ti -1c
.RI "float \fBheading_angle_rads\fP"
.br
.ti -1c
.RI "float \fBheading_angle_sigma_rads\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBheading_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 368 of file mip_sdk_filter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double _mip_filter_external_heading_with_time_command::gps_tow"

.PP
Definition at line 370 of file mip_sdk_filter\&.h\&.
.SS "\fBu16\fP _mip_filter_external_heading_with_time_command::gps_week_number"

.PP
Definition at line 371 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_external_heading_with_time_command::heading_angle_rads"

.PP
Definition at line 372 of file mip_sdk_filter\&.h\&.
.SS "float _mip_filter_external_heading_with_time_command::heading_angle_sigma_rads"

.PP
Definition at line 373 of file mip_sdk_filter\&.h\&.
.SS "\fBu8\fP _mip_filter_external_heading_with_time_command::heading_type"

.PP
Definition at line 374 of file mip_sdk_filter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
