.TH "_rq1_imu_diagnostic_status_field" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_rq1_imu_diagnostic_status_field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mip_rq1_imu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBdevice_model\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBstatus_selector\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBstatus_flags\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBsystem_timer_us\fP"
.br
.ti -1c
.RI "float \fBtemp_degc\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBlast_temp_read_ms\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBbad_temp_sensor_detected\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBcold_temp_detected\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBbad_voltage_detected\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBnum_gps_pps_triggers\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBlast_gps_pps_trigger_ms\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBstream_enabled\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBdropped_packets\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBcom_port_state\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom_port_baudrate\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom_port_bytes_written\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom_port_bytes_read\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom_port_write_overruns\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBcom_port_read_overruns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file mip_rq1_imu\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP _rq1_imu_diagnostic_status_field::bad_temp_sensor_detected"

.PP
Definition at line 103 of file mip_rq1_imu\&.h\&.
.SS "\fBu8\fP _rq1_imu_diagnostic_status_field::bad_voltage_detected"

.PP
Definition at line 107 of file mip_rq1_imu\&.h\&.
.SS "\fBu8\fP _rq1_imu_diagnostic_status_field::cold_temp_detected"

.PP
Definition at line 104 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::com_port_baudrate"

.PP
Definition at line 121 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::com_port_bytes_read"

.PP
Definition at line 122 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::com_port_bytes_written"

.PP
Definition at line 122 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::com_port_read_overruns"

.PP
Definition at line 123 of file mip_rq1_imu\&.h\&.
.SS "\fBu16\fP _rq1_imu_diagnostic_status_field::com_port_state"

.PP
Definition at line 120 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::com_port_write_overruns"

.PP
Definition at line 123 of file mip_rq1_imu\&.h\&.
.SS "\fBu16\fP _rq1_imu_diagnostic_status_field::device_model"

.PP
Definition at line 92 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::dropped_packets"

.PP
Definition at line 117 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::last_gps_pps_trigger_ms"

.PP
Definition at line 111 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::last_temp_read_ms"

.PP
Definition at line 102 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::num_gps_pps_triggers"

.PP
Definition at line 110 of file mip_rq1_imu\&.h\&.
.SS "\fBu32\fP _rq1_imu_diagnostic_status_field::status_flags"

.PP
Definition at line 95 of file mip_rq1_imu\&.h\&.
.SS "\fBu8\fP _rq1_imu_diagnostic_status_field::status_selector"

.PP
Definition at line 93 of file mip_rq1_imu\&.h\&.
.SS "\fBu8\fP _rq1_imu_diagnostic_status_field::stream_enabled"

.PP
Definition at line 114 of file mip_rq1_imu\&.h\&.
.SS "\fBu64\fP _rq1_imu_diagnostic_status_field::system_timer_us"

.PP
Definition at line 98 of file mip_rq1_imu\&.h\&.
.SS "float _rq1_imu_diagnostic_status_field::temp_degc"

.PP
Definition at line 101 of file mip_rq1_imu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
