.TH "/home/deng/Project/autobot-feature-decision/ros/src/common/libs/amathutils_lib/src/Amathutils.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/common/libs/amathutils_lib/src/Amathutils.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <amathutils_lib/amathutils\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBamathutils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgeometry_msgs::Point\fP \fBamathutils::getNearPtOnLine\fP (const \fBgeometry_msgs::Point\fP &_p, const \fBgeometry_msgs::Point\fP &_a, const \fBgeometry_msgs::Point\fP &_b)"
.br
.ti -1c
.RI "double \fBamathutils::find_distance\fP (const \fBgeometry_msgs::Point\fP &_from, const \fBgeometry_msgs::Point\fP &_to)"
.br
.ti -1c
.RI "double \fBamathutils::find_distance\fP (const geometry_msgs::Pose &_from, const geometry_msgs::Pose &_to)"
.br
.ti -1c
.RI "double \fBamathutils::find_angle\fP (const \fBgeometry_msgs::Point\fP &_from, const \fBgeometry_msgs::Point\fP &_to)"
.br
.ti -1c
.RI "bool \fBamathutils::isIntersectLine\fP (const \fBgeometry_msgs::Point\fP &_l1_p1, const \fBgeometry_msgs::Point\fP &_l1_p2, const \fBgeometry_msgs::Point\fP &_l2_p1, const \fBgeometry_msgs::Point\fP &_l2_p2)"
.br
.ti -1c
.RI "int \fBamathutils::isPointLeftFromLine\fP (const \fBgeometry_msgs::Point\fP &_target, const \fBgeometry_msgs::Point\fP &_line_p1, const \fBgeometry_msgs::Point\fP &_line_p2)"
.br
.ti -1c
.RI "double \fBamathutils::getPoseYawAngle\fP (const geometry_msgs::Pose &_pose)"
.br
.ti -1c
.RI "double \fBamathutils::calcPosesAngleDiffRaw\fP (const geometry_msgs::Pose &p_from, const geometry_msgs::Pose &_p_to)"
.br
.ti -1c
.RI "double \fBamathutils::radianNormalize\fP (double _angle)"
.br
.ti -1c
.RI "double \fBamathutils::calcPosesAngleDiffDeg\fP (const geometry_msgs::Pose &_p_from, const geometry_msgs::Pose &_p_to)"
.br
.ti -1c
.RI "double \fBamathutils::calcPosesAngleDiffRad\fP (const geometry_msgs::Pose &_p_from, const geometry_msgs::Pose &_p_to)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
