.TH "apollo::PointD" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::PointD \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pcl_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "uint8_t \fBintensity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file pcl_types\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t apollo::PointD::intensity"

.PP
Definition at line 83 of file pcl_types\&.h\&.
.SS "double apollo::PointD::x"

.PP
Definition at line 80 of file pcl_types\&.h\&.
.SS "double apollo::PointD::y"

.PP
Definition at line 81 of file pcl_types\&.h\&.
.SS "double apollo::PointD::z"

.PP
Definition at line 82 of file pcl_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
