.TH "app" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMarkerDownSampler\fP"
.br
.ti -1c
.RI "class \fBPC2DownSampler\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBpp\fP = pprint\&.PrettyPrinter(indent=2)\&.pprint"
.br
.ti -1c
.RI "\fBanonymous\fP"
.br
.ti -1c
.RI "\fBframe_id\fP"
.br
.ti -1c
.RI "\fBleaf_size\fP"
.br
.ti -1c
.RI "\fBlatch\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "app\&.anonymous"

.PP
Definition at line 38 of file app\&.py\&.
.SS "app\&.frame_id"

.PP
Definition at line 58 of file app\&.py\&.
.SS "app\&.latch"

.PP
Definition at line 58 of file app\&.py\&.
.SS "app\&.leaf_size"

.PP
Definition at line 58 of file app\&.py\&.
.SS "app\&.pp = pprint\&.PrettyPrinter(indent=2)\&.pprint"

.PP
Definition at line 14 of file app\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
