.TH "application::ntp_time_t" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
application::ntp_time_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LdmrsNtpTimeApp\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsecond\fP"
.br
.ti -1c
.RI "uint32_t \fBfraction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file LdmrsNtpTimeApp\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t application::ntp_time_t::fraction"

.PP
Definition at line 19 of file LdmrsNtpTimeApp\&.hpp\&.
.SS "uint32_t application::ntp_time_t::second"

.PP
Definition at line 18 of file LdmrsNtpTimeApp\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
