.TH "AstarAvoid" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AstarAvoid \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <astar_avoid\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSTATE\fP { \fBINITIALIZING\fP = -1, \fBRELAYING\fP = 0, \fBSTOPPING\fP = 1, \fBPLANNING\fP = 2, \fBAVOIDING\fP = 3 }"
.br
.ti -1c
.RI "typedef enum \fBAstarAvoid::STATE\fP \fBState\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAstarAvoid\fP ()"
.br
.ti -1c
.RI "\fB~AstarAvoid\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file astar_avoid\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef enum \fBAstarAvoid::STATE\fP  \fBAstarAvoid::State\fP"

.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAstarAvoid::STATE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINITIALIZING \fP\fP
.TP
\fB\fIRELAYING \fP\fP
.TP
\fB\fISTOPPING \fP\fP
.TP
\fB\fIPLANNING \fP\fP
.TP
\fB\fIAVOIDING \fP\fP
.PP
Definition at line 39 of file astar_avoid\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AstarAvoid::AstarAvoid ()"

.PP
Definition at line 19 of file astar_avoid\&.cpp\&.
.SS "AstarAvoid::~AstarAvoid ()"

.PP
Definition at line 52 of file astar_avoid\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AstarAvoid::run (void)"

.PP
Definition at line 105 of file astar_avoid\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
