.TH "augment_args" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
augment_args \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <darknet\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "float \fBrad\fP"
.br
.ti -1c
.RI "float \fBdx\fP"
.br
.ti -1c
.RI "float \fBdy\fP"
.br
.ti -1c
.RI "float \fBaspect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 497 of file darknet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float augment_args::aspect"

.PP
Definition at line 504 of file darknet\&.h\&.
.SS "float augment_args::dx"

.PP
Definition at line 502 of file darknet\&.h\&.
.SS "float augment_args::dy"

.PP
Definition at line 503 of file darknet\&.h\&.
.SS "int augment_args::h"

.PP
Definition at line 499 of file darknet\&.h\&.
.SS "float augment_args::rad"

.PP
Definition at line 501 of file darknet\&.h\&.
.SS "float augment_args::scale"

.PP
Definition at line 500 of file darknet\&.h\&.
.SS "int augment_args::w"

.PP
Definition at line 498 of file darknet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
