.TH "autoware_launcher.gui.quickstart.AwQuickStartPanel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.quickstart.AwQuickStartPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBguimgr\fP)"
.br
.ti -1c
.RI "def \fBprofile_ui_cleared\fP (self)"
.br
.ti -1c
.RI "def \fBnode_ui_created\fP (self, lnode)"
.br
.ti -1c
.RI "def \fBnode_ui_updated\fP (self, lnode)"
.br
.ti -1c
.RI "def \fBstatus_ui_updated\fP (self, lpath, state)"
.br
.ti -1c
.RI "def \fBsetup_widget\fP (self, \fBnode\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBguimgr\fP"
.br
.ti -1c
.RI "\fBframes\fP"
.br
.ti -1c
.RI "\fBawlogo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file quickstart\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.__init__ ( self,  guimgr)"

.PP
Definition at line 12 of file quickstart\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.node_ui_created ( self,  lnode)"

.PP
Definition at line 26 of file quickstart\&.py\&.
.SS "def autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.node_ui_updated ( self,  lnode)"

.PP
Definition at line 29 of file quickstart\&.py\&.
.SS "def autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.profile_ui_cleared ( self)"

.PP
Definition at line 23 of file quickstart\&.py\&.
.SS "def autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.setup_widget ( self,  node)"

.PP
Definition at line 39 of file quickstart\&.py\&.
.SS "def autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.status_ui_updated ( self,  lpath,  state)"

.PP
Definition at line 32 of file quickstart\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.awlogo"

.PP
Definition at line 16 of file quickstart\&.py\&.
.SS "autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.frames"

.PP
Definition at line 15 of file quickstart\&.py\&.
.SS "autoware_launcher\&.gui\&.quickstart\&.AwQuickStartPanel\&.guimgr"

.PP
Definition at line 14 of file quickstart\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
