.TH "autoware_launcher.gui.window.AwMainWindow" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.window.AwMainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBautoware_launcher\&.gui\&.window\&.AwAbstructWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBclient\fP)"
.br
.ti -1c
.RI "def \fBcloseEvent\fP (self, event)"
.br
.ti -1c
.RI "def \fBaddViewMenu\fP (self, text, func)"
.br
.ti -1c
.RI "def \fBload_profile\fP (self)"
.br
.ti -1c
.RI "def \fBsave_profile\fP (self)"
.br
.ti -1c
.RI "def \fBsave_profile_as\fP (self)"
.br
.ti -1c
.RI "def \fBexport_profile\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclient\fP"
.br
.ti -1c
.RI "\fBfilemenu\fP"
.br
.ti -1c
.RI "\fBviewmenu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file window\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.__init__ ( self,  client)"

.PP
Definition at line 26 of file window\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.addViewMenu ( self,  text,  func)"

.PP
Definition at line 67 of file window\&.py\&.
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.closeEvent ( self,  event)"

.PP
Definition at line 36 of file window\&.py\&.
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.export_profile ( self)"

.PP
Definition at line 92 of file window\&.py\&.
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.load_profile ( self)"

.PP
Definition at line 73 of file window\&.py\&.
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.save_profile ( self)"

.PP
Definition at line 80 of file window\&.py\&.
.SS "def autoware_launcher\&.gui\&.window\&.AwMainWindow\&.save_profile_as ( self)"

.PP
Definition at line 83 of file window\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.window\&.AwMainWindow\&.client"

.PP
Definition at line 29 of file window\&.py\&.
.SS "autoware_launcher\&.gui\&.window\&.AwMainWindow\&.filemenu"

.PP
Definition at line 43 of file window\&.py\&.
.SS "autoware_launcher\&.gui\&.window\&.AwMainWindow\&.viewmenu"

.PP
Definition at line 44 of file window\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
