.TH "autoware_launcher.gui.widgets.AwAbstructFrame" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.widgets.AwAbstructFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.PP
Inherited by \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwBooleanFrame\fP, \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwIntegerFrame\fP, \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwRealFrame\fP, \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwTextFrame\fP, \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwTextListFrame\fP, \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwTransformFrame\fP, and \fBautoware_launcher\&.gui\&.plugins\&.node\&.AwDefaultNodeFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBguimgr\fP, \fBnode\fP, \fBview\fP)"
.br
.ti -1c
.RI "def \fBsetup_widget\fP (self)"
.br
.ti -1c
.RI "def \fBset_title\fP (self, \fBtitle\fP)"
.br
.ti -1c
.RI "def \fBadd_button\fP (self, button)"
.br
.ti -1c
.RI "def \fBadd_widget\fP (self, widget)"
.br
.ti -1c
.RI "def \fBadd_text_widget\fP (self, text)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBguimgr\fP"
.br
.ti -1c
.RI "\fBnode\fP"
.br
.ti -1c
.RI "\fBview\fP"
.br
.ti -1c
.RI "\fBtitle\fP"
.br
.ti -1c
.RI "\fBheader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file widgets\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.__init__ ( self,  guimgr,  node,  view)"

.PP
Definition at line 64 of file widgets\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.add_button ( self,  button)"

.PP
Definition at line 107 of file widgets\&.py\&.
.SS "def autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.add_text_widget ( self,  text)"

.PP
Definition at line 114 of file widgets\&.py\&.
.SS "def autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.add_widget ( self,  widget)"

.PP
Definition at line 110 of file widgets\&.py\&.
.SS "def autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.set_title ( self,  title)"

.PP
Definition at line 104 of file widgets\&.py\&.
.SS "def autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.setup_widget ( self)"

.PP
Definition at line 70 of file widgets\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.guimgr"

.PP
Definition at line 66 of file widgets\&.py\&.
.SS "autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.header"

.PP
Definition at line 83 of file widgets\&.py\&.
.SS "autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.node"

.PP
Definition at line 67 of file widgets\&.py\&.
.SS "autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.title"

.PP
Definition at line 79 of file widgets\&.py\&.
.SS "autoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\&.view"

.PP
Definition at line 68 of file widgets\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
