.TH "autoware_camera_calibration.calibrator.ChessboardInfo" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_camera_calibration.calibrator.ChessboardInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBn_cols\fP=0, \fBn_rows\fP=0, \fBdim\fP=0\&.0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBn_cols\fP"
.br
.ti -1c
.RI "\fBn_rows\fP"
.br
.ti -1c
.RI "\fBdim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file calibrator\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_camera_calibration\&.calibrator\&.ChessboardInfo\&.__init__ ( self,  n_cols = \fC0\fP,  n_rows = \fC0\fP,  dim = \fC0\&.0\fP)"

.PP
Definition at line 83 of file calibrator\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_camera_calibration\&.calibrator\&.ChessboardInfo\&.dim"

.PP
Definition at line 86 of file calibrator\&.py\&.
.SS "autoware_camera_calibration\&.calibrator\&.ChessboardInfo\&.n_cols"

.PP
Definition at line 84 of file calibrator\&.py\&.
.SS "autoware_camera_calibration\&.calibrator\&.ChessboardInfo\&.n_rows"

.PP
Definition at line 85 of file calibrator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
