.TH "autoware_launcher.core.server.AwLaunchServerIF" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.server.AwLaunchServerIF \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBautoware_launcher\&.core\&.server\&.AwLaunchServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBmake_profile\fP (self, ppath)"
.br
.ti -1c
.RI "def \fBload_profile\fP (self, fpath)"
.br
.ti -1c
.RI "def \fBsave_profile\fP (self, fpath)"
.br
.ti -1c
.RI "def \fBlist_node\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBfind_node\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBupdate_node\fP (self, lpath, ldata)"
.br
.ti -1c
.RI "def \fBcreate_node\fP (self, lpath, ppath)"
.br
.ti -1c
.RI "def \fBremove_node\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBlaunch_node\fP (self, lpath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file server\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.create_node ( self,  lpath,  ppath)"

.PP
Definition at line 18 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.find_node ( self,  lpath)"

.PP
Definition at line 16 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.launch_node ( self,  lpath)"

.PP
Definition at line 20 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.list_node ( self,  lpath)"

.PP
Definition at line 15 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.load_profile ( self,  fpath)"

.PP
Definition at line 13 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.make_profile ( self,  ppath)"

.PP
Definition at line 12 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.remove_node ( self,  lpath)"

.PP
Definition at line 19 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.save_profile ( self,  fpath)"

.PP
Definition at line 14 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServerIF\&.update_node ( self,  lpath,  ldata)"

.PP
Definition at line 17 of file server\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
