.TH "autoware_connector::VehicleInfo" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_connector::VehicleInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <can_odometry_core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVehicleInfo\fP ()"
.br
.ti -1c
.RI "double \fBconvertSteeringAngleToAngularVelocity\fP (const double cur_vel_mps, const double cur_angle_deg)"
.br
.ti -1c
.RI "double \fBgetCurrentTireAngle\fP (const double angle_deg)"
.br
.ti -1c
.RI "double \fBgetMaximumTireAngle\fP ()"
.br
.ti -1c
.RI "\fBVehicleInfo\fP ()"
.br
.ti -1c
.RI "double \fBconvertSteeringAngleToAngularVelocity\fP (const double cur_vel_mps, const double cur_angle_deg)"
.br
.ti -1c
.RI "double \fBgetCurrentTireAngle\fP (const double angle_deg)"
.br
.ti -1c
.RI "double \fBgetMaximumTireAngle\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBis_stored\fP"
.br
.ti -1c
.RI "double \fBwheel_base\fP"
.br
.ti -1c
.RI "double \fBminimum_turning_radius\fP"
.br
.ti -1c
.RI "double \fBmaximum_steering_angle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file can_odometry_core\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "autoware_connector::VehicleInfo::VehicleInfo ()\fC [inline]\fP"

.PP
Definition at line 62 of file can_odometry_core\&.h\&.
.SS "autoware_connector::VehicleInfo::VehicleInfo ()\fC [inline]\fP"

.PP
Definition at line 61 of file can_status_translator_core\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double autoware_connector::VehicleInfo::convertSteeringAngleToAngularVelocity (const double cur_vel_mps, const double cur_angle_deg)\fC [inline]\fP"

.PP
Definition at line 68 of file can_status_translator_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::convertSteeringAngleToAngularVelocity (const double cur_vel_mps, const double cur_angle_deg)\fC [inline]\fP"

.PP
Definition at line 69 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::getCurrentTireAngle (const double angle_deg)\fC [inline]\fP"

.PP
Definition at line 72 of file can_status_translator_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::getCurrentTireAngle (const double angle_deg)\fC [inline]\fP"

.PP
Definition at line 73 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::getMaximumTireAngle ()\fC [inline]\fP"

.PP
Definition at line 76 of file can_status_translator_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::getMaximumTireAngle ()\fC [inline]\fP"

.PP
Definition at line 77 of file can_odometry_core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool autoware_connector::VehicleInfo::is_stored"

.PP
Definition at line 57 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::maximum_steering_angle"

.PP
Definition at line 60 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::minimum_turning_radius"

.PP
Definition at line 59 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::VehicleInfo::wheel_base"

.PP
Definition at line 58 of file can_odometry_core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
