.TH "autoware_sim_object::AutowareSimObjTool" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_sim_object::AutowareSimObjTool \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <autoware_flag_tool\&.h>\fP
.PP
Inherits Tool\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutowareSimObjTool\fP ()"
.br
.ti -1c
.RI "\fB~AutowareSimObjTool\fP ()"
.br
.ti -1c
.RI "virtual void \fBonInitialize\fP ()"
.br
.ti -1c
.RI "virtual void \fBactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBdeactivate\fP ()"
.br
.ti -1c
.RI "virtual int \fBprocessMouseEvent\fP (rviz::ViewportMouseEvent &event)"
.br
.ti -1c
.RI "virtual void \fBload\fP (const rviz::Config &config)"
.br
.ti -1c
.RI "virtual void \fBsave\fP (rviz::Config config) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file autoware_flag_tool\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "autoware_sim_object::AutowareSimObjTool::AutowareSimObjTool ()"

.PP
Definition at line 50 of file autoware_flag_tool\&.cpp\&.
.SS "autoware_sim_object::AutowareSimObjTool::~AutowareSimObjTool ()"

.PP
Definition at line 58 of file autoware_flag_tool\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void autoware_sim_object::AutowareSimObjTool::activate ()\fC [virtual]\fP"

.PP
Definition at line 82 of file autoware_flag_tool\&.cpp\&.
.SS "void autoware_sim_object::AutowareSimObjTool::deactivate ()\fC [virtual]\fP"

.PP
Definition at line 94 of file autoware_flag_tool\&.cpp\&.
.SS "void autoware_sim_object::AutowareSimObjTool::load (const rviz::Config & config)\fC [virtual]\fP"

.PP
Definition at line 169 of file autoware_flag_tool\&.cpp\&.
.SS "void autoware_sim_object::AutowareSimObjTool::onInitialize ()\fC [virtual]\fP"

.PP
Definition at line 66 of file autoware_flag_tool\&.cpp\&.
.SS "int autoware_sim_object::AutowareSimObjTool::processMouseEvent (rviz::ViewportMouseEvent & event)\fC [virtual]\fP"

.PP
Definition at line 104 of file autoware_flag_tool\&.cpp\&.
.SS "void autoware_sim_object::AutowareSimObjTool::save (rviz::Config config) const\fC [virtual]\fP"

.PP
Definition at line 153 of file autoware_flag_tool\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
