.TH "autoware_connector::Odometry" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_connector::Odometry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <can_odometry_core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOdometry\fP (const ros::Time &time)"
.br
.ti -1c
.RI "void \fBupdateOdometry\fP (const double vx, const double vth, const ros::Time &cur_time)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBth\fP"
.br
.ti -1c
.RI "ros::Time \fBstamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file can_odometry_core\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "autoware_connector::Odometry::Odometry (const ros::Time & time)\fC [inline]\fP"

.PP
Definition at line 90 of file can_odometry_core\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void autoware_connector::Odometry::updateOdometry (const double vx, const double vth, const ros::Time & cur_time)\fC [inline]\fP"

.PP
Definition at line 98 of file can_odometry_core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "ros::Time autoware_connector::Odometry::stamp"

.PP
Definition at line 88 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::Odometry::th"

.PP
Definition at line 87 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::Odometry::x"

.PP
Definition at line 85 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::Odometry::y"

.PP
Definition at line 86 of file can_odometry_core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
