.TH "autoware_launcher.gui.procmgr.AwProcessPanel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.procmgr.AwProcessPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QStackedWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, client)"
.br
.ti -1c
.RI "def \fBprofile_ui_cleared\fP (self)"
.br
.ti -1c
.RI "def \fBnode_ui_updated\fP (self, lnode)"
.br
.ti -1c
.RI "def \fBnode_ui_created\fP (self, lnode)"
.br
.ti -1c
.RI "def \fBconfig_selected\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBroslaunch\fP (self, lpath, xtext)"
.br
.ti -1c
.RI "def \fBterminate\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBregister_server\fP (self, server)"
.br
.ti -1c
.RI "def \fBrunner_finished\fP (self, lpath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file procmgr\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.__init__ ( self,  client)"

.PP
Definition at line 11 of file procmgr\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.config_selected ( self,  lpath)"

.PP
Definition at line 39 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.node_ui_created ( self,  lnode)"

.PP
Definition at line 30 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.node_ui_updated ( self,  lnode)"

.PP
Definition at line 27 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.profile_ui_cleared ( self)"

.PP
Definition at line 23 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.register_server ( self,  server)"

.PP
Definition at line 52 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.roslaunch ( self,  lpath,  xtext)"

.PP
Definition at line 43 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.runner_finished ( self,  lpath)"

.PP
Definition at line 55 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessPanel\&.terminate ( self,  lpath)"

.PP
Definition at line 49 of file procmgr\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
