.TH "autoware_connector::CanStatusTranslatorNode" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_connector::CanStatusTranslatorNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <can_status_translator_core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCanStatusTranslatorNode\fP ()"
.br
.ti -1c
.RI "\fB~CanStatusTranslatorNode\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file can_status_translator_core\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "autoware_connector::CanStatusTranslatorNode::CanStatusTranslatorNode ()"

.PP
Definition at line 22 of file can_status_translator_core\&.cpp\&.
.SS "autoware_connector::CanStatusTranslatorNode::~CanStatusTranslatorNode ()"

.PP
Definition at line 28 of file can_status_translator_core\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void autoware_connector::CanStatusTranslatorNode::run ()"

.PP
Definition at line 64 of file can_status_translator_core\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
