.TH "autoware_launcher.core.mylog" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.mylog \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBerror\fP (text)"
.br
.ti -1c
.RI "def \fBwarning\fP (text)"
.br
.ti -1c
.RI "def \fBinfo\fP (text)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.mylog\&.error ( text)"

.PP
Definition at line 3 of file mylog\&.py\&.
.SS "def autoware_launcher\&.core\&.mylog\&.info ( text)"

.PP
Definition at line 9 of file mylog\&.py\&.
.SS "def autoware_launcher\&.core\&.mylog\&.warning ( text)"

.PP
Definition at line 6 of file mylog\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
