.TH "autoware_launcher_rviz::ModulePanel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher_rviz::ModulePanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <module_panel\&.hpp>\fP
.PP
Inherits Panel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModulePanel\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file module_panel\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "autoware_launcher_rviz::ModulePanel::ModulePanel (QWidget * parent = \fC0\fP)"

.PP
Definition at line 24 of file module_panel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void autoware_launcher_rviz::ModulePanel::paintEvent (QPaintEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 53 of file module_panel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
