.TH "autoware_launcher.core.basetree.AwBaseNode" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.basetree.AwBaseNode \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBautoware_launcher\&.core\&.plugin\&.AwPluginNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBtree\fP, \fBpath\fP)"
.br
.ti -1c
.RI "def \fBtree\fP (self)"
.br
.ti -1c
.RI "def \fBpath\fP (self)"
.br
.ti -1c
.RI "def \fBname\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file basetree\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.basetree\&.AwBaseNode\&.__init__ ( self,  tree,  path)"

.PP
Definition at line 24 of file basetree\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.basetree\&.AwBaseNode\&.name ( self)"

.PP
Definition at line 34 of file basetree\&.py\&.
.SS "def autoware_launcher\&.core\&.basetree\&.AwBaseNode\&.path ( self)"

.PP
Definition at line 31 of file basetree\&.py\&.
.SS "def autoware_launcher\&.core\&.basetree\&.AwBaseNode\&.tree ( self)"

.PP
Definition at line 28 of file basetree\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
