.TH "autoware_launcher.gui.plugins.basic.AwTextFrame" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.plugins.basic.AwTextFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBautoware_launcher\&.gui\&.widgets\&.AwAbstructFrame\fP\&.
.PP
Inherited by \fBautoware_launcher\&.gui\&.plugins\&.basic\&.AwFileFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBguimgr\fP, \fBnode\fP, \fBview\fP)"
.br
.ti -1c
.RI "def \fBapply\fP (self, value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBvalidate_argtypes\fP (fields, \fBview\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfield\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file basic\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.plugins\&.basic\&.AwTextFrame\&.__init__ ( self,  guimgr,  node,  view)"

.PP
Definition at line 32 of file basic\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.plugins\&.basic\&.AwTextFrame\&.apply ( self,  value)"

.PP
Definition at line 41 of file basic\&.py\&.
.SS "def autoware_launcher\&.gui\&.plugins\&.basic\&.AwTextFrame\&.validate_argtypes ( fields,  view)\fC [static]\fP"

.PP
Definition at line 45 of file basic\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.plugins\&.basic\&.AwTextFrame\&.field"

.PP
Definition at line 37 of file basic\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
