.TH "autoware_launcher.core.server" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.server \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAwLaunchClientIF\fP"
.br
.ti -1c
.RI "class \fBAwLaunchServer\fP"
.br
.ti -1c
.RI "class \fBAwLaunchServerIF\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = getLogger(__name__)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "autoware_launcher\&.core\&.server\&.logger = getLogger(__name__)"

.PP
Definition at line 2 of file server\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
