.TH "autoware_launcher.core.server.AwLaunchServer" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.server.AwLaunchServer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBautoware_launcher\&.core\&.server\&.AwLaunchServerIF\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, sysarg)"
.br
.ti -1c
.RI "def \fBregister_runner\fP (self, runner)"
.br
.ti -1c
.RI "def \fBregister_client\fP (self, client)"
.br
.ti -1c
.RI "def \fBmake_profile\fP (self, ppath)"
.br
.ti -1c
.RI "def \fBload_profile\fP (self, fpath)"
.br
.ti -1c
.RI "def \fBsave_profile\fP (self, fpath)"
.br
.ti -1c
.RI "def \fBexport_profile\fP (self, fpath)"
.br
.ti -1c
.RI "def \fBlist_node\fP (self)"
.br
.ti -1c
.RI "def \fBfind_node\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBupdate_node\fP (self, lpath, ldata)"
.br
.ti -1c
.RI "def \fBcreate_node\fP (self, lpath, ppath)"
.br
.ti -1c
.RI "def \fBremove_node\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBlaunch_node\fP (self, lpath, xmode)"
.br
.ti -1c
.RI "def \fBrunner_finished\fP (self, lpath)"
.br
.ti -1c
.RI "def \fBrequest_json\fP (self, request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file server\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.__init__ ( self,  sysarg)"

.PP
Definition at line 37 of file server\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.create_node ( self,  lpath,  ppath)"

.PP
Definition at line 83 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.export_profile ( self,  fpath)"

.PP
Definition at line 65 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.find_node ( self,  lpath)"

.PP
Definition at line 73 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.launch_node ( self,  lpath,  xmode)"

.PP
Definition at line 92 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.list_node ( self)"

.PP
Definition at line 69 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.load_profile ( self,  fpath)"

.PP
Definition at line 55 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.make_profile ( self,  ppath)"

.PP
Definition at line 49 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.register_client ( self,  client)"

.PP
Definition at line 46 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.register_runner ( self,  runner)"

.PP
Definition at line 43 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.remove_node ( self,  lpath)"

.PP
Definition at line 89 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.request_json ( self,  request)"

.PP
Definition at line 118 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.runner_finished ( self,  lpath)"

.PP
Definition at line 114 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.save_profile ( self,  fpath)"

.PP
Definition at line 61 of file server\&.py\&.
.SS "def autoware_launcher\&.core\&.server\&.AwLaunchServer\&.update_node ( self,  lpath,  ldata)"

.PP
Definition at line 77 of file server\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
