.TH "autoware_connector" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_connector \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCanOdometryNode\fP"
.br
.ti -1c
.RI "class \fBCanStatusTranslatorNode\fP"
.br
.ti -1c
.RI "struct \fBOdometry\fP"
.br
.ti -1c
.RI "struct \fBVehicleInfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBkmph2mps\fP (double velocity_kmph)"
.br
.ti -1c
.RI "double \fBmps2kmph\fP (double velocity_mps)"
.br
.ti -1c
.RI "double \fBdeg2rad\fP (double deg)"
.br
.ti -1c
.RI "double \fBrad2deg\fP (double rad)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double autoware_connector::deg2rad (double deg)\fC [inline]\fP"

.PP
Definition at line 44 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::kmph2mps (double velocity_kmph)\fC [inline]\fP"

.PP
Definition at line 33 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::mps2kmph (double velocity_mps)\fC [inline]\fP"

.PP
Definition at line 38 of file can_odometry_core\&.h\&.
.SS "double autoware_connector::rad2deg (double rad)\fC [inline]\fP"

.PP
Definition at line 50 of file can_odometry_core\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
