.TH "autoware_launcher.gui.plugins.node.AwPluginRemoveWindow" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.plugins.node.AwPluginRemoveWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBguimgr\fP, launch, parent)"
.br
.ti -1c
.RI "def \fBremove_launch_node\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBguimgr\fP"
.br
.ti -1c
.RI "\fBnode\fP"
.br
.ti -1c
.RI "\fBnodelist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 192 of file node\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.plugins\&.node\&.AwPluginRemoveWindow\&.__init__ ( self,  guimgr,  launch,  parent)"

.PP
Definition at line 194 of file node\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.plugins\&.node\&.AwPluginRemoveWindow\&.remove_launch_node ( self)"

.PP
Definition at line 227 of file node\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.plugins\&.node\&.AwPluginRemoveWindow\&.guimgr"

.PP
Definition at line 196 of file node\&.py\&.
.SS "autoware_launcher\&.gui\&.plugins\&.node\&.AwPluginRemoveWindow\&.node"

.PP
Definition at line 197 of file node\&.py\&.
.SS "autoware_launcher\&.gui\&.plugins\&.node\&.AwPluginRemoveWindow\&.nodelist"

.PP
Definition at line 204 of file node\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
