.TH "autoware_launcher.core.myutils" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.myutils \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBuserhome\fP (path='')"
.br
.ti -1c
.RI "def \fBpackage\fP (path='')"
.br
.ti -1c
.RI "def \fBplugins\fP ()"
.br
.ti -1c
.RI "def \fBprofile\fP (profile='')"
.br
.ti -1c
.RI "def \fBparentpath\fP (path)"
.br
.ti -1c
.RI "def \fBmakedirs\fP (path, mode=0o777, exist_ok=False)"
.br
.ti -1c
.RI "def \fBlistfiles\fP (rootpath, relative=False)"
.br
.ti -1c
.RI "def \fBenvpath\fP (path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.myutils\&.envpath ( path)"

.PP
Definition at line 37 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.listfiles ( rootpath,  relative = \fCFalse\fP)"

.PP
Definition at line 26 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.makedirs ( path,  mode = \fC0o777\fP,  exist_ok = \fCFalse\fP)"

.PP
Definition at line 23 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.package ( path = \fC''\fP)"

.PP
Definition at line 10 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.parentpath ( path)"

.PP
Definition at line 20 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.plugins ()"

.PP
Definition at line 14 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.profile ( profile = \fC''\fP)"

.PP
Definition at line 17 of file myutils\&.py\&.
.SS "def autoware_launcher\&.core\&.myutils\&.userhome ( path = \fC''\fP)"

.PP
Definition at line 7 of file myutils\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
