.TH "autoware_camera_calibration.camera_calibrator.ConsumerThread" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_camera_calibration.camera_calibrator.ConsumerThread \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBqueue\fP, \fBfunction\fP)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBqueue\fP"
.br
.ti -1c
.RI "\fBfunction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file camera_calibrator\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_camera_calibration\&.camera_calibrator\&.ConsumerThread\&.__init__ ( self,  queue,  function)"

.PP
Definition at line 97 of file camera_calibrator\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_camera_calibration\&.camera_calibrator\&.ConsumerThread\&.run ( self)"

.PP
Definition at line 102 of file camera_calibrator\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_camera_calibration\&.camera_calibrator\&.ConsumerThread\&.function"

.PP
Definition at line 100 of file camera_calibrator\&.py\&.
.SS "autoware_camera_calibration\&.camera_calibrator\&.ConsumerThread\&.queue"

.PP
Definition at line 99 of file camera_calibrator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
