.TH "autoware_camera_lidar_calibrator.test.directed.TestArtificial" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_camera_lidar_calibrator.test.directed.TestArtificial \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBassert_good_mono\fP (self, \fBc\fP, images, max_err)"
.br
.ti -1c
.RI "def \fBtest_monocular\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBK\fP"
.br
.ti -1c
.RI "\fBD\fP"
.br
.ti -1c
.RI "\fBboard_width_dim\fP"
.br
.ti -1c
.RI "\fBsetups\fP"
.br
.ti -1c
.RI "\fBlimages\fP"
.br
.ti -1c
.RI "\fBrimages\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBSetup\fP = collections\&.namedtuple('Setup', ['pattern', 'cols', 'rows', 'lin_err', 'K_err'])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file directed\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.assert_good_mono ( self,  c,  images,  max_err)"

.PP
Definition at line 228 of file directed\&.py\&.
.SS "def autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.setUp ( self)"

.PP
Definition at line 163 of file directed\&.py\&.
.SS "def autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.test_monocular ( self)"

.PP
Definition at line 247 of file directed\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.board_width_dim"

.PP
Definition at line 170 of file directed\&.py\&.
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.D"

.PP
Definition at line 168 of file directed\&.py\&.
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.K"

.PP
Definition at line 167 of file directed\&.py\&.
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.limages"

.PP
Definition at line 178 of file directed\&.py\&.
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.rimages"

.PP
Definition at line 179 of file directed\&.py\&.
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.Setup = collections\&.namedtuple('Setup', ['pattern', 'cols', 'rows', 'lin_err', 'K_err'])\fC [static]\fP"

.PP
Definition at line 161 of file directed\&.py\&.
.SS "autoware_camera_lidar_calibrator\&.test\&.directed\&.TestArtificial\&.setups"

.PP
Definition at line 175 of file directed\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
