.TH "autoware_launcher.core.plugin.AwPluginPanelElement" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.core.plugin.AwPluginPanelElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBdata\fP)"
.br
.ti -1c
.RI "def \fBtodict\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwidget\fP"
.br
.ti -1c
.RI "\fBframes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file plugin\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.plugin\&.AwPluginPanelElement\&.__init__ ( self,  data)"

.PP
Definition at line 190 of file plugin\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.core\&.plugin\&.AwPluginPanelElement\&.todict ( self)"

.PP
Definition at line 194 of file plugin\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.core\&.plugin\&.AwPluginPanelElement\&.frames"

.PP
Definition at line 192 of file plugin\&.py\&.
.SS "autoware_launcher\&.core\&.plugin\&.AwPluginPanelElement\&.widget"

.PP
Definition at line 191 of file plugin\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
