.TH "autoware_launcher.gui.mirror.AwLaunchTreeMirror" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.mirror.AwLaunchTreeMirror \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBclient\fP)"
.br
.ti -1c
.RI "def \fBclear\fP (self, lpath=None)"
.br
.ti -1c
.RI "def \fBfind\fP (self, path)"
.br
.ti -1c
.RI "def \fBcreate\fP (self, path)"
.br
.ti -1c
.RI "def \fBremove\fP (self, path, \fBnode\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnodes\fP"
.br
.ti -1c
.RI "\fBcache\fP"
.br
.ti -1c
.RI "\fBclient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file mirror\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.__init__ ( self,  client)"

.PP
Definition at line 6 of file mirror\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.clear ( self,  lpath = \fCNone\fP)"

.PP
Definition at line 11 of file mirror\&.py\&.
.SS "def autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.create ( self,  path)"

.PP
Definition at line 22 of file mirror\&.py\&.
.SS "def autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.find ( self,  path)"

.PP
Definition at line 17 of file mirror\&.py\&.
.SS "def autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.remove ( self,  path,  node)"

.PP
Definition at line 27 of file mirror\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.cache"

.PP
Definition at line 8 of file mirror\&.py\&.
.SS "autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.client"

.PP
Definition at line 9 of file mirror\&.py\&.
.SS "autoware_launcher\&.gui\&.mirror\&.AwLaunchTreeMirror\&.nodes"

.PP
Definition at line 7 of file mirror\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
