.TH "autoware_launcher.gui.procmgr.AwProcessItem" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.procmgr.AwProcessItem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QPlainTextEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBlpath\fP)"
.br
.ti -1c
.RI "def \fBproc_finished\fP (self)"
.br
.ti -1c
.RI "def \fBproc_stdouted\fP (self)"
.br
.ti -1c
.RI "def \fBproc_stderred\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlpath\fP"
.br
.ti -1c
.RI "\fBproc\fP"
.br
.ti -1c
.RI "\fBbash_regex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file procmgr\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.__init__ ( self,  lpath)"

.PP
Definition at line 62 of file procmgr\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.proc_finished ( self)"

.PP
Definition at line 78 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.proc_stderred ( self)"

.PP
Definition at line 89 of file procmgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.proc_stdouted ( self)"

.PP
Definition at line 81 of file procmgr\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.bash_regex"

.PP
Definition at line 76 of file procmgr\&.py\&.
.SS "autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.lpath"

.PP
Definition at line 64 of file procmgr\&.py\&.
.SS "autoware_launcher\&.gui\&.procmgr\&.AwProcessItem\&.proc"

.PP
Definition at line 70 of file procmgr\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
