.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_rviz_plugins/rosbag_controller/src/autoware_rosbag_plugin.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_rviz_plugins/rosbag_controller/src/autoware_rosbag_plugin.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QEvent>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QStatusBar>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QTabWidget>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include 'rviz/visualization_manager\&.h'\fP
.br
\fC#include 'rviz/render_panel\&.h'\fP
.br
\fC#include 'rviz/display\&.h'\fP
.br
\fC#include 'rviz/panel\&.h'\fP
.br
\fC#include 'rviz/default_plugin/tools/measure_tool\&.h'\fP
.br
\fC#include 'rviz/tool_manager\&.h'\fP
.br
\fC#include 'rviz/default_plugin/tools/point_tool\&.h'\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <rosbag/bag\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include '\&.\&./src/core/recorder\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutoware_Rosbag_Plugin\fP"
.br
.ti -1c
.RI "struct \fBAutoware_Rosbag_Plugin::RecordParam\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
