.TH "autoware_launcher.gui.guimgr.AwQtGuiManager" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.guimgr.AwQtGuiManager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBclient\fP)"
.br
.ti -1c
.RI "def \fBclient\fP (self)"
.br
.ti -1c
.RI "def \fBwidget\fP (self, view)"
.br
.ti -1c
.RI "def \fBcreate_widget\fP (self, \fBnode\fP, view, parent=None, \fBwidget\fP=None)"
.br
.ti -1c
.RI "def \fBcreate_frame\fP (self, mirror, guikey=None, guicls=None)"
.br
.ti -1c
.RI "def \fBcreate_panel\fP (self, mirror, guikey=None, guicls=None)"
.br
.ti -1c
.RI "def \fBcreate_arg_frame\fP (self, parent, opts)"
.br
.ti -1c
.RI "def \fBcreate_info_frame\fP (self, parent, opts)"
.br
.ti -1c
.RI "def \fBcreate_frame_entire_vlayout\fP (self)"
.br
.ti -1c
.RI "def \fBcreate_frame_header_hlayout\fP (self)"
.br
.ti -1c
.RI "def \fBpanel_add_widget\fP (self, panel, \fBwidget\fP)"
.br
.ti -1c
.RI "def \fBpanel_setup\fP (self, \fBwidget\fP, spacer=None)"
.br
.ti -1c
.RI "def \fBframe_add_widget\fP (self, frame, \fBwidget\fP)"
.br
.ti -1c
.RI "def \fBframe_add_button\fP (self, frame, button)"
.br
.ti -1c
.RI "def \fBframe_add_text_widget\fP (self, frame, text)"
.br
.ti -1c
.RI "def \fBframe_setup\fP (self, \fBwidget\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file guimgr\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.__init__ ( self,  client)"

.PP
Definition at line 18 of file guimgr\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.client ( self)"

.PP
Definition at line 28 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_arg_frame ( self,  parent,  opts)"

.PP
Definition at line 52 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_frame ( self,  mirror,  guikey = \fCNone\fP,  guicls = \fCNone\fP)"

.PP
Definition at line 38 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_frame_entire_vlayout ( self)"

.PP
Definition at line 60 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_frame_header_hlayout ( self)"

.PP
Definition at line 66 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_info_frame ( self,  parent,  opts)"

.PP
Definition at line 56 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_panel ( self,  mirror,  guikey = \fCNone\fP,  guicls = \fCNone\fP)"

.PP
Definition at line 45 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.create_widget ( self,  node,  view,  parent = \fCNone\fP,  widget = \fCNone\fP)"

.PP
Definition at line 34 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.frame_add_button ( self,  frame,  button)"

.PP
Definition at line 117 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.frame_add_text_widget ( self,  frame,  text)"

.PP
Definition at line 120 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.frame_add_widget ( self,  frame,  widget)"

.PP
Definition at line 113 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.frame_setup ( self,  widget)"

.PP
Definition at line 127 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.panel_add_widget ( self,  panel,  widget)"

.PP
Definition at line 72 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.panel_setup ( self,  widget,  spacer = \fCNone\fP)"

.PP
Definition at line 77 of file guimgr\&.py\&.
.SS "def autoware_launcher\&.gui\&.guimgr\&.AwQtGuiManager\&.widget ( self,  view)"

.PP
Definition at line 31 of file guimgr\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
