.TH "autoware_launcher.gui.widgets.AwFileSelect" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
autoware_launcher.gui.widgets.AwFileSelect \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent)"
.br
.ti -1c
.RI "def \fBbrowse\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpath\fP"
.br
.ti -1c
.RI "\fBbutton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file widgets\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.widgets\&.AwFileSelect\&.__init__ ( self,  parent)"

.PP
Definition at line 125 of file widgets\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def autoware_launcher\&.gui\&.widgets\&.AwFileSelect\&.browse ( self)"

.PP
Definition at line 131 of file widgets\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "autoware_launcher\&.gui\&.widgets\&.AwFileSelect\&.button"

.PP
Definition at line 128 of file widgets\&.py\&.
.SS "autoware_launcher\&.gui\&.widgets\&.AwFileSelect\&.path"

.PP
Definition at line 127 of file widgets\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
