.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/op_utilities/include/BagTopicPlayer.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/op_utilities/include/BagTopicPlayer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rosbag/bag\&.h>\fP
.br
\fC#include <rosbag/view\&.h>\fP
.br
\fC#include <rosbag/player\&.h>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUtilityHNS::BagTopicPlayer< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUtilityHNS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBforeach\fP   BOOST_FOREACH"
.br
.ti -1c
.RI "#define \fBMAX_RECORDS_BUFFER\fP   25"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define foreach   BOOST_FOREACH"

.PP
Definition at line 26 of file BagTopicPlayer\&.h\&.
.SS "#define MAX_RECORDS_BUFFER   25"

.PP
Definition at line 33 of file BagTopicPlayer\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
