.TH "baseframe.BaseFrame" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseframe.BaseFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Frame\&.
.PP
Inherited by \fBinsidedesign\&.InsideDesign\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, args, kwds)"
.br
.ti -1c
.RI "def \fBset_properties\fP (self)"
.br
.ti -1c
.RI "def \fBOnLaunchKill\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnSetupLocalizer\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnCalibrationPublisher\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnLamp\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnIndi\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnGear\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnQuery\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnROSbagPlay\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnFtrace\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnEcho\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnRefreshTopics\fP (self, event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file baseframe\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def baseframe\&.BaseFrame\&.__init__ ( self,  args,  kwds)"

.PP
Definition at line 8 of file baseframe\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def baseframe\&.BaseFrame\&.OnCalibrationPublisher ( self,  event)"

.PP
Definition at line 30 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnEcho ( self,  event)"

.PP
Definition at line 58 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnFtrace ( self,  event)"

.PP
Definition at line 54 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnGear ( self,  event)"

.PP
Definition at line 42 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnIndi ( self,  event)"

.PP
Definition at line 38 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnLamp ( self,  event)"

.PP
Definition at line 34 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnLaunchKill ( self,  event)"

.PP
Definition at line 22 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnQuery ( self,  event)"

.PP
Definition at line 46 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnRefreshTopics ( self,  event)"

.PP
Definition at line 62 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnROSbagPlay ( self,  event)"

.PP
Definition at line 50 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.OnSetupLocalizer ( self,  event)"

.PP
Definition at line 26 of file baseframe\&.py\&.
.SS "def baseframe\&.BaseFrame\&.set_properties ( self)"

.PP
Definition at line 15 of file baseframe\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
