.TH "beyondtrack::ObjectCuboid_" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
beyondtrack::ObjectCuboid_ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <detection\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectCuboid_\fP (double avg_car_sz[3], double sz_ub[3], double sz_lb[3])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBavg_l\fP"
.br
.ti -1c
.RI "double \fBavg_h\fP"
.br
.ti -1c
.RI "double \fBavg_w\fP"
.br
.ti -1c
.RI "double \fBsz_ub_l\fP"
.br
.ti -1c
.RI "double \fBsz_ub_h\fP"
.br
.ti -1c
.RI "double \fBsz_ub_w\fP"
.br
.ti -1c
.RI "double \fBsz_lb_l\fP"
.br
.ti -1c
.RI "double \fBsz_lb_h\fP"
.br
.ti -1c
.RI "double \fBsz_lb_w\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file detection\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "beyondtrack::ObjectCuboid_::ObjectCuboid_ (double avg_car_sz[3], double sz_ub[3], double sz_lb[3])\fC [inline]\fP"

.PP
Definition at line 59 of file detection\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double beyondtrack::ObjectCuboid_::avg_h"

.PP
Definition at line 55 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::avg_l"

.PP
Definition at line 55 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::avg_w"

.PP
Definition at line 55 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::sz_lb_h"

.PP
Definition at line 57 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::sz_lb_l"

.PP
Definition at line 57 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::sz_lb_w"

.PP
Definition at line 57 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::sz_ub_h"

.PP
Definition at line 56 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::sz_ub_l"

.PP
Definition at line 56 of file detection\&.h\&.
.SS "double beyondtrack::ObjectCuboid_::sz_ub_w"

.PP
Definition at line 56 of file detection\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
