.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/camera/packages/baumer/nodes/vlg22/src/bgapi_init.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/camera/packages/baumer/nodes/vlg22/src/bgapi_init.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <bgapidef\&.hpp>\fP
.br
\fC#include 'bgapi\&.hpp'\fP
.br
\fC#include 'bgapi_init\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_systems\fP (int *system_count, std::vector< BGAPI::System * > *externppSystem)"
.br
.ti -1c
.RI "void \fBstop_cameras\fP (std::vector< BGAPI::Camera * > &cameraObjects)"
.br
.ti -1c
.RI "bool \fBstart_cameras\fP (std::vector< BGAPI::Camera * > &cameraObjects)"
.br
.ti -1c
.RI "bool \fBsetup_cameras\fP (std::vector< BGAPI::Camera * > &cameraObjects, std::string camera_pixel_format_str)"
.br
.ti -1c
.RI "int \fBinit_cameras\fP (int system_count, std::vector< BGAPI::System * > *externppSystem, int *pCurrSystem, int &camera_count, std::vector< BGAPI::Camera * > &cameraObjects)"
.br
.ti -1c
.RI "int \fBrelease_systems\fP (std::vector< BGAPI::System * > *externppSystem)"
.br
.ti -1c
.RI "int \fBrelease_images\fP (std::vector< BGAPI::Image * > *ppImage)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int init_cameras (int system_count, std::vector< BGAPI::System * > * externppSystem, int * pCurrSystem, int & camera_count, std::vector< BGAPI::Camera * > & cameraObjects)"

.PP
Definition at line 223 of file bgapi_init\&.cpp\&.
.SS "int init_systems (int * system_count, std::vector< BGAPI::System * > * externppSystem)"

.PP
Definition at line 5 of file bgapi_init\&.cpp\&.
.SS "int release_images (std::vector< BGAPI::Image * > * ppImage)"

.PP
Definition at line 326 of file bgapi_init\&.cpp\&.
.SS "int release_systems (std::vector< BGAPI::System * > * externppSystem)"

.PP
Definition at line 310 of file bgapi_init\&.cpp\&.
.SS "bool setup_cameras (std::vector< BGAPI::Camera * > & cameraObjects, std::string camera_pixel_format_str)"

.PP
Definition at line 70 of file bgapi_init\&.cpp\&.
.SS "bool start_cameras (std::vector< BGAPI::Camera * > & cameraObjects)"

.PP
Definition at line 53 of file bgapi_init\&.cpp\&.
.SS "void stop_cameras (std::vector< BGAPI::Camera * > & cameraObjects)"

.PP
Definition at line 40 of file bgapi_init\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
