.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/src/box.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/src/box.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'darknet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdbox\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBbox_rmse\fP (\fBbox\fP a, \fBbox\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBdbox\fP \fBdiou\fP (\fBbox\fP a, \fBbox\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBbox\fP \fBdecode_box\fP (\fBbox\fP \fBb\fP, \fBbox\fP anchor)"
.br
.ti -1c
.RI "\fBbox\fP \fBencode_box\fP (\fBbox\fP \fBb\fP, \fBbox\fP anchor)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float box_rmse (\fBbox\fP a, \fBbox\fP b)"

.PP
Definition at line 184 of file box\&.c\&.
.SS "\fBbox\fP decode_box (\fBbox\fP b, \fBbox\fP anchor)"

.PP
Definition at line 349 of file box\&.c\&.
.SS "\fBdbox\fP diou (\fBbox\fP a, \fBbox\fP b)"

.PP
Definition at line 295 of file box\&.c\&.
.SS "\fBbox\fP encode_box (\fBbox\fP b, \fBbox\fP anchor)"

.PP
Definition at line 339 of file box\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
