.TH "box_label" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
box_label \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <darknet\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBleft\fP"
.br
.ti -1c
.RI "float \fBright\fP"
.br
.ti -1c
.RI "float \fBtop\fP"
.br
.ti -1c
.RI "float \fBbottom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 579 of file darknet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float box_label::bottom"

.PP
Definition at line 582 of file darknet\&.h\&.
.SS "float box_label::h"

.PP
Definition at line 581 of file darknet\&.h\&.
.SS "int box_label::id"

.PP
Definition at line 580 of file darknet\&.h\&.
.SS "float box_label::left"

.PP
Definition at line 582 of file darknet\&.h\&.
.SS "float box_label::right"

.PP
Definition at line 582 of file darknet\&.h\&.
.SS "float box_label::top"

.PP
Definition at line 582 of file darknet\&.h\&.
.SS "float box_label::w"

.PP
Definition at line 581 of file darknet\&.h\&.
.SS "float box_label::x"

.PP
Definition at line 581 of file darknet\&.h\&.
.SS "float box_label::y"

.PP
Definition at line 581 of file darknet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
