.TH "BufferFile" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BufferFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <region_tlr_mxnet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBufferFile\fP (std::string file_path)"
.br
.ti -1c
.RI "int \fBGetLength\fP ()"
.br
.ti -1c
.RI "char * \fBGetBuffer\fP ()"
.br
.ti -1c
.RI "\fB~BufferFile\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfile_path_\fP"
.br
.ti -1c
.RI "int \fBlength_\fP"
.br
.ti -1c
.RI "char * \fBbuffer_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file region_tlr_mxnet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BufferFile::BufferFile (std::string file_path)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 26 of file region_tlr_mxnet\&.h\&.
.SS "BufferFile::~BufferFile ()\fC [inline]\fP"

.PP
Definition at line 54 of file region_tlr_mxnet\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "char* BufferFile::GetBuffer ()\fC [inline]\fP"

.PP
Definition at line 50 of file region_tlr_mxnet\&.h\&.
.SS "int BufferFile::GetLength ()\fC [inline]\fP"

.PP
Definition at line 47 of file region_tlr_mxnet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* BufferFile::buffer_"

.PP
Definition at line 24 of file region_tlr_mxnet\&.h\&.
.SS "std::string BufferFile::file_path_"

.PP
Definition at line 22 of file region_tlr_mxnet\&.h\&.
.SS "int BufferFile::length_"

.PP
Definition at line 23 of file region_tlr_mxnet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
