.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/can/packages/kvaser/nodes/can_draw/can_draw.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/can/packages/kvaser/nodes/can_draw/can_draw.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include 'autoware_can_msgs/CANPacket\&.h'\fP
.br
\fC#include <visualization_msgs/Marker\&.h>\fP
.br
\fC#include <visualization_msgs/MarkerArray\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBchatterCallback\fP (const autoware_can_msgs::CANPacket::ConstPtr &msg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ros::Publisher \fBpub\fP"
.br
.ti -1c
.RI "double \fBg_steer\fP"
.br
.ti -1c
.RI "double \fBg_speed\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void chatterCallback (const autoware_can_msgs::CANPacket::ConstPtr & msg)"

.PP
Definition at line 10 of file can_draw\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 87 of file can_draw\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "double g_speed"

.PP
Definition at line 8 of file can_draw\&.cpp\&.
.SS "double g_steer"

.PP
Definition at line 8 of file can_draw\&.cpp\&.
.SS "ros::Publisher pub"

.PP
Definition at line 7 of file can_draw\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
