.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/can/packages/kvaser/nodes/can_listener/can_listener.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/can/packages/kvaser/nodes/can_listener/can_listener.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <canlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include 'autoware_can_msgs/CANPacket\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsighand\fP (int sig)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBi\fP = 0"
.br
.ti -1c
.RI "unsigned char \fBwillExit\fP = 0"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "time_t \fBlast_time\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 84 of file can_listener\&.cpp\&.
.SS "void sighand (int sig)"

.PP
Definition at line 73 of file can_listener\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int i = 0"

.PP
Definition at line 67 of file can_listener\&.cpp\&.
.SS "int last"

.PP
Definition at line 69 of file can_listener\&.cpp\&.
.SS "time_t last_time = 0"

.PP
Definition at line 70 of file can_listener\&.cpp\&.
.SS "unsigned char willExit = 0"

.PP
Definition at line 68 of file can_listener\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
