.TH "CarSimulatorNS::SimuCommandParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CarSimulatorNS::SimuCommandParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <op_car_simulator_core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimuCommandParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "std::string \fBKmlMapPath\fP"
.br
.ti -1c
.RI "std::string \fBstrID\fP"
.br
.ti -1c
.RI "std::string \fBmeshPath\fP"
.br
.ti -1c
.RI "std::string \fBlogPath\fP"
.br
.ti -1c
.RI "\fBMAP_SOURCE_TYPE\fP \fBmapSource\fP"
.br
.ti -1c
.RI "bool \fBbRvizPositions\fP"
.br
.ti -1c
.RI "bool \fBbLooper\fP"
.br
.ti -1c
.RI "\fBPlannerHNS::WayPoint\fP \fBstartPose\fP"
.br
.ti -1c
.RI "\fBPlannerHNS::WayPoint\fP \fBgoalPose\fP"
.br
.ti -1c
.RI "std_msgs::ColorRGBA \fBmodelColor\fP"
.br
.ti -1c
.RI "bool \fBbEnableLogs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file op_car_simulator_core\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CarSimulatorNS::SimuCommandParams::SimuCommandParams ()\fC [inline]\fP"

.PP
Definition at line 89 of file op_car_simulator_core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CarSimulatorNS::SimuCommandParams::bEnableLogs"

.PP
Definition at line 87 of file op_car_simulator_core\&.h\&.
.SS "bool CarSimulatorNS::SimuCommandParams::bLooper"

.PP
Definition at line 83 of file op_car_simulator_core\&.h\&.
.SS "bool CarSimulatorNS::SimuCommandParams::bRvizPositions"

.PP
Definition at line 82 of file op_car_simulator_core\&.h\&.
.SS "\fBPlannerHNS::WayPoint\fP CarSimulatorNS::SimuCommandParams::goalPose"

.PP
Definition at line 85 of file op_car_simulator_core\&.h\&.
.SS "int CarSimulatorNS::SimuCommandParams::id"

.PP
Definition at line 76 of file op_car_simulator_core\&.h\&.
.SS "std::string CarSimulatorNS::SimuCommandParams::KmlMapPath"

.PP
Definition at line 77 of file op_car_simulator_core\&.h\&.
.SS "std::string CarSimulatorNS::SimuCommandParams::logPath"

.PP
Definition at line 80 of file op_car_simulator_core\&.h\&.
.SS "\fBMAP_SOURCE_TYPE\fP CarSimulatorNS::SimuCommandParams::mapSource"

.PP
Definition at line 81 of file op_car_simulator_core\&.h\&.
.SS "std::string CarSimulatorNS::SimuCommandParams::meshPath"

.PP
Definition at line 79 of file op_car_simulator_core\&.h\&.
.SS "std_msgs::ColorRGBA CarSimulatorNS::SimuCommandParams::modelColor"

.PP
Definition at line 86 of file op_car_simulator_core\&.h\&.
.SS "\fBPlannerHNS::WayPoint\fP CarSimulatorNS::SimuCommandParams::startPose"

.PP
Definition at line 84 of file op_car_simulator_core\&.h\&.
.SS "std::string CarSimulatorNS::SimuCommandParams::strID"

.PP
Definition at line 78 of file op_car_simulator_core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
