.TH "CarSimulatorNS" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CarSimulatorNS \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpenPlannerCarSimulator\fP"
.br
.ti -1c
.RI "class \fBSimuCommandParams\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMAP_SOURCE_TYPE\fP { \fBMAP_AUTOWARE\fP, \fBMAP_FOLDER\fP, \fBMAP_KML_FILE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCarSimulatorNS::MAP_SOURCE_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAP_AUTOWARE \fP\fP
.TP
\fB\fIMAP_FOLDER \fP\fP
.TP
\fB\fIMAP_KML_FILE \fP\fP
.PP
Definition at line 71 of file op_car_simulator_core\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
