.TH "ChangeConfig" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChangeConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HevCnt\&.h>\fP
.PP
Inherited by \fBHevComm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdateConfig\fP (int num, int index, int \fBdata\fP[])=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 156 of file HevCnt\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void ChangeConfig::UpdateConfig (int num, int index, int data[])\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
