.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_bag_tools/scripts/change_frame_id.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_bag_tools/scripts/change_frame_id.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBchange_frame_id\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBchange_frame_id\&.change_frame_id\fP (inbag, outbag, frame_ids, topics)"
.br
.ti -1c
.RI "def \fBchange_frame_id\&.progress_bar\fP (iteration, total)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBchange_frame_id\&.PKG\fP = 'autoware_bag_tools'"
.br
.ti -1c
.RI "\fBchange_frame_id\&.parser\fP"
.br
.ti -1c
.RI "\fBchange_frame_id\&.metavar\fP"
.br
.ti -1c
.RI "\fBchange_frame_id\&.required\fP"
.br
.ti -1c
.RI "\fBchange_frame_id\&.True\fP"
.br
.ti -1c
.RI "\fBchange_frame_id\&.help\fP"
.br
.ti -1c
.RI "\fBchange_frame_id\&.nargs\fP"
.br
.ti -1c
.RI "\fBchange_frame_id\&.args\fP = parser\&.parse_args()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
