.TH "ClipperLib::OutPt" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClipperLib::OutPt \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBIdx\fP"
.br
.ti -1c
.RI "\fBIntPoint\fP \fBPt\fP"
.br
.ti -1c
.RI "\fBOutPt\fP * \fBNext\fP"
.br
.ti -1c
.RI "\fBOutPt\fP * \fBPrev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 120 of file clipper\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int ClipperLib::OutPt::Idx"

.PP
Definition at line 122 of file clipper\&.cpp\&.
.SS "\fBOutPt\fP* ClipperLib::OutPt::Next"

.PP
Definition at line 124 of file clipper\&.cpp\&.
.SS "\fBOutPt\fP* ClipperLib::OutPt::Prev"

.PP
Definition at line 125 of file clipper\&.cpp\&.
.SS "\fBIntPoint\fP ClipperLib::OutPt::Pt"

.PP
Definition at line 123 of file clipper\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
