.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/log_tools/scripts/autologger/common.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/log_tools/scripts/autologger/common.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcommon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcommon\&.genhash\fP (path)"
.br
.ti -1c
.RI "def \fBcommon\&.chkhash\fP (hsh, path)"
.br
.ti -1c
.RI "def \fBcommon\&.normpath\fP (path)"
.br
.ti -1c
.RI "def \fBcommon\&.execmd\fP (cmd, blocking=True)"
.br
.ti -1c
.RI "def \fBcommon\&.gendir\fP (path)"
.br
.ti -1c
.RI "def \fBcommon\&.getutime\fP ()"
.br
.ti -1c
.RI "def \fBcommon\&.getdate\fP (ns=False)"
.br
.ti -1c
.RI "def \fBcommon\&.genlogger\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcommon\&.HOME_PATH\fP = os\&.path\&.expanduser('~/autologger')"
.br
.ti -1c
.RI "string \fBcommon\&.LOG_PATH\fP = '{}/log'"
.br
.ti -1c
.RI "string \fBcommon\&.TMP_PATH\fP = '{}/tmp'"
.br
.ti -1c
.RI "string \fBcommon\&.BAG_PATH\fP = '{}/bag'"
.br
.ti -1c
.RI "string \fBcommon\&.BAG_PREFIX\fP = 'autologger'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
