.TH "CommandData" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlinear_x\fP"
.br
.ti -1c
.RI "double \fBangular_z\fP"
.br
.ti -1c
.RI "int \fBmodeValue\fP"
.br
.ti -1c
.RI "int \fBgearValue\fP"
.br
.ti -1c
.RI "int \fBlampValue\fP"
.br
.ti -1c
.RI "int \fBaccellValue\fP"
.br
.ti -1c
.RI "int \fBbrakeValue\fP"
.br
.ti -1c
.RI "int \fBsteerValue\fP"
.br
.ti -1c
.RI "double \fBlinear_velocity\fP"
.br
.ti -1c
.RI "double \fBsteering_angle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file vehicle_sender\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CommandData::reset ()"

.PP
Definition at line 45 of file vehicle_sender\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int CommandData::accellValue"

.PP
Definition at line 36 of file vehicle_sender\&.cpp\&.
.SS "double CommandData::angular_z"

.PP
Definition at line 32 of file vehicle_sender\&.cpp\&.
.SS "int CommandData::brakeValue"

.PP
Definition at line 37 of file vehicle_sender\&.cpp\&.
.SS "int CommandData::gearValue"

.PP
Definition at line 34 of file vehicle_sender\&.cpp\&.
.SS "int CommandData::lampValue"

.PP
Definition at line 35 of file vehicle_sender\&.cpp\&.
.SS "double CommandData::linear_velocity"

.PP
Definition at line 39 of file vehicle_sender\&.cpp\&.
.SS "double CommandData::linear_x"

.PP
Definition at line 31 of file vehicle_sender\&.cpp\&.
.SS "int CommandData::modeValue"

.PP
Definition at line 33 of file vehicle_sender\&.cpp\&.
.SS "double CommandData::steering_angle"

.PP
Definition at line 40 of file vehicle_sender\&.cpp\&.
.SS "int CommandData::steerValue"

.PP
Definition at line 38 of file vehicle_sender\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
