.TH "/home/deng/Project/autobot-feature-decision/ros/src/system/autoware_health_checker/include/autoware_health_checker/constants.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/system/autoware_health_checker/include/autoware_health_checker/constants.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <autoware_system_msgs/DiagnosticStatus\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBautoware_health_checker\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::LEVEL_UNDEFINED\fP"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::LEVEL_OK\fP = autoware_system_msgs::DiagnosticStatus::OK"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::LEVEL_WARN\fP = autoware_system_msgs::DiagnosticStatus::WARN"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::LEVEL_ERROR\fP = autoware_system_msgs::DiagnosticStatus::ERROR"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::LEVEL_FATAL\fP = autoware_system_msgs::DiagnosticStatus::FATAL"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::TYPE_UNDEFINED\fP"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::TYPE_OUT_OF_RANGE\fP"
.br
.ti -1c
.RI "constexpr uint8_t \fBautoware_health_checker::TYPE_RATE_IS_SLOW\fP"
.br
.ti -1c
.RI "constexpr double \fBautoware_health_checker::BUFFER_LENGTH\fP = 5\&.0"
.br
.ti -1c
.RI "constexpr double \fBautoware_health_checker::UPDATE_RATE\fP = 10\&.0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
