.TH "ContourTrackerNS" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContourTrackerNS \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContourTracker\fP"
.br
.ti -1c
.RI "class \fBCostRecordSet\fP"
.br
.ti -1c
.RI "class \fBInterestCircle\fP"
.br
.ti -1c
.RI "struct \fBKalman1dState\fP"
.br
.ti -1c
.RI "class \fBkalmanFilter1D\fP"
.br
.ti -1c
.RI "class \fBKFTrackV\fP"
.br
.ti -1c
.RI "class \fBPerceptionParams\fP"
.br
.ti -1c
.RI "class \fBPolygonGenerator\fP"
.br
.ti -1c
.RI "class \fBQuarterView\fP"
.br
.ti -1c
.RI "class \fBSimpleTracker\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTRACKING_TYPE\fP { \fBASSOCIATE_ONLY\fP = 0, \fBSIMPLE_TRACKER\fP = 1, \fBCONTOUR_TRACKER\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBContourTrackerNS::TRACKING_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIASSOCIATE_ONLY \fP\fP
.TP
\fB\fISIMPLE_TRACKER \fP\fP
.TP
\fB\fICONTOUR_TRACKER \fP\fP
.PP
Definition at line 39 of file SimpleTracker\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
