.TH "ContourTrackerNS::QuarterView" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContourTrackerNS::QuarterView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PolygonGenerator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuarterView\fP (const int &min_a, const int &max_a, const int &index)"
.br
.ti -1c
.RI "void \fBInitQuarterView\fP (const int &min_a, const int &max_a, const int &index)"
.br
.ti -1c
.RI "void \fBResetQuarterView\fP ()"
.br
.ti -1c
.RI "bool \fBUpdateQuarterView\fP (const \fBPlannerHNS::WayPoint\fP &v)"
.br
.ti -1c
.RI "bool \fBGetMaxPoint\fP (\fBPlannerHNS::WayPoint\fP &maxPoint)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBmin_ang\fP"
.br
.ti -1c
.RI "int \fBmax_ang\fP"
.br
.ti -1c
.RI "\fBPlannerHNS::WayPoint\fP \fBmax_from_center\fP"
.br
.ti -1c
.RI "bool \fBbFirst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file PolygonGenerator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContourTrackerNS::QuarterView::QuarterView (const int & min_a, const int & max_a, const int & index)\fC [inline]\fP"

.PP
Definition at line 40 of file PolygonGenerator\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ContourTrackerNS::QuarterView::GetMaxPoint (\fBPlannerHNS::WayPoint\fP & maxPoint)\fC [inline]\fP"

.PP
Definition at line 77 of file PolygonGenerator\&.h\&.
.SS "void ContourTrackerNS::QuarterView::InitQuarterView (const int & min_a, const int & max_a, const int & index)\fC [inline]\fP"

.PP
Definition at line 48 of file PolygonGenerator\&.h\&.
.SS "void ContourTrackerNS::QuarterView::ResetQuarterView ()\fC [inline]\fP"

.PP
Definition at line 56 of file PolygonGenerator\&.h\&.
.SS "bool ContourTrackerNS::QuarterView::UpdateQuarterView (const \fBPlannerHNS::WayPoint\fP & v)\fC [inline]\fP"

.PP
Definition at line 61 of file PolygonGenerator\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ContourTrackerNS::QuarterView::bFirst"

.PP
Definition at line 38 of file PolygonGenerator\&.h\&.
.SS "int ContourTrackerNS::QuarterView::id"

.PP
Definition at line 34 of file PolygonGenerator\&.h\&.
.SS "int ContourTrackerNS::QuarterView::max_ang"

.PP
Definition at line 36 of file PolygonGenerator\&.h\&.
.SS "\fBPlannerHNS::WayPoint\fP ContourTrackerNS::QuarterView::max_from_center"

.PP
Definition at line 37 of file PolygonGenerator\&.h\&.
.SS "int ContourTrackerNS::QuarterView::min_ang"

.PP
Definition at line 35 of file PolygonGenerator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
