.TH "ContourTrackerNS::kalmanFilter1D" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContourTrackerNS::kalmanFilter1D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleTracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBkalmanFilter1D\fP ()"
.br
.ti -1c
.RI "\fBkalmanFilter1D\fP (double MovCov, double MeasureCov, double \fBp\fP, double intial_value)"
.br
.ti -1c
.RI "\fBKalman1dState\fP \fBUpdate\fP (double measurement)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKalman1dState\fP \fBresult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file SimpleTracker\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContourTrackerNS::kalmanFilter1D::kalmanFilter1D ()\fC [inline]\fP"

.PP
Definition at line 56 of file SimpleTracker\&.h\&.
.SS "ContourTrackerNS::kalmanFilter1D::kalmanFilter1D (double MovCov, double MeasureCov, double p, double intial_value)\fC [inline]\fP"

.PP
Definition at line 60 of file SimpleTracker\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBKalman1dState\fP ContourTrackerNS::kalmanFilter1D::Update (double measurement)\fC [inline]\fP"

.PP
Definition at line 68 of file SimpleTracker\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKalman1dState\fP ContourTrackerNS::kalmanFilter1D::result"

.PP
Definition at line 54 of file SimpleTracker\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
