.TH "ContourTrackerNS::InterestCircle" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContourTrackerNS::InterestCircle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleTracker\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterestCircle\fP (int _id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "double \fBradius\fP"
.br
.ti -1c
.RI "double \fBforget_time\fP"
.br
.ti -1c
.RI "std::vector< \fBKFTrackV\fP * > \fBpTrackers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 343 of file SimpleTracker\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ContourTrackerNS::InterestCircle::InterestCircle (int _id)\fC [inline]\fP"

.PP
Definition at line 351 of file SimpleTracker\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double ContourTrackerNS::InterestCircle::forget_time"

.PP
Definition at line 348 of file SimpleTracker\&.h\&.
.SS "int ContourTrackerNS::InterestCircle::id"

.PP
Definition at line 346 of file SimpleTracker\&.h\&.
.SS "std::vector<\fBKFTrackV\fP*> ContourTrackerNS::InterestCircle::pTrackers"

.PP
Definition at line 349 of file SimpleTracker\&.h\&.
.SS "double ContourTrackerNS::InterestCircle::radius"

.PP
Definition at line 347 of file SimpleTracker\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
