.TH "create_h5file" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
create_h5file \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcreate_h5file\fP (\fBfilename\fP, keys, \fBdata\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBfilename\fP = 'output\&.h5'"
.br
.ti -1c
.RI "string \fBinput_file\fP = 'hogehoge\&.bag'"
.br
.ti -1c
.RI "\fBh5file\fP = h5py\&.File(output_file,'w')"
.br
.ti -1c
.RI "string \fBdir\fP = 'frequency_'"
.br
.ti -1c
.RI "\fBdata\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def create_h5file\&.create_h5file ( filename,  keys,  data)"

.PP
Definition at line 4 of file create_h5file\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "create_h5file\&.data"

.PP
Definition at line 15 of file create_h5file\&.py\&.
.SS "string create_h5file\&.dir = 'frequency_'"

.PP
Definition at line 13 of file create_h5file\&.py\&.
.SS "string create_h5file\&.filename = 'output\&.h5'"

.PP
Definition at line 8 of file create_h5file\&.py\&.
.SS "create_h5file\&.h5file = h5py\&.File(output_file,'w')"

.PP
Definition at line 11 of file create_h5file\&.py\&.
.SS "string create_h5file\&.input_file = 'hogehoge\&.bag'"

.PP
Definition at line 9 of file create_h5file\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
