.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/data_preprocessor/scripts/create_h5file.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/data_preprocessor/scripts/create_h5file.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcreate_h5file\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcreate_h5file\&.create_h5file\fP (filename, keys, \fBdata\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBcreate_h5file\&.filename\fP = 'output\&.h5'"
.br
.ti -1c
.RI "string \fBcreate_h5file\&.input_file\fP = 'hogehoge\&.bag'"
.br
.ti -1c
.RI "\fBcreate_h5file\&.h5file\fP = h5py\&.File(output_file,'w')"
.br
.ti -1c
.RI "string \fBcreate_h5file\&.dir\fP = 'frequency_'"
.br
.ti -1c
.RI "\fBcreate_h5file\&.data\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
