.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/src/crnn_layer.c" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/src/crnn_layer.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'crnn_layer\&.h'\fP
.br
\fC#include 'convolutional_layer\&.h'\fP
.br
\fC#include 'utils\&.h'\fP
.br
\fC#include 'cuda\&.h'\fP
.br
\fC#include 'blas\&.h'\fP
.br
\fC#include 'gemm\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlayer\fP \fBmake_crnn_layer\fP (int batch, int h, int w, int \fBc\fP, int hidden_filters, int output_filters, int steps, \fBACTIVATION\fP activation, int batch_normalize)"
.br
.ti -1c
.RI "void \fBupdate_crnn_layer\fP (\fBlayer\fP l, \fBupdate_args\fP a)"
.br
.ti -1c
.RI "void \fBforward_crnn_layer\fP (\fBlayer\fP l, \fBnetwork\fP net)"
.br
.ti -1c
.RI "void \fBbackward_crnn_layer\fP (\fBlayer\fP l, \fBnetwork\fP net)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void backward_crnn_layer (\fBlayer\fP l, \fBnetwork\fP net)"

.PP
Definition at line 132 of file crnn_layer\&.c\&.
.SS "void forward_crnn_layer (\fBlayer\fP l, \fBnetwork\fP net)"

.PP
Definition at line 91 of file crnn_layer\&.c\&.
.SS "\fBlayer\fP make_crnn_layer (int batch, int h, int w, int c, int hidden_filters, int output_filters, int steps, \fBACTIVATION\fP activation, int batch_normalize)"

.PP
Definition at line 29 of file crnn_layer\&.c\&.
.SS "void update_crnn_layer (\fBlayer\fP l, \fBupdate_args\fP a)"

.PP
Definition at line 84 of file crnn_layer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
