.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/decision/packages/decision_maker/nodes/decision_maker/cross_road_area.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/decision/packages/decision_maker/nodes/decision_maker/cross_road_area.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <amathutils_lib/amathutils\&.hpp>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cross_road_area\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdecision_maker\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTARGET_WAYPOINTS_NUM\fP   15"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< \fBgeometry_msgs::Point\fP > \fBdecision_maker::convhull\fP (const CrossRoadArea *_TargetArea)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TARGET_WAYPOINTS_NUM   15"

.PP
Definition at line 7 of file cross_road_area\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
