.TH "data" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <darknet\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "\fBmatrix\fP \fBX\fP"
.br
.ti -1c
.RI "\fBmatrix\fP \fBy\fP"
.br
.ti -1c
.RI "int \fBshallow\fP"
.br
.ti -1c
.RI "int * \fBnum_boxes\fP"
.br
.ti -1c
.RI "\fBbox\fP ** \fBboxes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 533 of file darknet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBbox\fP** data::boxes"

.PP
Definition at line 539 of file darknet\&.h\&.
.SS "int data::h"

.PP
Definition at line 534 of file darknet\&.h\&.
.SS "int* data::num_boxes"

.PP
Definition at line 538 of file darknet\&.h\&.
.SS "int data::shallow"

.PP
Definition at line 537 of file darknet\&.h\&.
.SS "int data::w"

.PP
Definition at line 534 of file darknet\&.h\&.
.SS "\fBmatrix\fP data::X"

.PP
Definition at line 535 of file darknet\&.h\&.
.SS "\fBmatrix\fP data::y"

.PP
Definition at line 536 of file darknet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
