.TH "data_preprocessor.StrValObj" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_preprocessor.StrValObj \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBs\fP, \fBv\fP)"
.br
.ti -1c
.RI "def \fBGetValue\fP (self)"
.br
.ti -1c
.RI "def \fBSetValue\fP (self, \fBv\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs\fP"
.br
.ti -1c
.RI "\fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3069 of file data_preprocessor\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def data_preprocessor\&.StrValObj\&.__init__ ( self,  s,  v)"

.PP
Definition at line 3070 of file data_preprocessor\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def data_preprocessor\&.StrValObj\&.GetValue ( self)"

.PP
Definition at line 3073 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.StrValObj\&.SetValue ( self,  v)"

.PP
Definition at line 3075 of file data_preprocessor\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "data_preprocessor\&.StrValObj\&.s"

.PP
Definition at line 3071 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.StrValObj\&.v"

.PP
Definition at line 3072 of file data_preprocessor\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
