.TH "datatypes::FieldRectangle" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes::FieldRectangle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Fields\&.hpp>\fP
.PP
Inherits \fBdatatypes::FieldDescription\fP\&.
.PP
Inherited by \fBdatatypes::FieldDynamic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldRectangle\fP ()"
.br
.ti -1c
.RI "virtual \fB~FieldRectangle\fP ()"
.br
.ti -1c
.RI "virtual const \fBUINT32\fP \fBgetUsedMemory\fP () const "
.br
.ti -1c
.RI "void \fBcomputePolygon\fP ()"
.br
.RI "\fIfills the polygon clockwise \fP"
.ti -1c
.RI "double \fBgetLength\fP () const "
.br
.ti -1c
.RI "double \fBgetRefPointAngle\fP () const "
.br
.ti -1c
.RI "double \fBgetRefPointDist\fP () const "
.br
.ti -1c
.RI "double \fBgetRotAngle\fP () const "
.br
.ti -1c
.RI "double \fBgetWidth\fP () const "
.br
.ti -1c
.RI "void \fBsetLength\fP (double length)"
.br
.ti -1c
.RI "void \fBsetRefPointAngle\fP (double refPointAngle)"
.br
.ti -1c
.RI "void \fBsetRefPointDist\fP (double refPointDist)"
.br
.ti -1c
.RI "void \fBsetRotAngle\fP (double rotAngle)"
.br
.ti -1c
.RI "void \fBsetWidth\fP (double width)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 130 of file Fields\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "datatypes::FieldRectangle::FieldRectangle ()\fC [inline]\fP"

.PP
Definition at line 133 of file Fields\&.hpp\&.
.SS "virtual datatypes::FieldRectangle::~FieldRectangle ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 138 of file Fields\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void datatypes::FieldRectangle::computePolygon ()\fC [virtual]\fP"

.PP
fills the polygon clockwise 
.PP
Implements \fBdatatypes::FieldDescription\fP\&.
.PP
Definition at line 82 of file Fields\&.cpp\&.
.SS "double datatypes::FieldRectangle::getLength () const"

.PP
Definition at line 98 of file Fields\&.cpp\&.
.SS "double datatypes::FieldRectangle::getRefPointAngle () const"

.PP
Definition at line 103 of file Fields\&.cpp\&.
.SS "double datatypes::FieldRectangle::getRefPointDist () const"

.PP
Definition at line 108 of file Fields\&.cpp\&.
.SS "double datatypes::FieldRectangle::getRotAngle () const"

.PP
Definition at line 113 of file Fields\&.cpp\&.
.SS "virtual const \fBUINT32\fP datatypes::FieldRectangle::getUsedMemory () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBdatatypes::BasicData\fP\&.
.PP
Reimplemented in \fBdatatypes::FieldDynamic\fP\&.
.PP
Definition at line 142 of file Fields\&.hpp\&.
.SS "double datatypes::FieldRectangle::getWidth () const"

.PP
Definition at line 118 of file Fields\&.cpp\&.
.SS "void datatypes::FieldRectangle::setLength (double length)"

.PP
Definition at line 126 of file Fields\&.cpp\&.
.SS "void datatypes::FieldRectangle::setRefPointAngle (double refPointAngle)"

.PP
Definition at line 138 of file Fields\&.cpp\&.
.SS "void datatypes::FieldRectangle::setRefPointDist (double refPointDist)"

.PP
Definition at line 143 of file Fields\&.cpp\&.
.SS "void datatypes::FieldRectangle::setRotAngle (double rotAngle)"

.PP
Definition at line 152 of file Fields\&.cpp\&.
.SS "void datatypes::FieldRectangle::setWidth (double width)"

.PP
Definition at line 163 of file Fields\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
