.TH "data_preprocessor.VarPanel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_preprocessor.VarPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Panel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, args, kwds)"
.br
.ti -1c
.RI "def \fBsetup_tooltip\fP (self)"
.br
.ti -1c
.RI "def \fBcreate_bmbtn\fP (self, filename, hdr)"
.br
.ti -1c
.RI "def \fBget_v\fP (self)"
.br
.ti -1c
.RI "def \fBget_tc_v\fP (self)"
.br
.ti -1c
.RI "def \fBget_int_v\fP (self)"
.br
.ti -1c
.RI "def \fBOnScroll\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnIncBtn\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnDecBtn\fP (self, event)"
.br
.ti -1c
.RI "def \fBget_step\fP (self)"
.br
.ti -1c
.RI "def \fBadd_v\fP (self, step)"
.br
.ti -1c
.RI "def \fBOnUpdate\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnRef\fP (self, event)"
.br
.ti -1c
.RI "def \fBchoices_sel_get\fP (self)"
.br
.ti -1c
.RI "def \fBchoices_sel_set\fP (self, v)"
.br
.ti -1c
.RI "def \fBis_nl\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvar\fP"
.br
.ti -1c
.RI "\fBupdate\fP"
.br
.ti -1c
.RI "\fBmin\fP"
.br
.ti -1c
.RI "\fBmax\fP"
.br
.ti -1c
.RI "\fBhas_slider\fP"
.br
.ti -1c
.RI "\fBlb\fP"
.br
.ti -1c
.RI "\fBkind\fP"
.br
.ti -1c
.RI "\fBobj\fP"
.br
.ti -1c
.RI "\fBtc\fP"
.br
.ti -1c
.RI "\fBw\fP"
.br
.ti -1c
.RI "\fBis_float\fP"
.br
.ti -1c
.RI "\fBint_max\fP"
.br
.ti -1c
.RI "\fBint_min\fP"
.br
.ti -1c
.RI "\fBslider\fP"
.br
.ti -1c
.RI "\fBref\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2579 of file data_preprocessor\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def data_preprocessor\&.VarPanel\&.__init__ ( self,  args,  kwds)"

.PP
Definition at line 2580 of file data_preprocessor\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def data_preprocessor\&.VarPanel\&.add_v ( self,  step)"

.PP
Definition at line 2750 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.choices_sel_get ( self)"

.PP
Definition at line 2768 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.choices_sel_set ( self,  v)"

.PP
Definition at line 2771 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.create_bmbtn ( self,  filename,  hdr)"

.PP
Definition at line 2690 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.get_int_v ( self)"

.PP
Definition at line 2723 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.get_step ( self)"

.PP
Definition at line 2746 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.get_tc_v ( self)"

.PP
Definition at line 2714 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.get_v ( self)"

.PP
Definition at line 2698 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.is_nl ( self)"

.PP
Definition at line 2777 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.OnDecBtn ( self,  event)"

.PP
Definition at line 2742 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.OnIncBtn ( self,  event)"

.PP
Definition at line 2738 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.OnRef ( self,  event)"

.PP
Definition at line 2764 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.OnScroll ( self,  event)"

.PP
Definition at line 2729 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.OnUpdate ( self,  event)"

.PP
Definition at line 2759 of file data_preprocessor\&.py\&.
.SS "def data_preprocessor\&.VarPanel\&.setup_tooltip ( self)"

.PP
Definition at line 2683 of file data_preprocessor\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "data_preprocessor\&.VarPanel\&.has_slider"

.PP
Definition at line 2588 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.int_max"

.PP
Definition at line 2653 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.int_min"

.PP
Definition at line 2654 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.is_float"

.PP
Definition at line 2652 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.kind"

.PP
Definition at line 2592 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.lb"

.PP
Definition at line 2589 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.max"

.PP
Definition at line 2587 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.min"

.PP
Definition at line 2586 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.obj"

.PP
Definition at line 2596 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.ref"

.PP
Definition at line 2669 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.slider"

.PP
Definition at line 2656 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.tc"

.PP
Definition at line 2645 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.update"

.PP
Definition at line 2583 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.var"

.PP
Definition at line 2581 of file data_preprocessor\&.py\&.
.SS "data_preprocessor\&.VarPanel\&.w"

.PP
Definition at line 2650 of file data_preprocessor\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
