.TH "datatypes::FieldDynamic" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes::FieldDynamic \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Fields\&.hpp>\fP
.PP
Inherits \fBdatatypes::FieldRectangle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldDynamic\fP ()"
.br
.ti -1c
.RI "virtual \fB~FieldDynamic\fP ()"
.br
.ti -1c
.RI "virtual const \fBUINT32\fP \fBgetUsedMemory\fP () const "
.br
.ti -1c
.RI "double \fBgetMaxLength\fP () const "
.br
.ti -1c
.RI "double \fBgetSpeedMax\fP () const "
.br
.ti -1c
.RI "void \fBsetMaxLength\fP (double maxLength)"
.br
.ti -1c
.RI "void \fBsetSpeedMax\fP (double speedMax)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 214 of file Fields\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "datatypes::FieldDynamic::FieldDynamic ()\fC [inline]\fP"

.PP
Definition at line 217 of file Fields\&.hpp\&.
.SS "virtual datatypes::FieldDynamic::~FieldDynamic ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 222 of file Fields\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double datatypes::FieldDynamic::getMaxLength () const"

.PP
Definition at line 230 of file Fields\&.cpp\&.
.SS "double datatypes::FieldDynamic::getSpeedMax () const"

.PP
Definition at line 235 of file Fields\&.cpp\&.
.SS "virtual const \fBUINT32\fP datatypes::FieldDynamic::getUsedMemory () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBdatatypes::FieldRectangle\fP\&.
.PP
Definition at line 226 of file Fields\&.hpp\&.
.SS "void datatypes::FieldDynamic::setMaxLength (double maxLength)"

.PP
Definition at line 240 of file Fields\&.cpp\&.
.SS "void datatypes::FieldDynamic::setSpeedMax (double speedMax)"

.PP
Definition at line 245 of file Fields\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
