.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/decision/packages/decision_maker/include/decision_maker/decision_maker_param.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/decision/packages/decision_maker/include/decision_maker/decision_maker_param.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdecision_maker\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_DISPLAY_FLAG\fP   false"
.br
.ti -1c
.RI "#define \fBDEFAULT_FORCE_STATE_CHANGE\fP   true"
.br
.ti -1c
.RI "#define \fBVEL_AVERAGE_COUNT\fP   10"
.br
.ti -1c
.RI "#define \fBDEFAULT_CONVERGENCE_COUNT\fP   5"
.br
.ti -1c
.RI "#define \fBDEFAULT_CONVERGENCE_THRESHOLD\fP   0\&.01"
.br
.ti -1c
.RI "#define \fBDOUBLE_MAX\fP   1\&.7976931348623158e308"
.br
.ti -1c
.RI "#define \fBDEFAULT_TARGET_WAYPOINT\fP   14"
.br
.ti -1c
.RI "#define \fBDEFAULT_STOP_DECELERATION\fP   0\&.2"
.br
.ti -1c
.RI "#define \fBDEFAULT_STOP_TIME\fP   1"
.br
.ti -1c
.RI "#define \fBDEFAULT_STOPLINE_TARGET_WAYPOINT\fP   10"
.br
.ti -1c
.RI "#define \fBDEFAULT_STOPLINE_TARGET_RATIO\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_SHIFT_WIDTH\fP   1\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_CRAWL_VELOCITY\fP   4\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_DETECTION_AREA_RATE\fP   1\&.0"
.br
.ti -1c
.RI "#define \fBANGLE_NEUTRAL\fP   0"
.br
.ti -1c
.RI "#define \fBANGLE_CURVE\fP   40"
.br
.ti -1c
.RI "#define \fBANGLE_LEFT\fP   (\fBANGLE_NEUTRAL\fP \- \fBANGLE_CURVE\fP)"
.br
.ti -1c
.RI "#define \fBANGLE_RIGHT\fP   (\fBANGLE_NEUTRAL\fP + \fBANGLE_CURVE\fP)"
.br
.ti -1c
.RI "#define \fBTPNAME_BASED_LANE_WAYPOINTS_ARRAY\fP   '/based/lane_waypoints_array'"
.br
.ti -1c
.RI "#define \fBTPNAME_CONTROL_LANE_WAYPOINTS_ARRAY\fP   '/lane_waypoints_array'"
.br
.ti -1c
.RI "#define \fBLAMP_ON\fP   1"
.br
.ti -1c
.RI "#define \fBLAMP_OFF\fP   0"
.br
.ti -1c
.RI "#define \fBDEFAULT_DETECTION_AREA_X1\fP   80\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_DETECTION_AREA_X2\fP   0\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_DETECTION_AREA_Y1\fP   50\&.0"
.br
.ti -1c
.RI "#define \fBDEFAULT_DETECTION_AREA_Y2\fP   \-50\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANGLE_CURVE   40"

.PP
Definition at line 27 of file decision_maker_param\&.hpp\&.
.SS "#define ANGLE_LEFT   (\fBANGLE_NEUTRAL\fP \- \fBANGLE_CURVE\fP)"

.PP
Definition at line 28 of file decision_maker_param\&.hpp\&.
.SS "#define ANGLE_NEUTRAL   0"

.PP
Definition at line 26 of file decision_maker_param\&.hpp\&.
.SS "#define ANGLE_RIGHT   (\fBANGLE_NEUTRAL\fP + \fBANGLE_CURVE\fP)"

.PP
Definition at line 29 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_CONVERGENCE_COUNT   5"

.PP
Definition at line 12 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_CONVERGENCE_THRESHOLD   0\&.01"

.PP
Definition at line 13 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_CRAWL_VELOCITY   4\&.0"

.PP
Definition at line 23 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_DETECTION_AREA_RATE   1\&.0"

.PP
Definition at line 24 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_DETECTION_AREA_X1   80\&.0"

.PP
Definition at line 36 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_DETECTION_AREA_X2   0\&.0"

.PP
Definition at line 37 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_DETECTION_AREA_Y1   50\&.0"

.PP
Definition at line 38 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_DETECTION_AREA_Y2   \-50\&.0"

.PP
Definition at line 39 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_DISPLAY_FLAG   false"

.PP
Definition at line 8 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_FORCE_STATE_CHANGE   true"

.PP
Definition at line 9 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_SHIFT_WIDTH   1\&.0"

.PP
Definition at line 22 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_STOP_DECELERATION   0\&.2"

.PP
Definition at line 18 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_STOP_TIME   1"

.PP
Definition at line 19 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_STOPLINE_TARGET_RATIO   0\&.0"

.PP
Definition at line 21 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_STOPLINE_TARGET_WAYPOINT   10"

.PP
Definition at line 20 of file decision_maker_param\&.hpp\&.
.SS "#define DEFAULT_TARGET_WAYPOINT   14"

.PP
Definition at line 16 of file decision_maker_param\&.hpp\&.
.SS "#define DOUBLE_MAX   1\&.7976931348623158e308"

.PP
Definition at line 15 of file decision_maker_param\&.hpp\&.
.SS "#define LAMP_OFF   0"

.PP
Definition at line 34 of file decision_maker_param\&.hpp\&.
.SS "#define LAMP_ON   1"

.PP
Definition at line 33 of file decision_maker_param\&.hpp\&.
.SS "#define TPNAME_BASED_LANE_WAYPOINTS_ARRAY   '/based/lane_waypoints_array'"

.PP
Definition at line 31 of file decision_maker_param\&.hpp\&.
.SS "#define TPNAME_CONTROL_LANE_WAYPOINTS_ARRAY   '/lane_waypoints_array'"

.PP
Definition at line 32 of file decision_maker_param\&.hpp\&.
.SS "#define VEL_AVERAGE_COUNT   10"

.PP
Definition at line 11 of file decision_maker_param\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
