.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/DecisionMaker.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/DecisionMaker.h \- Initialize behaviors state machine, and calculate required parameters for the state machine transition conditions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'op_planner/BehaviorStateMachine\&.h'\fP
.br
\fC#include 'op_planner/PlannerCommonDef\&.h'\fP
.br
\fC#include 'op_planner/RoadNetwork\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerHNS::DecisionMaker\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlannerHNS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initialize behaviors state machine, and calculate required parameters for the state machine transition conditions\&. 


.PP
\fBAuthor:\fP
.RS 4
Hatem Darweesh 
.RE
.PP
\fBDate:\fP
.RS 4
Dec 14, 2016 
.RE
.PP

.PP
Definition in file \fBDecisionMaker\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
