.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/src/detection_layer.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/packages/vision_darknet_detect/darknet/src/detection_layer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'layer\&.h'\fP
.br
\fC#include 'network\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBlayer\fP \fBdetection_layer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdetection_layer\fP \fBmake_detection_layer\fP (int batch, int inputs, int n, int size, int classes, int coords, int rescore)"
.br
.ti -1c
.RI "void \fBforward_detection_layer\fP (const \fBdetection_layer\fP l, \fBnetwork\fP net)"
.br
.ti -1c
.RI "void \fBbackward_detection_layer\fP (const \fBdetection_layer\fP l, \fBnetwork\fP net)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBlayer\fP \fBdetection_layer\fP"

.PP
Definition at line 7 of file detection_layer\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void backward_detection_layer (const \fBdetection_layer\fP l, \fBnetwork\fP net)"

.PP
Definition at line 220 of file detection_layer\&.c\&.
.SS "void forward_detection_layer (const \fBdetection_layer\fP l, \fBnetwork\fP net)"

.PP
Definition at line 50 of file detection_layer\&.c\&.
.SS "\fBdetection_layer\fP make_detection_layer (int batch, int inputs, int n, int size, int classes, int coords, int rescore)"

.PP
Definition at line 14 of file detection_layer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
