.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_tracker/packages/vision_beyond_track/include/detection.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_tracker/packages/vision_beyond_track/include/detection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include 'opencv2/highgui/highgui\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc/imgproc\&.hpp'\fP
.br
\fC#include 'clipper\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbeyondtrack::ObjectCuboid_\fP"
.br
.ti -1c
.RI "class \fBbeyondtrack::Detection\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbeyondtrack\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdeg2rad\fP(a)   ((a)/180\&.0 * M_PI)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBbeyondtrack::ObjectCuboid_\fP \fBbeyondtrack::ObjectCuboid\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define deg2rad(a)   ((a)/180\&.0 * M_PI)"

.PP
Definition at line 49 of file detection\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
