.TH "DPMTTICParam" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DPMTTICParam \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dpm_ttic\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDPMTTICParam\fP ()=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBthreshold\fP"
.br
.ti -1c
.RI "double \fBoverlap\fP"
.br
.ti -1c
.RI "double \fBlambda\fP"
.br
.ti -1c
.RI "double \fBnum_cells\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file dpm_ttic\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DPMTTICParam::DPMTTICParam ()\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double DPMTTICParam::lambda"

.PP
Definition at line 21 of file dpm_ttic\&.hpp\&.
.SS "double DPMTTICParam::num_cells"

.PP
Definition at line 22 of file dpm_ttic\&.hpp\&.
.SS "double DPMTTICParam::overlap"

.PP
Definition at line 20 of file dpm_ttic\&.hpp\&.
.SS "double DPMTTICParam::threshold"

.PP
Definition at line 19 of file dpm_ttic\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
