.TH "DPMTTICResult" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DPMTTICResult \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dpm_ttic\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "std::vector< int > \fBcorner_points\fP"
.br
.ti -1c
.RI "std::vector< int > \fBtype\fP"
.br
.ti -1c
.RI "std::vector< float > \fBscore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file dpm_ttic\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<int> DPMTTICResult::corner_points"

.PP
Definition at line 13 of file dpm_ttic\&.hpp\&.
.SS "int DPMTTICResult::num"

.PP
Definition at line 12 of file dpm_ttic\&.hpp\&.
.SS "std::vector<float> DPMTTICResult::score"

.PP
Definition at line 15 of file dpm_ttic\&.hpp\&.
.SS "std::vector<int> DPMTTICResult::type"

.PP
Definition at line 14 of file dpm_ttic\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
