.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/visualizers/packages/integrated_viewer/node/image_viewer_plugin/draw_rects.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/visualizers/packages/integrated_viewer/node/image_viewer_plugin/draw_rects.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv/cv\&.h>\fP
.br
\fC#include <autoware_msgs/DetectedObjectArray\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintegrated_viewer::DrawRects\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBintegrated_viewer\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBXSTR\fP(x)   #x"
.br
.ti -1c
.RI "#define \fBSTR\fP(x)   \fBXSTR\fP(x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBDEFAULT_PATH\fP = \fBSTR\fP(IMAGE_VIEWER_DEFAULT_PATH)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STR(x)   \fBXSTR\fP(x)"

.PP
Definition at line 8 of file draw_rects\&.h\&.
.SS "#define XSTR(x)   #x"

.PP
Definition at line 7 of file draw_rects\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const std::string DEFAULT_PATH = \fBSTR\fP(IMAGE_VIEWER_DEFAULT_PATH)"

.PP
Definition at line 10 of file draw_rects\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
