.TH "DriveWorks::ImageConfig" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DriveWorks::ImageConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DriveWorksApi\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBpub_width\fP"
.br
.ti -1c
.RI "uint32_t \fBpub_height\fP"
.br
.ti -1c
.RI "uint32_t \fBpub_buffer\fP"
.br
.ti -1c
.RI "bool \fBpub_compressed\fP"
.br
.ti -1c
.RI "uint32_t \fBpub_compressed_quality\fP"
.br
.ti -1c
.RI "std::string \fBpub_caminfo_folder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 103 of file DriveWorksApi\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t DriveWorks::ImageConfig::pub_buffer"

.PP
Definition at line 106 of file DriveWorksApi\&.hpp\&.
.SS "std::string DriveWorks::ImageConfig::pub_caminfo_folder"

.PP
Definition at line 109 of file DriveWorksApi\&.hpp\&.
.SS "bool DriveWorks::ImageConfig::pub_compressed"

.PP
Definition at line 107 of file DriveWorksApi\&.hpp\&.
.SS "uint32_t DriveWorks::ImageConfig::pub_compressed_quality"

.PP
Definition at line 108 of file DriveWorksApi\&.hpp\&.
.SS "uint32_t DriveWorks::ImageConfig::pub_height"

.PP
Definition at line 105 of file DriveWorksApi\&.hpp\&.
.SS "uint32_t DriveWorks::ImageConfig::pub_width"

.PP
Definition at line 104 of file DriveWorksApi\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
