.TH "DriveWorks::DeviceArguments" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DriveWorks::DeviceArguments \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DeviceArguments\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeviceArguments\fP (const std::vector< \fBoption_t\fP > &\fBoptions\fP)"
.br
.ti -1c
.RI "\fB~DeviceArguments\fP ()"
.br
.ti -1c
.RI "void \fBprintArguments\fP ()"
.br
.ti -1c
.RI "const std::string & \fBget\fP (const char *name) const "
.br
.ti -1c
.RI "bool \fBset\fP (const char *name, std::string new_value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file DeviceArguments\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DriveWorks::DeviceArguments::DeviceArguments (const std::vector< \fBoption_t\fP > & options)"

.PP
Definition at line 43 of file DeviceArguments\&.cpp\&.
.SS "DriveWorks::DeviceArguments::~DeviceArguments ()"

.PP
Definition at line 53 of file DeviceArguments\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const std::string & DriveWorks::DeviceArguments::get (const char * name) const"

.PP
Definition at line 67 of file DeviceArguments\&.cpp\&.
.SS "void DriveWorks::DeviceArguments::printArguments ()"

.PP
Definition at line 59 of file DeviceArguments\&.cpp\&.
.SS "bool DriveWorks::DeviceArguments::set (const char * name, std::string new_value)"

.PP
Definition at line 82 of file DeviceArguments\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
