.TH "dt_partition" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dt_partition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNoP\fP"
.br
.ti -1c
.RI "int \fBNoC\fP"
.br
.ti -1c
.RI "int \fBinterval\fP"
.br
.ti -1c
.RI "int \fBL_MAX\fP"
.br
.ti -1c
.RI "int \fBsum_size_SQ\fP"
.br
.ti -1c
.RI "int \fBmax_numpart\fP"
.br
.ti -1c
.RI "int \fBmax_dim0\fP"
.br
.ti -1c
.RI "int \fBmax_dim1\fP"
.br
.ti -1c
.RI "\fBFLOAT\fP * \fBdst_M\fP"
.br
.ti -1c
.RI "int * \fBdst_tmpIx\fP"
.br
.ti -1c
.RI "int * \fBdst_tmpIy\fP"
.br
.ti -1c
.RI "int *** \fBPIDX_array\fP"
.br
.ti -1c
.RI "int ** \fBsize_array\fP"
.br
.ti -1c
.RI "const int * \fBnumpart\fP"
.br
.ti -1c
.RI "int * \fBFSIZE\fP"
.br
.ti -1c
.RI "int \fBpadx\fP"
.br
.ti -1c
.RI "int \fBpady\fP"
.br
.ti -1c
.RI "int \fBmax_X\fP"
.br
.ti -1c
.RI "int \fBmax_Y\fP"
.br
.ti -1c
.RI "\fBFLOAT\fP * \fBdef\fP"
.br
.ti -1c
.RI "int \fBtmp_array_size\fP"
.br
.ti -1c
.RI "int * \fBdst_PIDX\fP"
.br
.ti -1c
.RI "int * \fBdst_DID_4\fP"
.br
.ti -1c
.RI "int \fBpid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file dt_GPU\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFLOAT\fP* dt_partition::def"

.PP
Definition at line 47 of file dt_GPU\&.cpp\&.
.SS "int* dt_partition::dst_DID_4"

.PP
Definition at line 50 of file dt_GPU\&.cpp\&.
.SS "\fBFLOAT\fP* dt_partition::dst_M"

.PP
Definition at line 36 of file dt_GPU\&.cpp\&.
.SS "int* dt_partition::dst_PIDX"

.PP
Definition at line 49 of file dt_GPU\&.cpp\&.
.SS "int* dt_partition::dst_tmpIx"

.PP
Definition at line 37 of file dt_GPU\&.cpp\&.
.SS "int* dt_partition::dst_tmpIy"

.PP
Definition at line 38 of file dt_GPU\&.cpp\&.
.SS "int* dt_partition::FSIZE"

.PP
Definition at line 42 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::interval"

.PP
Definition at line 30 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::L_MAX"

.PP
Definition at line 31 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::max_dim0"

.PP
Definition at line 34 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::max_dim1"

.PP
Definition at line 35 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::max_numpart"

.PP
Definition at line 33 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::max_X"

.PP
Definition at line 45 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::max_Y"

.PP
Definition at line 46 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::NoC"

.PP
Definition at line 29 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::NoP"

.PP
Definition at line 28 of file dt_GPU\&.cpp\&.
.SS "const int* dt_partition::numpart"

.PP
Definition at line 41 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::padx"

.PP
Definition at line 43 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::pady"

.PP
Definition at line 44 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::pid"

.PP
Definition at line 51 of file dt_GPU\&.cpp\&.
.SS "int*** dt_partition::PIDX_array"

.PP
Definition at line 39 of file dt_GPU\&.cpp\&.
.SS "int** dt_partition::size_array"

.PP
Definition at line 40 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::sum_size_SQ"

.PP
Definition at line 32 of file dt_GPU\&.cpp\&.
.SS "int dt_partition::tmp_array_size"

.PP
Definition at line 48 of file dt_GPU\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
