.TH "error_request" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error_request \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBerror_request\fP (const tablet_socket_msgs::error_info &msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBtype\fP"
.br
.ti -1c
.RI "int32_t \fBerror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file tablet_sender\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "error_request::error_request (const tablet_socket_msgs::error_info & msg)\fC [inline]\fP"

.PP
Definition at line 51 of file tablet_sender\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int32_t error_request::error"

.PP
Definition at line 49 of file tablet_sender\&.cpp\&.
.SS "int32_t error_request::type"

.PP
Definition at line 48 of file tablet_sender\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
