.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/RobotSDK/fastvirtualscan/FastVirtualScan/fastvirtualscan.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/RobotSDK/fastvirtualscan/FastVirtualScan/fastvirtualscan.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fastvirtualscan/fastvirtualscan\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXVIRTUALSCAN\fP   1e6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcompareDistance\fP (const \fBSimpleVirtualScan\fP &svs1, const \fBSimpleVirtualScan\fP &svs2)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXVIRTUALSCAN   1e6"

.PP
Definition at line 3 of file fastvirtualscan\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "bool compareDistance (const \fBSimpleVirtualScan\fP & svs1, const \fBSimpleVirtualScan\fP & svs2)"

.PP
Definition at line 20 of file fastvirtualscan\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
