.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/libs/dpm_ttic/gpu/fconvsMT.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/libs/dpm_ttic/gpu/fconvsMT.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'MODEL_info\&.h'\fP
.br
\fC#include 'common\&.hpp'\fP
.br
\fC#include 'multithreading\&.h'\fP
.br
\fC#include 'for_use_GPU\&.h'\fP
.br
\fC#include 'drvapi_error_string\&.h'\fP
.br
\fC#include 'switch_release\&.h'\fP
.br
\fC#include <cuda_util\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfconvs_partition\fP"
.br
.ti -1c
.RI "struct \fBthread_data\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLOAT\fP *** \fBfconvsMT_GPU\fP (\fBFLOAT\fP **featp2, size_t SUM_SIZE_feat, \fBFLOAT\fP **filter, int *sym_info, int start, int end, int *A_SIZE, int **B_SIZE, int **M_size_array, int L_MAX, int interval, int *FSIZE, int padx, int pady, int max_X, int max_Y, int calc_flag)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBpart_error_array_num\fP"
.br
.ti -1c
.RI "int * \fBpart_error_array\fP"
.br
.ti -1c
.RI "size_t \fBSUM_SIZE_C\fP"
.br
.ti -1c
.RI "\fBFLOAT\fP * \fBdst_C\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLOAT\fP*** fconvsMT_GPU (\fBFLOAT\fP ** featp2, size_t SUM_SIZE_feat, \fBFLOAT\fP ** filter, int * sym_info, int start, int end, int * A_SIZE, int ** B_SIZE, int ** M_size_array, int L_MAX, int interval, int * FSIZE, int padx, int pady, int max_X, int max_Y, int calc_flag)"

.PP
Definition at line 594 of file fconvsMT\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBFLOAT\fP* dst_C"

.PP
Definition at line 36 of file fconvsMT\&.cpp\&.
.SS "int* part_error_array"

.PP
Definition at line 34 of file fconvsMT\&.cpp\&.
.SS "int part_error_array_num"

.PP
Definition at line 33 of file fconvsMT\&.cpp\&.
.SS "size_t SUM_SIZE_C"

.PP
Definition at line 35 of file fconvsMT\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
