.TH "fconvs_partition" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fconvs_partition \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFLOAT\fP ** \fBfeatp2\fP"
.br
.ti -1c
.RI "size_t \fBSUM_SIZE_feat\fP"
.br
.ti -1c
.RI "int * \fBA_SIZE\fP"
.br
.ti -1c
.RI "size_t \fBSUM_SIZE_B\fP"
.br
.ti -1c
.RI "size_t \fBSUM_SIZE_C\fP"
.br
.ti -1c
.RI "\fBFLOAT\fP * \fBdst_C\fP"
.br
.ti -1c
.RI "\fBFLOAT\fP ** \fBfilter\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBcalc_flag\fP"
.br
.ti -1c
.RI "int \fBerror_array_num\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int * \fBerror_array\fP"
.br
.ti -1c
.RI "int * \fBB_dimension\fP"
.br
.ti -1c
.RI "int \fBinterval\fP"
.br
.ti -1c
.RI "int \fBL_MAX\fP"
.br
.ti -1c
.RI "int \fBpid\fP"
.br
.ti -1c
.RI "int \fBmax_height\fP"
.br
.ti -1c
.RI "int \fBmax_width\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file fconvsMT\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int* fconvs_partition::A_SIZE"

.PP
Definition at line 41 of file fconvsMT\&.cpp\&.
.SS "int* fconvs_partition::B_dimension"

.PP
Definition at line 51 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::calc_flag"

.PP
Definition at line 47 of file fconvsMT\&.cpp\&.
.SS "\fBFLOAT\fP* fconvs_partition::dst_C"

.PP
Definition at line 44 of file fconvsMT\&.cpp\&.
.SS "int* fconvs_partition::error_array"

.PP
Definition at line 50 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::error_array_num"

.PP
Definition at line 48 of file fconvsMT\&.cpp\&.
.SS "\fBFLOAT\fP** fconvs_partition::featp2"

.PP
Definition at line 39 of file fconvsMT\&.cpp\&.
.SS "\fBFLOAT\fP** fconvs_partition::filter"

.PP
Definition at line 45 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::interval"

.PP
Definition at line 52 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::L_MAX"

.PP
Definition at line 53 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::len"

.PP
Definition at line 46 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::max_height"

.PP
Definition at line 55 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::max_width"

.PP
Definition at line 56 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::pid"

.PP
Definition at line 54 of file fconvsMT\&.cpp\&.
.SS "int fconvs_partition::start"

.PP
Definition at line 49 of file fconvsMT\&.cpp\&.
.SS "size_t fconvs_partition::SUM_SIZE_B"

.PP
Definition at line 42 of file fconvsMT\&.cpp\&.
.SS "size_t fconvs_partition::SUM_SIZE_C"

.PP
Definition at line 43 of file fconvsMT\&.cpp\&.
.SS "size_t fconvs_partition::SUM_SIZE_feat"

.PP
Definition at line 40 of file fconvsMT\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
