.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/ff_waypoint_follower/nodes/ff_waypoint_follower_core.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/ff_waypoint_follower/nodes/ff_waypoint_follower_core.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ff_waypoint_follower_core\&.h'\fP
.br
\fC#include 'autoware_msgs/LaneArray\&.h'\fP
.br
\fC#include <visualization_msgs/MarkerArray\&.h>\fP
.br
\fC#include <visualization_msgs/InteractiveMarkerPose\&.h>\fP
.br
\fC#include <std_msgs/Bool\&.h>\fP
.br
\fC#include <std_msgs/Float32\&.h>\fP
.br
\fC#include 'op_utility/UtilityH\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFFSteerControlNS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
