.TH "FFSteerControlNS" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFSteerControlNS \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControlCommandParams\fP"
.br
.ti -1c
.RI "class \fBFFSteerControl\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSTATUS_TYPE\fP { \fBCONTROL_BOX_STATUS\fP, \fBROBOT_STATUS\fP, \fBSIMULATION_STATUS\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFFSteerControlNS::STATUS_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICONTROL_BOX_STATUS \fP\fP
.TP
\fB\fIROBOT_STATUS \fP\fP
.TP
\fB\fISIMULATION_STATUS \fP\fP
.PP
Definition at line 49 of file ff_waypoint_follower_core\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
