.TH "ftrace" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftrace \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyFrame\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmyapp\fP = wx\&.App(0)"
.br
.ti -1c
.RI "\fBframe\fP = \fBMyFrame\fP(None, \-1, 'Ftrace')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ftrace\&.frame = \fBMyFrame\fP(None, \-1, 'Ftrace')"

.PP
Definition at line 344 of file ftrace\&.py\&.
.SS "ftrace\&.myapp = wx\&.App(0)"

.PP
Definition at line 343 of file ftrace\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
