.TH "/home/deng/Project/autobot-feature-decision/ros/src/actuation/vehicles/packages/ymc/node/g30esli_interface/g30esli_interface_util.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/actuation/vehicles/packages/ymc/node/g30esli_interface/g30esli_interface_util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <termios\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBymc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBymc::reverse_byteorder_memcpy\fP (unsigned char *target, int16_t *source, size_t size)"
.br
.ti -1c
.RI "std::vector< std::string > \fBymc::splitString\fP (const std::string &s)"
.br
.ti -1c
.RI "int \fBymc::kbhit\fP ()"
.br
.ti -1c
.RI "double \fBymc::computeTargetSteeringAngleDegree\fP (double angular_z, double velocity_mps, double wheel_base)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
