.TH "get_PCD" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_PCD \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcloud_loader\fP (msg)"
.br
.ti -1c
.RI "def \fBsave_pcd\fP (cloud, timestamp, path)"
.br
.ti -1c
.RI "def \fBrosbag_data_extract_sample\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsave_path\fP = None"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def get_PCD\&.cloud_loader ( msg)"

.PP
Definition at line 14 of file get_PCD\&.py\&.
.SS "def get_PCD\&.rosbag_data_extract_sample ()"

.PP
Definition at line 22 of file get_PCD\&.py\&.
.SS "def get_PCD\&.save_pcd ( cloud,  timestamp,  path)"

.PP
Definition at line 18 of file get_PCD\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "get_PCD\&.save_path = None"

.PP
Definition at line 12 of file get_PCD\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
