.TH "/home/deng/Project/autobot-feature-decision/ros/src/data/packages/map_file/lib/map_file/get_file.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/data/packages/map_file/lib/map_file/get_file.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <ext/stdio_filebuf\&.h>\fP
.br
\fC#include <curl/curl\&.h>\fP
.br
\fC#include <map_file/get_file\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::basic_ofstream< char >::__filebuf_type \fBbuffer_t\fP"
.br
.ti -1c
.RI "typedef __gnu_cxx::stdio_filebuf< char > \fBio_buffer_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::basic_ofstream<char>::__filebuf_type \fBbuffer_t\fP"

.PP
Definition at line 41 of file get_file\&.cpp\&.
.SS "typedef __gnu_cxx::stdio_filebuf<char> \fBio_buffer_t\fP"

.PP
Definition at line 42 of file get_file\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
