.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/data_preprocessor/scripts/get_rosbaginfo.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/data_preprocessor/scripts/get_rosbaginfo.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBget_rosbaginfo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_rosbaginfo\&.get_rosbagtopics\fP (file_path)"
.br
.ti -1c
.RI "def \fBget_rosbaginfo\&.get_type_of_topics\fP (file_path)"
.br
.ti -1c
.RI "def \fBget_rosbaginfo\&.get_type_and_topic\fP (file_path)"
.br
.ti -1c
.RI "def \fBget_rosbaginfo\&.get_baginfo\fP (file_path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBget_rosbaginfo\&.file_path\fP = sys\&.argv[1]"
.br
.ti -1c
.RI "\fBget_rosbaginfo\&.rostopic_list\fP = get_rosbagtopics(file_path)"
.br
.ti -1c
.RI "\fBget_rosbaginfo\&.topictype_list\fP = get_type_of_topics(file_path)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
