.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/data_preprocessor/scripts/get_PCD.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/data_preprocessor/scripts/get_PCD.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBget_PCD\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_PCD\&.cloud_loader\fP (msg)"
.br
.ti -1c
.RI "def \fBget_PCD\&.save_pcd\fP (cloud, timestamp, path)"
.br
.ti -1c
.RI "def \fBget_PCD\&.rosbag_data_extract_sample\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBget_PCD\&.save_path\fP = None"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
