.TH "get_ImageTopic.ImageSaver" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_ImageTopic.ImageSaver \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBsave_path\fP, \fBoutput_type\fP, \fBbagfile\fP, \fBtopic\fP)"
.br
.ti -1c
.RI "def \fBimg_loader\fP (self, image_msg)"
.br
.ti -1c
.RI "def \fBsave_image\fP (self, img, timestamp, sfx)"
.br
.ti -1c
.RI "def \fBsave_h5file\fP (self, img, timestamp)"
.br
.ti -1c
.RI "def \fBprocess\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsave_path\fP"
.br
.ti -1c
.RI "\fBtopic\fP"
.br
.ti -1c
.RI "\fBoutput_type\fP"
.br
.ti -1c
.RI "\fBbagfile\fP"
.br
.ti -1c
.RI "\fBimg_datasets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file get_ImageTopic\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def get_ImageTopic\&.ImageSaver\&.__init__ ( self,  save_path,  output_type,  bagfile,  topic)"

.PP
Definition at line 15 of file get_ImageTopic\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def get_ImageTopic\&.ImageSaver\&.img_loader ( self,  image_msg)"

.PP
Definition at line 22 of file get_ImageTopic\&.py\&.
.SS "def get_ImageTopic\&.ImageSaver\&.process ( self)"

.PP
Definition at line 41 of file get_ImageTopic\&.py\&.
.SS "def get_ImageTopic\&.ImageSaver\&.save_h5file ( self,  img,  timestamp)"

.PP
Definition at line 36 of file get_ImageTopic\&.py\&.
.SS "def get_ImageTopic\&.ImageSaver\&.save_image ( self,  img,  timestamp,  sfx)"

.PP
Definition at line 33 of file get_ImageTopic\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "get_ImageTopic\&.ImageSaver\&.bagfile"

.PP
Definition at line 19 of file get_ImageTopic\&.py\&.
.SS "get_ImageTopic\&.ImageSaver\&.img_datasets"

.PP
Definition at line 20 of file get_ImageTopic\&.py\&.
.SS "get_ImageTopic\&.ImageSaver\&.output_type"

.PP
Definition at line 18 of file get_ImageTopic\&.py\&.
.SS "get_ImageTopic\&.ImageSaver\&.save_path"

.PP
Definition at line 16 of file get_ImageTopic\&.py\&.
.SS "get_ImageTopic\&.ImageSaver\&.topic"

.PP
Definition at line 17 of file get_ImageTopic\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
