.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/libs/dpm_ttic/gpu/get_boxes.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/libs/dpm_ttic/gpu/get_boxes.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'MODEL_info\&.h'\fP
.br
\fC#include 'common\&.hpp'\fP
.br
\fC#include 'for_use_GPU\&.h'\fP
.br
\fC#include 'switch_float\&.h'\fP
.br
\fC#include 'switch_release\&.h'\fP
.br
\fC#include 'dt\&.hpp'\fP
.br
\fC#include 'dt_GPU\&.hpp'\fP
.br
\fC#include 'detect\&.hpp'\fP
.br
\fC#include 'fconvsMT\&.hpp'\fP
.br
\fC#include <cuda_util\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLOAT\fP * \fBdpm_ttic_gpu_get_boxes\fP (\fBFLOAT\fP **features, \fBFLOAT\fP *scales, int *feature_size, \fBGPUModel\fP *MO, int *detected_count, \fBFLOAT\fP *acc_score, \fBFLOAT\fP thresh)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmax_numpart\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLOAT\fP* dpm_ttic_gpu_get_boxes (\fBFLOAT\fP ** features, \fBFLOAT\fP * scales, int * feature_size, \fBGPUModel\fP * MO, int * detected_count, \fBFLOAT\fP * acc_score, \fBFLOAT\fP thresh)"

.PP
Definition at line 355 of file get_boxes\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int max_numpart = 0"

.PP
Definition at line 25 of file get_boxes\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
