.TH "/home/deng/Project/autobot-feature-decision/ros/src/data/packages/map_file/include/map_file/get_file.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/data/packages/map_file/include/map_file/get_file.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <string>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGetFile\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHTTP_HOSTNAME\fP   '133\&.6\&.148\&.90'"
.br
.ti -1c
.RI "#define \fBHTTP_PORT\fP   (80)"
.br
.ti -1c
.RI "#define \fBHTTP_USER\fP   ''"
.br
.ti -1c
.RI "#define \fBHTTP_PASSWORD\fP   ''"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HTTP_HOSTNAME   '133\&.6\&.148\&.90'"

.PP
Definition at line 24 of file get_file\&.h\&.
.SS "#define HTTP_PASSWORD   ''"

.PP
Definition at line 27 of file get_file\&.h\&.
.SS "#define HTTP_PORT   (80)"

.PP
Definition at line 25 of file get_file\&.h\&.
.SS "#define HTTP_USER   ''"

.PP
Definition at line 26 of file get_file\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
