.TH "GetFile" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GetFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <get_file\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGetFile\fP ()"
.br
.ti -1c
.RI "\fBGetFile\fP (const std::string &host_name, int port, const std::string &user, const std::string &password)"
.br
.ti -1c
.RI "int \fBGetHTTPFile\fP (const std::string &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file get_file\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GetFile::GetFile ()"

.PP
Definition at line 31 of file get_file\&.cpp\&.
.SS "GetFile::GetFile (const std::string & host_name, int port, const std::string & user, const std::string & password)\fC [explicit]\fP"

.PP
Definition at line 36 of file get_file\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int GetFile::GetHTTPFile (const std::string & value)"

.PP
Definition at line 47 of file get_file\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
