.TH "/home/deng/Project/autobot-feature-decision/ros/src/driveworks/packages/autoware_driveworks_interface/nodes/gmsl_interface/gmsl_interface_node.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/driveworks/packages/autoware_driveworks_interface/nodes/gmsl_interface/gmsl_interface_node.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include 'gmsl_interface\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsig_int_handler\fP (int sig)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgmsl_camera::GMSLCameraNode\fP * \fBgmsl_ptr\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 44 of file gmsl_interface_node\&.cpp\&.
.SS "void sig_int_handler (int sig)"

.PP
Definition at line 38 of file gmsl_interface_node\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBgmsl_camera::GMSLCameraNode\fP* gmsl_ptr"

.PP
Definition at line 36 of file gmsl_interface_node\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
