.TH "gmsl_camera::GMSLCameraNode" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gmsl_camera::GMSLCameraNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gmsl_interface\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGMSLCameraNode\fP ()"
.br
.ti -1c
.RI "\fB~GMSLCameraNode\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBg_runSetter\fP (bool)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBargc_\fP"
.br
.ti -1c
.RI "char ** \fBargv_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file gmsl_interface\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "gmsl_camera::GMSLCameraNode::GMSLCameraNode ()"

.SS "gmsl_camera::GMSLCameraNode::~GMSLCameraNode ()"

.SH "Member Function Documentation"
.PP 
.SS "void gmsl_camera::GMSLCameraNode::g_runSetter (bool)"

.SS "void gmsl_camera::GMSLCameraNode::run ()"

.SH "Member Data Documentation"
.PP 
.SS "int gmsl_camera::GMSLCameraNode::argc_"

.PP
Definition at line 50 of file gmsl_interface\&.hpp\&.
.SS "char** gmsl_camera::GMSLCameraNode::argv_"

.PP
Definition at line 51 of file gmsl_interface\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
