.TH "GPS_Point" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPS_Point \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGPS_Point\fP (double _lat, double _lon, double _alt)"
.br
.ti -1c
.RI "\fBGPS_Point\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlat\fP"
.br
.ti -1c
.RI "double \fBlon\fP"
.br
.ti -1c
.RI "double \fBalt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file nmea2kml\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GPS_Point::GPS_Point (double _lat, double _lon, double _alt)\fC [inline]\fP"

.PP
Definition at line 64 of file nmea2kml\&.cpp\&.
.SS "GPS_Point::GPS_Point ()\fC [inline]\fP"

.PP
Definition at line 71 of file nmea2kml\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double GPS_Point::alt"

.PP
Definition at line 62 of file nmea2kml\&.cpp\&.
.SS "double GPS_Point::lat"

.PP
Definition at line 60 of file nmea2kml\&.cpp\&.
.SS "double GPS_Point::lon"

.PP
Definition at line 61 of file nmea2kml\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
