.TH "GpuEuclideanCluster::GClusterIndex" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GpuEuclideanCluster::GClusterIndex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gpu_euclidean_clustering\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex_value\fP"
.br
.ti -1c
.RI "std::vector< int > \fBpoints_in_cluster\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file gpu_euclidean_clustering\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int GpuEuclideanCluster::GClusterIndex::index_value"

.PP
Definition at line 12 of file gpu_euclidean_clustering\&.h\&.
.SS "std::vector<int> GpuEuclideanCluster::GClusterIndex::points_in_cluster"

.PP
Definition at line 13 of file gpu_euclidean_clustering\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
