.TH "GPUModel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPUModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MODEL_info\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModel_info\fP * \fBMI\fP"
.br
.ti -1c
.RI "\fBRootfilters\fP * \fBRF\fP"
.br
.ti -1c
.RI "\fBPartfilters\fP * \fBPF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file MODEL_info\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBModel_info\fP* GPUModel::MI"

.PP
Definition at line 68 of file MODEL_info\&.h\&.
.SS "\fBPartfilters\fP* GPUModel::PF"

.PP
Definition at line 70 of file MODEL_info\&.h\&.
.SS "\fBRootfilters\fP* GPUModel::RF"

.PP
Definition at line 69 of file MODEL_info\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
