.TH "HealthAggregator" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HealthAggregator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <health_aggregator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHealthAggregator\fP (ros::NodeHandle nh, ros::NodeHandle pnh)"
.br
.ti -1c
.RI "\fB~HealthAggregator\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file health_aggregator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HealthAggregator::HealthAggregator (ros::NodeHandle nh, ros::NodeHandle pnh)"

.PP
Definition at line 22 of file health_aggregator\&.cpp\&.
.SS "HealthAggregator::~HealthAggregator ()"

.PP
Definition at line 27 of file health_aggregator\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HealthAggregator::run (void)"

.PP
Definition at line 29 of file health_aggregator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
