.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/ff_waypoint_follower/include/HevCnt.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/ff_waypoint_follower/include/HevCnt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'HevControl\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBattInf\fP"
.br
.ti -1c
.RI "struct \fBBrakeInf\fP"
.br
.ti -1c
.RI "struct \fBOtherInf\fP"
.br
.ti -1c
.RI "struct \fBDrvInf\fP"
.br
.ti -1c
.RI "struct \fBStrInf\fP"
.br
.ti -1c
.RI "struct \fBAccInf\fP"
.br
.ti -1c
.RI "struct \fBGyroInf\fP"
.br
.ti -1c
.RI "struct \fBCompInf\fP"
.br
.ti -1c
.RI "struct \fBSensorInf\fP"
.br
.ti -1c
.RI "struct \fBConfigInf\fP"
.br
.ti -1c
.RI "struct \fBselectLogInf\fP"
.br
.ti -1c
.RI "class \fBChangeConfig\fP"
.br
.ti -1c
.RI "class \fBHevCnt\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSAMPLE_APP_VERSION\fP   '01\&.01\&.01'"
.br
.ti -1c
.RI "#define \fBUSE_DEMO\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SAMPLE_APP_VERSION   '01\&.01\&.01'"

.PP
Definition at line 10 of file HevCnt\&.h\&.
.SS "#define USE_DEMO   1"

.PP
Definition at line 11 of file HevCnt\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
