.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/hokuyo/nodes/hokuyo_3d/hokuyo_3d.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/hokuyo/nodes/hokuyo_3d/hokuyo_3d.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <sensor_msgs/MagneticField\&.h>\fP
.br
\fC#include <sensor_msgs/Imu\&.h>\fP
.br
\fC#include 'vssp\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhokuyo3d_node\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_INVALID_RANGE\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _INVALID_RANGE   1"

.PP
Definition at line 38 of file hokuyo_3d\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 326 of file hokuyo_3d\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
