.TH "HungarianAlgorithm" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HungarianAlgorithm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hungarian\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHungarianAlgorithm\fP ()"
.br
.ti -1c
.RI "\fB~HungarianAlgorithm\fP ()"
.br
.ti -1c
.RI "double \fBSolve\fP (vector< vector< double > > &DistMatrix, vector< int > &Assignment)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file hungarian\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HungarianAlgorithm::HungarianAlgorithm ()"

.PP
Definition at line 18 of file hungarian\&.cpp\&.
.SS "HungarianAlgorithm::~HungarianAlgorithm ()"

.PP
Definition at line 22 of file hungarian\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double HungarianAlgorithm::Solve (vector< vector< double > > & DistMatrix, vector< int > & Assignment)"

.PP
Definition at line 30 of file hungarian\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
