.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/filters/packages/image_processor/nodes/image_rotator/image_rotator_node.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/filters/packages/image_processor/nodes/image_rotator/image_rotator_node.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br
\fC#include <sensor_msgs/Image\&.h>\fP
.br
\fC#include <sensor_msgs/image_encodings\&.h>\fP
.br
\fC#include <sensor_msgs/CameraInfo\&.h>\fP
.br
\fC#include 'opencv2/highgui/highgui\&.hpp'\fP
.br
\fC#include 'opencv2/imgproc/imgproc\&.hpp'\fP
.br
\fC#include 'opencv2/calib3d/calib3d\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBROSImageRotatorApp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_NODE_NAME_\fP   'image_rotator'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _NODE_NAME_   'image_rotator'"

.PP
Definition at line 31 of file image_rotator_node\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 136 of file image_rotator_node\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
