.TH "image" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
image \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <darknet\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBc\fP"
.br
.ti -1c
.RI "float * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 507 of file darknet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int image::c"

.PP
Definition at line 510 of file darknet\&.h\&.
.SS "float* image::data"

.PP
Definition at line 511 of file darknet\&.h\&.
.SS "int image::h"

.PP
Definition at line 509 of file darknet\&.h\&.
.SS "int image::w"

.PP
Definition at line 508 of file darknet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
