.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_tracker/packages/lidar_imm_ukf_pda_track/include/imm_transformer.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_tracker/packages/lidar_imm_ukf_pda_track/include/imm_transformer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <ros/package\&.h>\fP
.br
\fC#include <pcl/point_cloud\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <pcl_ros/transforms\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include 'autoware_msgs/DetectedObjectArray\&.h'\fP
.br
\fC#include 'autoware_msgs/DetectedObject\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImmTransformer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
