.TH "insidedesign.MyApp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
insidedesign.MyApp \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits App\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBOnInit\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 327 of file insidedesign\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def insidedesign\&.MyApp\&.OnInit ( self)"

.PP
Definition at line 328 of file insidedesign\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
