.TH "integrated_viewer::TrafficLightPlugin::StateInfo" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
integrated_viewer::TrafficLightPlugin::StateInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <traffic_light_plugin\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBlabel\fP"
.br
.ti -1c
.RI "QColor \fBlabel_color\fP"
.br
.ti -1c
.RI "cv::Scalar \fBview_color\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file traffic_light_plugin\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString integrated_viewer::TrafficLightPlugin::StateInfo::label"

.PP
Definition at line 33 of file traffic_light_plugin\&.h\&.
.SS "QColor integrated_viewer::TrafficLightPlugin::StateInfo::label_color"

.PP
Definition at line 34 of file traffic_light_plugin\&.h\&.
.SS "cv::Scalar integrated_viewer::TrafficLightPlugin::StateInfo::view_color"

.PP
Definition at line 35 of file traffic_light_plugin\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
