.TH "KeyPair" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyPair \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyPair\fP ()"
.br
.ti -1c
.RI "void \fBresize\fP (int size)"
.br
.ti -1c
.RI "void \fBpush_front\fP (ros::Time sensor_time, ros::Time execution_time)"
.br
.ti -1c
.RI "ros::Time \fBfront\fP (void)"
.br
.ti -1c
.RI "ros::Time \fBfind\fP (ros::Time sensor_time)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file time_monitor\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyPair::KeyPair ()\fC [inline]\fP"

.PP
Definition at line 48 of file time_monitor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "ros::Time KeyPair::find (ros::Time sensor_time)\fC [inline]\fP"

.PP
Definition at line 64 of file time_monitor\&.cpp\&.
.SS "ros::Time KeyPair::front (void)\fC [inline]\fP"

.PP
Definition at line 60 of file time_monitor\&.cpp\&.
.SS "void KeyPair::push_front (ros::Time sensor_time, ros::Time execution_time)\fC [inline]\fP"

.PP
Definition at line 56 of file time_monitor\&.cpp\&.
.SS "void KeyPair::resize (int size)\fC [inline]\fP"

.PP
Definition at line 52 of file time_monitor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
