.TH "kitti_player_options" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kitti_player_options \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "float \fBfrequency\fP"
.br
.ti -1c
.RI "bool \fBall_data\fP"
.br
.ti -1c
.RI "bool \fBvelodyne\fP"
.br
.ti -1c
.RI "bool \fBgps\fP"
.br
.ti -1c
.RI "bool \fBimu\fP"
.br
.ti -1c
.RI "bool \fBgrayscale\fP"
.br
.ti -1c
.RI "bool \fBcolor\fP"
.br
.ti -1c
.RI "bool \fBviewer\fP"
.br
.ti -1c
.RI "bool \fBtimestamps\fP"
.br
.ti -1c
.RI "bool \fBsendTransform\fP"
.br
.ti -1c
.RI "bool \fBstereoDisp\fP"
.br
.ti -1c
.RI "bool \fBviewDisparities\fP"
.br
.ti -1c
.RI "unsigned int \fBstartFrame\fP"
.br
.ti -1c
.RI "bool \fBlaneDetections\fP"
.br
.RI "\fIExtra parameters\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file kitti_player\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool kitti_player_options::all_data"

.PP
Definition at line 70 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::color"

.PP
Definition at line 75 of file kitti_player\&.cpp\&.
.SS "float kitti_player_options::frequency"

.PP
Definition at line 69 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::gps"

.PP
Definition at line 72 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::grayscale"

.PP
Definition at line 74 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::imu"

.PP
Definition at line 73 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::laneDetections"

.PP
Extra parameters\&. 
.PP
Definition at line 84 of file kitti_player\&.cpp\&.
.SS "string kitti_player_options::path"

.PP
Definition at line 68 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::sendTransform"

.PP
Definition at line 78 of file kitti_player\&.cpp\&.
.SS "unsigned int kitti_player_options::startFrame"

.PP
Definition at line 81 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::stereoDisp"

.PP
Definition at line 79 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::timestamps"

.PP
Definition at line 77 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::velodyne"

.PP
Definition at line 71 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::viewDisparities"

.PP
Definition at line 80 of file kitti_player\&.cpp\&.
.SS "bool kitti_player_options::viewer"

.PP
Definition at line 76 of file kitti_player\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
