.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/trafficlight_recognizer/nodes/label_maker/label_maker_gui.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/trafficlight_recognizer/nodes/label_maker/label_maker_gui.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'label_maker_gui\&.h'\fP
.br
\fC#include 'file_system_operator\&.h'\fP
.br
\fC#include 'ui_label_maker_gui\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
