.TH "lane_planner::vmap::VectorMap" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lane_planner::vmap::VectorMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lane_planner_vmap\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBvector_map::Point\fP > \fBpoints\fP"
.br
.ti -1c
.RI "std::vector< vector_map::Lane > \fBlanes\fP"
.br
.ti -1c
.RI "std::vector< vector_map::Node > \fBnodes\fP"
.br
.ti -1c
.RI "std::vector< vector_map::StopLine > \fBstoplines\fP"
.br
.ti -1c
.RI "std::vector< vector_map::DTLane > \fBdtlanes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file lane_planner_vmap\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<vector_map::DTLane> lane_planner::vmap::VectorMap::dtlanes"

.PP
Definition at line 51 of file lane_planner_vmap\&.hpp\&.
.SS "std::vector<vector_map::Lane> lane_planner::vmap::VectorMap::lanes"

.PP
Definition at line 48 of file lane_planner_vmap\&.hpp\&.
.SS "std::vector<vector_map::Node> lane_planner::vmap::VectorMap::nodes"

.PP
Definition at line 49 of file lane_planner_vmap\&.hpp\&.
.SS "std::vector<\fBvector_map::Point\fP> lane_planner::vmap::VectorMap::points"

.PP
Definition at line 47 of file lane_planner_vmap\&.hpp\&.
.SS "std::vector<vector_map::StopLine> lane_planner::vmap::VectorMap::stoplines"

.PP
Definition at line 50 of file lane_planner_vmap\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
