.TH "Launch" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Launch \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLaunch\fP (const char *launch)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file tablet_receiver\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Launch::Launch (const char * launch)\fC [explicit]\fP"

.PP
Definition at line 64 of file tablet_receiver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Launch::start ()"

.PP
Definition at line 70 of file tablet_receiver\&.cpp\&.
.SS "void Launch::stop ()"

.PP
Definition at line 90 of file tablet_receiver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
