.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_launcher/src/autoware_launcher/core/launch.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_launcher/src/autoware_launcher/core/launch.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBautoware_launcher\&.core\&.launch\&.AwBaseNode\fP"
.br
.ti -1c
.RI "class \fBautoware_launcher\&.core\&.launch\&.AwBaseTree\fP"
.br
.ti -1c
.RI "class \fBautoware_launcher\&.core\&.launch\&.AwLaunchTree\fP"
.br
.ti -1c
.RI "class \fBautoware_launcher\&.core\&.launch\&.AwLaunchNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBautoware_launcher\&.core\&.launch\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBautoware_launcher\&.core\&.launch\&.logger\fP = getLogger(__name__)"
.br
.ti -1c
.RI "\fBautoware_launcher\&.core\&.launch\&.plugin\fP = AwPluginTree()"
.br
.ti -1c
.RI "\fBautoware_launcher\&.core\&.launch\&.launch\fP = AwLaunchTree(None)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
