.TH "lf_request" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lf_request \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlf_request\fP (const std_msgs::Bool &msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBtype\fP"
.br
.ti -1c
.RI "int32_t \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file tablet_sender\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lf_request::lf_request (const std_msgs::Bool & msg)\fC [inline]\fP"

.PP
Definition at line 98 of file tablet_sender\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int32_t lf_request::data"

.PP
Definition at line 96 of file tablet_sender\&.cpp\&.
.SS "int32_t lf_request::type"

.PP
Definition at line 95 of file tablet_sender\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
