.TH "lgsvl_simulator_bridge.configurator.RqtLgsvlSimulatorConfiguratorPlugin" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lgsvl_simulator_bridge.configurator.RqtLgsvlSimulatorConfiguratorPlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Plugin\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, context)"
.br
.ti -1c
.RI "def \fBshutdown_plugin\fP (self)"
.br
.ti -1c
.RI "def \fBsave_settings\fP (self, plugin_settings, instance_settings)"
.br
.ti -1c
.RI "def \fBrestore_settings\fP (self, pluign_settings, instance_settings)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsettings\fP"
.br
.ti -1c
.RI "\fBjson_dict\fP"
.br
.ti -1c
.RI "\fBinstance_id\fP"
.br
.ti -1c
.RI "\fBis_remote\fP"
.br
.ti -1c
.RI "\fBproc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file configurator\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.__init__ ( self,  context)"

.PP
Definition at line 16 of file configurator\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.restore_settings ( self,  pluign_settings,  instance_settings)"

.PP
Definition at line 79 of file configurator\&.py\&.
.SS "def lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.save_settings ( self,  plugin_settings,  instance_settings)"

.PP
Definition at line 74 of file configurator\&.py\&.
.SS "def lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.shutdown_plugin ( self)"

.PP
Definition at line 70 of file configurator\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.instance_id"

.PP
Definition at line 63 of file configurator\&.py\&.
.SS "lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.is_remote"

.PP
Definition at line 64 of file configurator\&.py\&.
.SS "lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.json_dict"

.PP
Definition at line 62 of file configurator\&.py\&.
.SS "lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.proc"

.PP
Definition at line 87 of file configurator\&.py\&.
.SS "lgsvl_simulator_bridge\&.configurator\&.RqtLgsvlSimulatorConfiguratorPlugin\&.settings"

.PP
Definition at line 19 of file configurator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
