.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/lib/libwaypoint_follower.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/lib/libwaypoint_follower.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'waypoint_follower/libwaypoint_follower\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBDecelerateVelocity\fP (double \fBdistance\fP, double prev_velocity)"
.br
.ti -1c
.RI "\fBgeometry_msgs::Point\fP \fBcalcRelativeCoordinate\fP (\fBgeometry_msgs::Point\fP point_msg, geometry_msgs::Pose current_pose)"
.br
.ti -1c
.RI "\fBgeometry_msgs::Point\fP \fBcalcAbsoluteCoordinate\fP (\fBgeometry_msgs::Point\fP point_msg, geometry_msgs::Pose current_pose)"
.br
.ti -1c
.RI "double \fBgetPlaneDistance\fP (\fBgeometry_msgs::Point\fP target1, \fBgeometry_msgs::Point\fP target2)"
.br
.ti -1c
.RI "double \fBgetRelativeAngle\fP (geometry_msgs::Pose waypoint_pose, geometry_msgs::Pose vehicle_pose)"
.br
.ti -1c
.RI "int \fBgetClosestWaypoint\fP (const autoware_msgs::Lane &current_path, geometry_msgs::Pose current_pose)"
.br
.ti -1c
.RI "bool \fBgetLinearEquation\fP (\fBgeometry_msgs::Point\fP start, \fBgeometry_msgs::Point\fP end, double *a, double *\fBb\fP, double *\fBc\fP)"
.br
.ti -1c
.RI "double \fBgetDistanceBetweenLineAndPoint\fP (\fBgeometry_msgs::Point\fP point, double a, double \fBb\fP, double \fBc\fP)"
.br
.ti -1c
.RI "\fBtf::Vector3\fP \fBpoint2vector\fP (\fBgeometry_msgs::Point\fP point)"
.br
.ti -1c
.RI "\fBgeometry_msgs::Point\fP \fBvector2point\fP (\fBtf::Vector3\fP vector)"
.br
.ti -1c
.RI "\fBtf::Vector3\fP \fBrotateUnitVector\fP (\fBtf::Vector3\fP unit_vector, double degree)"
.br
.ti -1c
.RI "\fBgeometry_msgs::Point\fP \fBrotatePoint\fP (\fBgeometry_msgs::Point\fP point, double degree)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgeometry_msgs::Point\fP calcAbsoluteCoordinate (\fBgeometry_msgs::Point\fP point_msg, geometry_msgs::Pose current_pose)"

.PP
Definition at line 121 of file libwaypoint_follower\&.cpp\&.
.SS "\fBgeometry_msgs::Point\fP calcRelativeCoordinate (\fBgeometry_msgs::Point\fP point_msg, geometry_msgs::Pose current_pose)"

.PP
Definition at line 105 of file libwaypoint_follower\&.cpp\&.
.SS "double DecelerateVelocity (double distance, double prev_velocity)"

.PP
Definition at line 88 of file libwaypoint_follower\&.cpp\&.
.SS "int getClosestWaypoint (const autoware_msgs::Lane & current_path, geometry_msgs::Pose current_pose)"

.PP
Definition at line 161 of file libwaypoint_follower\&.cpp\&.
.SS "double getDistanceBetweenLineAndPoint (\fBgeometry_msgs::Point\fP point, double a, double b, double c)"

.PP
Definition at line 250 of file libwaypoint_follower\&.cpp\&.
.SS "bool getLinearEquation (\fBgeometry_msgs::Point\fP start, \fBgeometry_msgs::Point\fP end, double * a, double * b, double * c)"

.PP
Definition at line 231 of file libwaypoint_follower\&.cpp\&.
.SS "double getPlaneDistance (\fBgeometry_msgs::Point\fP target1, \fBgeometry_msgs::Point\fP target2)"

.PP
Definition at line 135 of file libwaypoint_follower\&.cpp\&.
.SS "double getRelativeAngle (geometry_msgs::Pose waypoint_pose, geometry_msgs::Pose vehicle_pose)"

.PP
Definition at line 144 of file libwaypoint_follower\&.cpp\&.
.SS "\fBtf::Vector3\fP point2vector (\fBgeometry_msgs::Point\fP point)"

.PP
Definition at line 257 of file libwaypoint_follower\&.cpp\&.
.SS "\fBgeometry_msgs::Point\fP rotatePoint (\fBgeometry_msgs::Point\fP point, double degree)"

.PP
Definition at line 281 of file libwaypoint_follower\&.cpp\&.
.SS "\fBtf::Vector3\fP rotateUnitVector (\fBtf::Vector3\fP unit_vector, double degree)"

.PP
Definition at line 272 of file libwaypoint_follower\&.cpp\&.
.SS "\fBgeometry_msgs::Point\fP vector2point (\fBtf::Vector3\fP vector)"

.PP
Definition at line 263 of file libwaypoint_follower\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
