.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_fake_perception/include/lidar_fake_perception.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_fake_perception/include/lidar_fake_perception.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <tf_conversions/tf_eigen\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <geometry_msgs/Twist\&.h>\fP
.br
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include <autoware_msgs/DetectedObject\&.h>\fP
.br
\fC#include <autoware_msgs/DetectedObjectArray\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <pcl_ros/point_cloud\&.h>\fP
.br
\fC#include <pcl_ros/transforms\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLidarFakePerception\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
