.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/LocalPlannerH.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/LocalPlannerH.h \- OpenPlanner's local planing functions combines in one process, used in simulation vehicle and OpenPlanner old implementation like dp_planner node\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'BehaviorStateMachine\&.h'\fP
.br
\fC#include 'PlannerCommonDef\&.h'\fP
.br
\fC#include 'RoadNetwork\&.h'\fP
.br
\fC#include 'TrajectoryCosts\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerHNS::LocalPlannerH\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlannerHNS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAVOIDANCE_SPEED_FACTOR\fP   0\&.75"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenPlanner's local planing functions combines in one process, used in simulation vehicle and OpenPlanner old implementation like dp_planner node\&. 


.PP
\fBAuthor:\fP
.RS 4
Hatem Darweesh 
.RE
.PP
\fBDate:\fP
.RS 4
Dec 14, 2016 
.RE
.PP

.PP
Definition in file \fBLocalPlannerH\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AVOIDANCE_SPEED_FACTOR   0\&.75"

.PP
Definition at line 16 of file LocalPlannerH\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
