.TH "Logger" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point_pillars\&.h>\fP
.PP
Inherits ILogger\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogger\fP (Severity severity=Severity::kWARNING)"
.br
.ti -1c
.RI "void \fBlog\fP (Severity severity, const char *msg) override"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Severity \fBreportableSeverity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file point_pillars\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Logger::Logger (Severity severity = \fCSeverity::kWARNING\fP)\fC [inline]\fP"

.PP
Definition at line 52 of file point_pillars\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Logger::log (Severity severity, const char * msg)\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 56 of file point_pillars\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "Severity Logger::reportableSeverity"

.PP
Definition at line 83 of file point_pillars\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
