.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/MappingHelpers.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/MappingHelpers.h \- Helper functions for mapping operation such as (load and initialize vector maps , convert map from one format to another, \&.\&. )  

.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include 'RoadNetwork\&.h'\fP
.br
\fC#include 'op_utility/UtilityH\&.h'\fP
.br
\fC#include 'op_utility/DataRW\&.h'\fP
.br
\fC#include 'tinyxml\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerHNS::MappingHelpers\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlannerHNS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper functions for mapping operation such as (load and initialize vector maps , convert map from one format to another, \&.\&. ) 


.PP
\fBAuthor:\fP
.RS 4
Hatem Darweesh 
.RE
.PP
\fBDate:\fP
.RS 4
Jul 2, 2016 
.RE
.PP

.PP
Definition in file \fBMappingHelpers\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
