.TH "/home/deng/Project/autobot-feature-decision/ros/src/common/libvectormap/include/libvectormap/Math.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/common/libvectormap/include/libvectormap/Math.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Eigen/Eigen>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Eigen::Vector2f \fBPoint2\fP"
.br
.ti -1c
.RI "typedef Eigen::Vector3f \fBPoint3\fP"
.br
.ti -1c
.RI "typedef Eigen::Vector3f \fBVector3\fP"
.br
.ti -1c
.RI "typedef Eigen::Vector4f \fBPoint4\fP"
.br
.ti -1c
.RI "typedef Eigen::Vector4f \fBVector4\fP"
.br
.ti -1c
.RI "typedef Eigen::Vector2f \fBVector2\fP"
.br
.ti -1c
.RI "typedef Eigen::Quaternionf \fBQuaternion\fP"
.br
.ti -1c
.RI "typedef Eigen::Matrix4f \fBMatrix4\fP"
.br
.ti -1c
.RI "typedef Eigen::Matrix2f \fBMatrix2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdistance\fP (const \fBPoint2\fP &p1, const \fBPoint2\fP &p2)"
.br
.ti -1c
.RI "double \fBdistance\fP (const \fBPoint3\fP &p1, const \fBPoint3\fP &p2)"
.br
.ti -1c
.RI "double \fBdistance\fP (const \fBPoint4\fP &p1, const \fBPoint4\fP &p2)"
.br
.ti -1c
.RI "double \fBdistance\fP (const double &x1, const double &y1, const double &x2, const double &y2)"
.br
.ti -1c
.RI "\fBVector2\fP \fBperpendicular\fP (const \fBVector2\fP &v)"
.br
.ti -1c
.RI "void \fBrotate\fP (\fBVector2\fP &v, const float angleInDegree)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef Eigen::Matrix2f \fBMatrix2\fP"

.PP
Definition at line 23 of file Math\&.h\&.
.SS "typedef Eigen::Matrix4f \fBMatrix4\fP"

.PP
Definition at line 22 of file Math\&.h\&.
.SS "typedef Eigen::Vector2f \fBPoint2\fP"

.PP
Definition at line 15 of file Math\&.h\&.
.SS "typedef Eigen::Vector3f \fBPoint3\fP"

.PP
Definition at line 16 of file Math\&.h\&.
.SS "typedef Eigen::Vector4f \fBPoint4\fP"

.PP
Definition at line 18 of file Math\&.h\&.
.SS "typedef Eigen::Quaternionf \fBQuaternion\fP"

.PP
Definition at line 21 of file Math\&.h\&.
.SS "typedef Eigen::Vector2f \fBVector2\fP"

.PP
Definition at line 20 of file Math\&.h\&.
.SS "typedef Eigen::Vector3f \fBVector3\fP"

.PP
Definition at line 17 of file Math\&.h\&.
.SS "typedef Eigen::Vector4f \fBVector4\fP"

.PP
Definition at line 19 of file Math\&.h\&.
.SH "Function Documentation"
.PP 
.SS "double distance (const \fBPoint2\fP & p1, const \fBPoint2\fP & p2)\fC [inline]\fP"

.PP
Definition at line 33 of file Math\&.h\&.
.SS "double distance (const \fBPoint3\fP & p1, const \fBPoint3\fP & p2)\fC [inline]\fP"

.PP
Definition at line 40 of file Math\&.h\&.
.SS "double distance (const \fBPoint4\fP & p1, const \fBPoint4\fP & p2)\fC [inline]\fP"

.PP
Definition at line 47 of file Math\&.h\&.
.SS "double distance (const double & x1, const double & y1, const double & x2, const double & y2)\fC [inline]\fP"

.PP
Definition at line 54 of file Math\&.h\&.
.SS "\fBVector2\fP perpendicular (const \fBVector2\fP & v)\fC [inline]\fP"

.PP
Definition at line 61 of file Math\&.h\&.
.SS "void rotate (\fBVector2\fP & v, const float angleInDegree)\fC [inline]\fP"

.PP
Definition at line 65 of file Math\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
