.TH "md__home_deng__project_autobot-feature-decision_ros_src_sensing_drivers_imu_packages_xsens__c_h_a_n_g_e_l_o_g" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_deng__project_autobot-feature-decision_ros_src_sensing_drivers_imu_packages_xsens__c_h_a_n_g_e_l_o_g \- Changelog for package xsens_mti_ros_node 

.SS "3\&.0\&.0 (2016-05-27)"
.PP
.IP "\(bu" 2
Added functionality to detect devices based on product masks (incl\&. 1-series and FMT1000 devices)
.IP "\(bu" 2
Increased the 'additionalTimeOutOffset' from 6ms to 10ms as default
.PP
.PP
.SS "2\&.0\&.2 (2015-11-23)"
.PP
.IP "\(bu" 2
Fix Readme
.PP
.PP
.SS "2\&.0\&.1 (2015-03-19)"
.PP
.IP "\(bu" 2
Fix documentation, switch to Markdown
.PP
.PP
.SS "2\&.0\&.0 (2015-03-19)"
.PP
.IP "\(bu" 2
Updated GNSS data identifiers
.IP "\(bu" 2
Fixed a timeout issue
.IP "\(bu" 2
Added new message files
.IP "\(bu" 2
Add baudrate checks
.IP "\(bu" 2
Add filter options
.IP "\(bu" 2
Removed support for legacy devices
.PP
.PP
.SS "1\&.0\&.0 (2014-09-02)"
.PP
.IP "\(bu" 2
Improved on MK4 functionality to publish /xsens/sensorSample messages
.PP
.PP
Built on ethzasl_xsens_driver developed by previous contributors - Enrique Fernandez, Francis Colas, Paul Mathieu, Sam Pfeiffer, Benjamin Hitov, Francis Colas, Nikolaus Demmel, Stéphane Magnenat, fcolas\&. 
