.TH "md__home_deng__project_autobot-feature-decision_ros_src_util_packages_kitti_pkg_kitti_player__r_e_a_d_m_e" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_deng__project_autobot-feature-decision_ros_src_util_packages_kitti_pkg_kitti_player__r_e_a_d_m_e \- README 
From version 2, this node aims to play the whole KITTI data into ROS (color/grayscale images, Velodyne scan as PCL, sensor_msgs/Imu Message, GPS as sensor_msgs/NavSatFix Message)\&. 
