.TH "md__home_deng__project_autobot-feature-decision_ros_src_sensing_drivers_gnss_packages_nmea_navsat_scripts__r_e_a_d_m_e" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_deng__project_autobot-feature-decision_ros_src_sensing_drivers_gnss_packages_nmea_navsat_scripts__r_e_a_d_m_e \- \fBLaunch\fP file for nmea_navsat_driver 
Serial port reader and parser for NMEA compatible GPS devices\&.
.PP
.SS "Setup"
.PP
.PP
.nf
1 $ sudo apt-get install ros-kinetic-nmea-navsat-driver
.fi
.PP
.PP
.SS "ROS run"
.PP
.PP
.nf
1 $ rosrun nmea_navsat_driver nmea_serial_driver _port:=/dev/ttyUSB0 _baud:=57600
.fi
.PP
 
