.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/Measurement.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/Measurement.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include '\&.\&./BasicDatatypes\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdatatypes::Measurement\fP"
.br
.ti -1c
.RI "class \fBdatatypes::MeasurementList\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdatatypes\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMeasurementType\fP { \fBMeastype_Unknown\fP = 0x0000, \fBMeastype_Voltage_Supply_Panel\fP = 0x0001, \fBMeastype_Temperature_Panel\fP = 0x0002, \fBMeastype_Brightness\fP = 0x0003, \fBMeastype_Voltage_Supply_Video\fP = 0x0004, \fBMeastype_Sniffpad_Panel\fP = 0x0005, \fBMeastype_DeviceName\fP = 0x0006, \fBMeastype_DeviceVersion\fP = 0x0007, \fBMeastype_ScanFreq\fP = 0x0008, \fBMeastype_ScanStartAngle\fP = 0x0009, \fBMeastype_ScanStopAngle\fP = 0x000A, \fBMeastype_ScanResolution\fP = 0x000B }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMeasurementType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMeastype_Unknown \fP\fP
.TP
\fB\fIMeastype_Voltage_Supply_Panel \fP\fP
.TP
\fB\fIMeastype_Temperature_Panel \fP\fP
.TP
\fB\fIMeastype_Brightness \fP\fP
.TP
\fB\fIMeastype_Voltage_Supply_Video \fP\fP
.TP
\fB\fIMeastype_Sniffpad_Panel \fP\fP
.TP
\fB\fIMeastype_DeviceName \fP\fP
.TP
\fB\fIMeastype_DeviceVersion \fP\fP
.TP
\fB\fIMeastype_ScanFreq \fP\fP
.TP
\fB\fIMeastype_ScanStartAngle \fP\fP
.TP
\fB\fIMeastype_ScanStopAngle \fP\fP
.TP
\fB\fIMeastype_ScanResolution \fP\fP
.PP
Definition at line 24 of file Measurement\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
