.TH "Microstrain" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Microstrain \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfilter_packet_callback_wrapper\fP (void *user_ptr, \fBu8\fP *packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"
.br
.ti -1c
.RI "void \fBahrs_packet_callback_wrapper\fP (void *user_ptr, \fBu8\fP *packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"
.br
.ti -1c
.RI "void \fBgps_packet_callback_wrapper\fP (void *user_ptr, \fBu8\fP *packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Microstrain::ahrs_packet_callback_wrapper (void * user_ptr, \fBu8\fP * packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"

.PP
Definition at line 1043 of file microstrain\&.cpp\&.
.SS "void Microstrain::filter_packet_callback_wrapper (void * user_ptr, \fBu8\fP * packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"

.PP
Definition at line 1037 of file microstrain\&.cpp\&.
.SS "void Microstrain::gps_packet_callback_wrapper (void * user_ptr, \fBu8\fP * packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"

.PP
Definition at line 1049 of file microstrain\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
