.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/imu/packages/microstrain/src/microstrain.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/imu/packages/microstrain/src/microstrain.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'microstrain\&.h'\fP
.br
\fC#include <tf2/LinearMath/Transform\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMicrostrain\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMicrostrain::filter_packet_callback_wrapper\fP (void *user_ptr, \fBu8\fP *packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"
.br
.ti -1c
.RI "void \fBMicrostrain::ahrs_packet_callback_wrapper\fP (void *user_ptr, \fBu8\fP *packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"
.br
.ti -1c
.RI "void \fBMicrostrain::gps_packet_callback_wrapper\fP (void *user_ptr, \fBu8\fP *packet, \fBu16\fP packet_size, \fBu8\fP callback_type)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
