.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/imu/packages/microstrain/MIPSDK/C/Library/Include/mip_rq1.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/imu/packages/microstrain/MIPSDK/C/Library/Include/mip_rq1.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mip\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_rq1_basic_status_field\fP"
.br
.ti -1c
.RI "struct \fB_rq1_diagnostic_status_field\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRQ1_MODEL_NUMBER\fP   6232"
.br
.RI "\fIMIP RQ1 Specific Structures and Definitions \fP"
.ti -1c
.RI "#define \fBRQ1_BASIC_STATUS_SEL\fP   1"
.br
.ti -1c
.RI "#define \fBRQ1_DIAGNOSTICS_STATUS_SEL\fP   2"
.br
.ti -1c
.RI "#define \fBRQ1_SYSTEM_STATE_INITIALIZATION\fP   0x0001"
.br
.ti -1c
.RI "#define \fBRQ1_SYSTEM_STATE_SENSOR_STARTUP\fP   0x0002"
.br
.ti -1c
.RI "#define \fBRQ1_SYSTEM_STATE_RUNNING\fP   0x0003"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_rq1_basic_status_field\fP \fBrq1_basic_status_field\fP"
.br
.ti -1c
.RI "typedef struct \fB_rq1_diagnostic_status_field\fP \fBrq1_diagnostic_device_status_field\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Nathan Miller 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP

.PP
Definition in file \fBmip_rq1\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RQ1_BASIC_STATUS_SEL   1"

.PP
Definition at line 58 of file mip_rq1\&.h\&.
.SS "#define RQ1_DIAGNOSTICS_STATUS_SEL   2"

.PP
Definition at line 59 of file mip_rq1\&.h\&.
.SS "#define RQ1_MODEL_NUMBER   6232"

.PP
MIP RQ1 Specific Structures and Definitions 
.PP
\fBCopyright:\fP
.RS 4
2014 Lord \fBMicrostrain\fP Sensing Systems\&. 
.RE
.PP
.SH "CHANGES"
.PP
THE PRESENT SOFTWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A \fBRESULT\fP, LORD MICROSTRAIN SENSING SYSTEMS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH SOFTWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&. 
.PP
Definition at line 56 of file mip_rq1\&.h\&.
.SS "#define RQ1_SYSTEM_STATE_INITIALIZATION   0x0001"

.PP
Definition at line 61 of file mip_rq1\&.h\&.
.SS "#define RQ1_SYSTEM_STATE_RUNNING   0x0003"

.PP
Definition at line 63 of file mip_rq1\&.h\&.
.SS "#define RQ1_SYSTEM_STATE_SENSOR_STARTUP   0x0002"

.PP
Definition at line 62 of file mip_rq1\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_rq1_basic_status_field\fP \fBrq1_basic_status_field\fP"

.SS "typedef struct \fB_rq1_diagnostic_status_field\fP \fBrq1_diagnostic_device_status_field\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
