.TH "mmtimer" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mmtimer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmmtimer\fP (void)"
.br
.ti -1c
.RI "virtual \fB~mmtimer\fP (void)"
.br
.ti -1c
.RI "double \fBelapsed\fP ()"
.br
.ti -1c
.RI "void \fBrestart\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file vg440_node\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mmtimer::mmtimer (void)\fC [inline]\fP"

.PP
Definition at line 22 of file vg440_node\&.cpp\&.
.SS "virtual mmtimer::~mmtimer (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 25 of file vg440_node\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double mmtimer::elapsed ()\fC [inline]\fP"

.PP
Definition at line 26 of file vg440_node\&.cpp\&.
.SS "void mmtimer::restart ()\fC [inline]\fP"

.PP
Definition at line 32 of file vg440_node\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
