.TH "mode_request" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mode_request \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmode_request\fP (const tablet_socket_msgs::mode_info &msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBtype\fP"
.br
.ti -1c
.RI "int32_t \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file tablet_sender\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mode_request::mode_request (const tablet_socket_msgs::mode_info & msg)\fC [inline]\fP"

.PP
Definition at line 69 of file tablet_sender\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int32_t mode_request::mode"

.PP
Definition at line 67 of file tablet_sender\&.cpp\&.
.SS "int32_t mode_request::type"

.PP
Definition at line 66 of file tablet_sender\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
