.TH "/home/deng/Project/autobot-feature-decision/ros/src/socket/packages/mqtt_socket/include/mqtt_socket/mqtt_setting.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/socket/packages/mqtt_socket/include/mqtt_socket/mqtt_setting.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMQTT_NODE_NAME\fP   'mqtt_socket'"
.br
.ti -1c
.RI "#define \fBMQTT_CONFIG_FILE_NAME\fP   '/mqtt_config\&.yml'"
.br
.ti -1c
.RI "#define \fBAUTO_MODE\fP   1"
.br
.ti -1c
.RI "#define \fBREMOTE_MODE\fP   2"
.br
.ti -1c
.RI "#define \fBNORMAL_MODE\fP   0"
.br
.ti -1c
.RI "#define \fBEMERGENCY_MODE\fP   1"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBgear_d\fP"
.br
.ti -1c
.RI "int \fBgear_n\fP"
.br
.ti -1c
.RI "int \fBgear_r\fP"
.br
.ti -1c
.RI "int \fBgear_p\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUTO_MODE   1"

.PP
Definition at line 5 of file mqtt_setting\&.hpp\&.
.SS "#define EMERGENCY_MODE   1"

.PP
Definition at line 8 of file mqtt_setting\&.hpp\&.
.SS "#define MQTT_CONFIG_FILE_NAME   '/mqtt_config\&.yml'"

.PP
Definition at line 2 of file mqtt_setting\&.hpp\&.
.SS "#define MQTT_NODE_NAME   'mqtt_socket'"

.PP
Definition at line 1 of file mqtt_setting\&.hpp\&.
.SS "#define NORMAL_MODE   0"

.PP
Definition at line 7 of file mqtt_setting\&.hpp\&.
.SS "#define REMOTE_MODE   2"

.PP
Definition at line 6 of file mqtt_setting\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "int gear_d"

.PP
Definition at line 21 of file mqtt_setting\&.hpp\&.
.SS "int gear_n"

.PP
Definition at line 22 of file mqtt_setting\&.hpp\&.
.SS "int gear_p"

.PP
Definition at line 24 of file mqtt_setting\&.hpp\&.
.SS "int gear_r"

.PP
Definition at line 23 of file mqtt_setting\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
