.TH "mtdef" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtdef \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaudrates\fP"
.br
.ti -1c
.RI "class \fBMID\fP"
.br
.ti -1c
.RI "class \fBMTException\fP"
.br
.ti -1c
.RI "class \fBXDIGroup\fP"
.br
.ti -1c
.RI "class \fBXDIMessage\fP"
.br
.ti -1c
.RI "class \fBXDIProductMask\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetName\fP (cls, value)"
.br
.ti -1c
.RI "def \fBgetMIDName\fP (mid)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Constant and messages definition for MT communication.
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def mtdef\&.getMIDName ( mid)"

.PP
.nf
Return the name of a message given the message id.
.fi
.PP
 
.PP
Definition at line 139 of file mtdef\&.py\&.
.SS "def mtdef\&.getName ( cls,  value)"

.PP
.nf
Return the name of the first found member of class cls with given
value.
.fi
.PP
 
.PP
Definition at line 130 of file mtdef\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
