.TH "mtnode" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtnode \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXSensDriver\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBget_param\fP (name, default)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def mtnode\&.get_param ( name,  default)"

.PP
Definition at line 23 of file mtnode\&.py\&.
.SS "def mtnode\&.main (void)"

.PP
.nf
Create a ROS node and instantiate the class.
.fi
.PP
 
.PP
Definition at line 366 of file mtnode\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
