.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_launcher/src/autoware_launcher/core/mylog.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_launcher/src/autoware_launcher/core/mylog.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBautoware_launcher\&.core\&.mylog\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBautoware_launcher\&.core\&.mylog\&.error\fP (text)"
.br
.ti -1c
.RI "def \fBautoware_launcher\&.core\&.mylog\&.warning\fP (text)"
.br
.ti -1c
.RI "def \fBautoware_launcher\&.core\&.mylog\&.info\fP (text)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
