.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/prediction/motion_predictor/packages/naive_motion_predict/include/naive_motion_predict.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/prediction/motion_predictor/packages/naive_motion_predict/include/naive_motion_predict.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <tf/transform_datatypes\&.h>\fP
.br
\fC#include <visualization_msgs/MarkerArray\&.h>\fP
.br
\fC#include 'autoware_msgs/DetectedObject\&.h'\fP
.br
\fC#include 'autoware_msgs/DetectedObjectArray\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNaiveMotionPredict\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMotionModel\fP : int { \fBCV\fP = 0, \fBCTRV\fP = 1, \fBRM\fP = 2, \fBCV\fP = 0, \fBCTRV\fP = 1, \fBRM\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMotionModel\fP : int"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICV \fP\fP
.TP
\fB\fICTRV \fP\fP
.TP
\fB\fIRM \fP\fP
.TP
\fB\fICV \fP\fP
.TP
\fB\fICTRV \fP\fP
.TP
\fB\fIRM \fP\fP
.PP
Definition at line 29 of file naive_motion_predict\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
