.TH "nd_data" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nd_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ndt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNormalDistribution\fP \fBnd\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "int \fBlayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 259 of file ndt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int nd_data::layer"

.PP
Definition at line 265 of file ndt\&.h\&.
.SS "\fBNormalDistribution\fP nd_data::nd"

.PP
Definition at line 261 of file ndt\&.h\&.
.SS "int nd_data::x"

.PP
Definition at line 262 of file ndt\&.h\&.
.SS "int nd_data::y"

.PP
Definition at line 263 of file ndt\&.h\&.
.SS "int nd_data::z"

.PP
Definition at line 264 of file ndt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
