.TH "nd_map" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nd_map \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ndt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNDPtr\fP * \fBnd\fP"
.br
.ti -1c
.RI "int \fBlayer\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "int \fBto_x\fP"
.br
.ti -1c
.RI "int \fBto_y\fP"
.br
.ti -1c
.RI "double \fBsize\fP"
.br
.ti -1c
.RI "char \fBname\fP [30]"
.br
.ti -1c
.RI "\fBNDMapPtr\fP \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 242 of file ndt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int nd_map::layer"

.PP
Definition at line 245 of file ndt\&.h\&.
.SS "char nd_map::name[30]"

.PP
Definition at line 252 of file ndt\&.h\&.
.SS "\fBNDPtr\fP* nd_map::nd"

.PP
Definition at line 244 of file ndt\&.h\&.
.SS "\fBNDMapPtr\fP nd_map::next"

.PP
Definition at line 254 of file ndt\&.h\&.
.SS "double nd_map::size"

.PP
Definition at line 251 of file ndt\&.h\&.
.SS "int nd_map::to_x"

.PP
Definition at line 249 of file ndt\&.h\&.
.SS "int nd_map::to_y"

.PP
Definition at line 250 of file ndt\&.h\&.
.SS "int nd_map::x"

.PP
Definition at line 246 of file ndt\&.h\&.
.SS "int nd_map::y"

.PP
Definition at line 247 of file ndt\&.h\&.
.SS "int nd_map::z"

.PP
Definition at line 248 of file ndt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
