.TH "NMEA_PARSER" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NMEA_PARSER \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReadNMEASentence\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBuint\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuchar\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBparseStatus\fP { \fBwaitFirstChar\fP = 0, \fBcommand\fP, \fBdata\fP, \fBcheckSum1\fP, \fBcheckSum2\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBNMEA_PARSER::uchar\fP"

.PP
Definition at line 19 of file ReadNMEASentence\&.cpp\&.
.SS "typedef unsigned int \fBNMEA_PARSER::uint\fP"

.PP
Definition at line 18 of file ReadNMEASentence\&.cpp\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNMEA_PARSER::parseStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIwaitFirstChar \fP\fP
.TP
\fB\fIcommand \fP\fP
.TP
\fB\fIdata \fP\fP
.TP
\fB\fIcheckSum1 \fP\fP
.TP
\fB\fIcheckSum2 \fP\fP
.PP
Definition at line 24 of file ReadNMEASentence\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
