.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/libs/dpm_ttic/gpu/nms.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/vision_detector/libs/dpm_ttic/gpu/nms.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'MODEL_info\&.h'\fP
.br
\fC#include 'common\&.hpp'\fP
.br
\fC#include 'switch_float\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFLOAT\fP * \fBnms\fP (\fBFLOAT\fP *boxes, \fBFLOAT\fP \fBoverlap\fP, int *num, \fBGPUModel\fP *MO)"
.br
.ti -1c
.RI "\fBFLOAT\fP * \fBdpm_ttic_gpu_nms\fP (\fBFLOAT\fP *boxes, \fBFLOAT\fP \fBoverlap\fP, int *num, \fBGPUModel\fP *MO)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBFLOAT\fP* dpm_ttic_gpu_nms (\fBFLOAT\fP * boxes, \fBFLOAT\fP overlap, int * num, \fBGPUModel\fP * MO)"

.PP
Definition at line 54 of file nms\&.cpp\&.
.SS "\fBFLOAT\fP* nms (\fBFLOAT\fP * boxes, \fBFLOAT\fP overlap, int * num, \fBGPUModel\fP * MO)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
