.TH "Normaldistribution" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Normaldistribution \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ndt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBmean\fP"
.br
.ti -1c
.RI "double \fBcovariance\fP [3][3]"
.br
.ti -1c
.RI "double \fBinv_covariance\fP [3][3]"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "int \fBsign\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "double \fBm_x\fP"
.br
.ti -1c
.RI "double \fBm_y\fP"
.br
.ti -1c
.RI "double \fBm_z\fP"
.br
.ti -1c
.RI "double \fBc_xx\fP"
.br
.ti -1c
.RI "double \fBc_yy\fP"
.br
.ti -1c
.RI "double \fBc_zz\fP"
.br
.ti -1c
.RI "double \fBc_xy\fP"
.br
.ti -1c
.RI "double \fBc_yz\fP"
.br
.ti -1c
.RI "double \fBc_zx\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBw\fP"
.br
.ti -1c
.RI "double \fBl\fP [3]"
.br
.ti -1c
.RI "int \fBis_source\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 205 of file ndt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Normaldistribution::c_xx"

.PP
Definition at line 221 of file ndt\&.h\&.
.SS "double Normaldistribution::c_xy"

.PP
Definition at line 224 of file ndt\&.h\&.
.SS "double Normaldistribution::c_yy"

.PP
Definition at line 222 of file ndt\&.h\&.
.SS "double Normaldistribution::c_yz"

.PP
Definition at line 225 of file ndt\&.h\&.
.SS "double Normaldistribution::c_zx"

.PP
Definition at line 226 of file ndt\&.h\&.
.SS "double Normaldistribution::c_zz"

.PP
Definition at line 223 of file ndt\&.h\&.
.SS "double Normaldistribution::covariance[3][3]"

.PP
Definition at line 209 of file ndt\&.h\&.
.SS "int Normaldistribution::flag"

.PP
Definition at line 212 of file ndt\&.h\&.
.SS "double Normaldistribution::inv_covariance[3][3]"

.PP
Definition at line 210 of file ndt\&.h\&.
.SS "int Normaldistribution::is_source"

.PP
Definition at line 236 of file ndt\&.h\&.
.SS "double Normaldistribution::l[3]"

.PP
Definition at line 234 of file ndt\&.h\&.
.SS "double Normaldistribution::m_x"

.PP
Definition at line 217 of file ndt\&.h\&.
.SS "double Normaldistribution::m_y"

.PP
Definition at line 218 of file ndt\&.h\&.
.SS "double Normaldistribution::m_z"

.PP
Definition at line 219 of file ndt\&.h\&.
.SS "\fBPoint\fP Normaldistribution::mean"

.PP
Definition at line 208 of file ndt\&.h\&.
.SS "int Normaldistribution::num"

.PP
Definition at line 215 of file ndt\&.h\&.
.SS "int Normaldistribution::sign"

.PP
Definition at line 213 of file ndt\&.h\&.
.SS "double Normaldistribution::w"

.PP
Definition at line 232 of file ndt\&.h\&.
.SS "double Normaldistribution::x"

.PP
Definition at line 228 of file ndt\&.h\&.
.SS "double Normaldistribution::y"

.PP
Definition at line 229 of file ndt\&.h\&.
.SS "double Normaldistribution::z"

.PP
Definition at line 230 of file ndt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
