.TH "/home/deng/Project/autobot-feature-decision/ros/src/data/packages/obj_db/include/obj_db.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/data/packages/obj_db/include/obj_db.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSendData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBmake_header\fP (int32_t sql_inst, int32_t sql_num)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string make_header (int32_t sql_inst, int32_t sql_num)"

.PP
Definition at line 11 of file util\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
