.TH "OP_TESTING_NS" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OP_TESTING_NS \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBagReaderParams\fP"
.br
.ti -1c
.RI "class \fBDisplayParams\fP"
.br
.ti -1c
.RI "class \fBDrawingHelpers\fP"
.br
.ti -1c
.RI "class \fBDrawObjBase\fP"
.br
.ti -1c
.RI "class \fBMainWindowWrapper\fP"
.br
.ti -1c
.RI "class \fBTestingUI\fP"
.br
.ti -1c
.RI "class \fBWindowParams\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDisplayMode\fP { \fBDISPLAY_FREE\fP, \fBDISPLAY_TOP_FREE\fP, \fBDISPLAY_FOLLOW\fP }"
.br
.ti -1c
.RI "enum \fBTESTING_MODE\fP { \fBSIMULATION_MODE\fP, \fBROSBAG_MODE\fP, \fBLIVE_MODE\fP }"
.br
.ti -1c
.RI "enum \fBROSBAG_PLAY_MODE\fP { \fBPLAY_FORWARD\fP, \fBPLAY_BACKWARD\fP, \fBPLAY_PAUSE\fP, \fBPLAY_STEP_FORWARD\fP, \fBPLAY_STEP_BACKWARD\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBOP_TESTING_NS::DisplayMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDISPLAY_FREE \fP\fP
.TP
\fB\fIDISPLAY_TOP_FREE \fP\fP
.TP
\fB\fIDISPLAY_FOLLOW \fP\fP
.PP
Definition at line 29 of file MainWindowWrapper\&.h\&.
.SS "enum \fBOP_TESTING_NS::ROSBAG_PLAY_MODE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPLAY_FORWARD \fP\fP
.TP
\fB\fIPLAY_BACKWARD \fP\fP
.TP
\fB\fIPLAY_PAUSE \fP\fP
.TP
\fB\fIPLAY_STEP_FORWARD \fP\fP
.TP
\fB\fIPLAY_STEP_BACKWARD \fP\fP
.PP
Definition at line 49 of file op_bag_player_core\&.h\&.
.SS "enum \fBOP_TESTING_NS::TESTING_MODE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISIMULATION_MODE \fP\fP
.TP
\fB\fIROSBAG_MODE \fP\fP
.TP
\fB\fILIVE_MODE \fP\fP
.PP
Definition at line 48 of file op_bag_player_core\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
