.TH "OP_TESTING_NS::DrawObjBase" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OP_TESTING_NS::DrawObjBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DrawObjBase\&.h>\fP
.PP
Inherited by \fBOP_TESTING_NS::TestingUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDrawSimu\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBOnKeyboardPress\fP (const int &sKey, const unsigned char &key)=0"
.br
.ti -1c
.RI "\fBDrawObjBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~DrawObjBase\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file DrawObjBase\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OP_TESTING_NS::DrawObjBase::DrawObjBase ()"

.PP
Definition at line 22 of file DrawObjBase\&.cpp\&.
.SS "OP_TESTING_NS::DrawObjBase::~DrawObjBase ()\fC [virtual]\fP"

.PP
Definition at line 26 of file DrawObjBase\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void OP_TESTING_NS::DrawObjBase::DrawSimu ()\fC [pure virtual]\fP"

.PP
Implemented in \fBOP_TESTING_NS::TestingUI\fP\&.
.SS "virtual void OP_TESTING_NS::DrawObjBase::OnKeyboardPress (const int & sKey, const unsigned char & key)\fC [pure virtual]\fP"

.PP
Implemented in \fBOP_TESTING_NS::TestingUI\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
