.TH "OP_TESTING_NS::WindowParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OP_TESTING_NS::WindowParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MainWindowWrapper\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinfo_window\fP"
.br
.ti -1c
.RI "struct \fBsimu_window\fP"
.br
.ti -1c
.RI "struct \fBUI_CONST\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowParams\fP ()"
.br
.ti -1c
.RI "void \fBReCalcSimuWindow\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "double \fBinfo_ratio\fP"
.br
.ti -1c
.RI "std::string \fBtitle\fP"
.br
.ti -1c
.RI "struct \fBOP_TESTING_NS::WindowParams::info_window\fP \fBinfo_window\fP"
.br
.ti -1c
.RI "struct \fBOP_TESTING_NS::WindowParams::simu_window\fP \fBsimu_window\fP"
.br
.ti -1c
.RI "struct \fBOP_TESTING_NS::WindowParams::UI_CONST\fP \fBUI_CONST\fP"
.br
.ti -1c
.RI "bool \fBbNew\fP"
.br
.ti -1c
.RI "bool \fBbGPU\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file MainWindowWrapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OP_TESTING_NS::WindowParams::WindowParams ()"

.PP
Definition at line 34 of file MainWindowWrapper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void OP_TESTING_NS::WindowParams::ReCalcSimuWindow ()"

.PP
Definition at line 56 of file MainWindowWrapper\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool OP_TESTING_NS::WindowParams::bGPU"

.PP
Definition at line 67 of file MainWindowWrapper\&.h\&.
.SS "bool OP_TESTING_NS::WindowParams::bNew"

.PP
Definition at line 66 of file MainWindowWrapper\&.h\&.
.SS "int OP_TESTING_NS::WindowParams::h"

.PP
Definition at line 37 of file MainWindowWrapper\&.h\&.
.SS "double OP_TESTING_NS::WindowParams::info_ratio"

.PP
Definition at line 38 of file MainWindowWrapper\&.h\&.
.SS "struct \fBOP_TESTING_NS::WindowParams::info_window\fP \fBOP_TESTING_NS::WindowParams::info_window\fP"

.SS "struct \fBOP_TESTING_NS::WindowParams::simu_window\fP \fBOP_TESTING_NS::WindowParams::simu_window\fP"

.SS "std::string OP_TESTING_NS::WindowParams::title"

.PP
Definition at line 39 of file MainWindowWrapper\&.h\&.
.SS "struct \fBOP_TESTING_NS::WindowParams::UI_CONST\fP \fBOP_TESTING_NS::WindowParams::UI_CONST\fP"

.SS "int OP_TESTING_NS::WindowParams::w"

.PP
Definition at line 36 of file MainWindowWrapper\&.h\&.
.SS "int OP_TESTING_NS::WindowParams::x"

.PP
Definition at line 34 of file MainWindowWrapper\&.h\&.
.SS "int OP_TESTING_NS::WindowParams::y"

.PP
Definition at line 35 of file MainWindowWrapper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
