.TH "OtherInf" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OtherInf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HevCnt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBsideAcc\fP"
.br
.ti -1c
.RI "float \fBacc\fP"
.br
.ti -1c
.RI "float \fBangleFromP\fP"
.br
.ti -1c
.RI "float \fBbrkPedalStrFromP\fP"
.br
.ti -1c
.RI "float \fBvelocFrFromP\fP"
.br
.ti -1c
.RI "float \fBvelocFlFromP\fP"
.br
.ti -1c
.RI "float \fBvelocRrFromP\fP"
.br
.ti -1c
.RI "float \fBvelocRlFromP\fP"
.br
.ti -1c
.RI "float \fBvelocFromP2\fP"
.br
.ti -1c
.RI "int \fBdrv_mode\fP"
.br
.ti -1c
.RI "unsigned int \fBdrvPedalStrFromP\fP"
.br
.ti -1c
.RI "int \fBrpm\fP"
.br
.ti -1c
.RI "float \fBvelocFromP\fP"
.br
.ti -1c
.RI "int \fBev_mode\fP"
.br
.ti -1c
.RI "int \fBtemp\fP"
.br
.ti -1c
.RI "int \fBshiftFromPrius\fP"
.br
.ti -1c
.RI "LIGHT_STATE \fBlight\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "DOOR_STATE \fBdoor\fP"
.br
.ti -1c
.RI "bool \fBcluise\fP"
.br
.ti -1c
.RI "char \fBdtcData1\fP"
.br
.ti -1c
.RI "char \fBdtcData2\fP"
.br
.ti -1c
.RI "char \fBdtcData3\fP"
.br
.ti -1c
.RI "char \fBdtcData4\fP"
.br
.ti -1c
.RI "char \fBdtcData5\fP"
.br
.ti -1c
.RI "char \fBdtcData6\fP"
.br
.ti -1c
.RI "char \fBdtcData7\fP"
.br
.ti -1c
.RI "char \fBdtcData8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file HevCnt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float OtherInf::acc"

.PP
Definition at line 45 of file HevCnt\&.h\&.
.SS "float OtherInf::angleFromP"

.PP
Definition at line 46 of file HevCnt\&.h\&.
.SS "float OtherInf::brkPedalStrFromP"

.PP
Definition at line 47 of file HevCnt\&.h\&.
.SS "bool OtherInf::cluise"

.PP
Definition at line 63 of file HevCnt\&.h\&.
.SS "DOOR_STATE OtherInf::door"

.PP
Definition at line 62 of file HevCnt\&.h\&.
.SS "int OtherInf::drv_mode"

.PP
Definition at line 53 of file HevCnt\&.h\&.
.SS "unsigned int OtherInf::drvPedalStrFromP"

.PP
Definition at line 54 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData1"

.PP
Definition at line 64 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData2"

.PP
Definition at line 65 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData3"

.PP
Definition at line 66 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData4"

.PP
Definition at line 67 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData5"

.PP
Definition at line 68 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData6"

.PP
Definition at line 69 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData7"

.PP
Definition at line 70 of file HevCnt\&.h\&.
.SS "char OtherInf::dtcData8"

.PP
Definition at line 71 of file HevCnt\&.h\&.
.SS "int OtherInf::ev_mode"

.PP
Definition at line 57 of file HevCnt\&.h\&.
.SS "int OtherInf::level"

.PP
Definition at line 61 of file HevCnt\&.h\&.
.SS "LIGHT_STATE OtherInf::light"

.PP
Definition at line 60 of file HevCnt\&.h\&.
.SS "int OtherInf::rpm"

.PP
Definition at line 55 of file HevCnt\&.h\&.
.SS "int OtherInf::shiftFromPrius"

.PP
Definition at line 59 of file HevCnt\&.h\&.
.SS "float OtherInf::sideAcc"

.PP
Definition at line 44 of file HevCnt\&.h\&.
.SS "int OtherInf::temp"

.PP
Definition at line 58 of file HevCnt\&.h\&.
.SS "float OtherInf::velocFlFromP"

.PP
Definition at line 49 of file HevCnt\&.h\&.
.SS "float OtherInf::velocFrFromP"

.PP
Definition at line 48 of file HevCnt\&.h\&.
.SS "float OtherInf::velocFromP"

.PP
Definition at line 56 of file HevCnt\&.h\&.
.SS "float OtherInf::velocFromP2"

.PP
Definition at line 52 of file HevCnt\&.h\&.
.SS "float OtherInf::velocRlFromP"

.PP
Definition at line 51 of file HevCnt\&.h\&.
.SS "float OtherInf::velocRrFromP"

.PP
Definition at line 50 of file HevCnt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
