.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/gnss/packages/javad_navsat_driver/lib/libjavad_navsat_driver/parser.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/gnss/packages/javad_navsat_driver/lib/libjavad_navsat_driver/parser.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBlibjavad_navsat_driver\&.parser\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.safe_float\fP (field)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.convert_latitude\fP (field)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.convert_longitude\fP (field)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.convert_time\fP (nmea_utc)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.convert_status_flag\fP (status_flag)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.convert_knots_to_mps\fP (knots)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.convert_deg_to_rads\fP (degs)"
.br
.ti -1c
.RI "def \fBlibjavad_navsat_driver\&.parser\&.parse_nmea_sentence\fP (nmea_sentence)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlibjavad_navsat_driver\&.parser\&.logger\fP = logging\&.getLogger('rosout')"
.br
.ti -1c
.RI "dictionary \fBlibjavad_navsat_driver\&.parser\&.parse_maps\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
