.TH "pcd_xyzrgb_grid" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcd_xyzrgb_grid \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfilename\fP"
.br
.ti -1c
.RI "int \fBgrid_id\fP"
.br
.ti -1c
.RI "int \fBgrid_id_x\fP"
.br
.ti -1c
.RI "int \fBgrid_id_y\fP"
.br
.ti -1c
.RI "int \fBlower_bound_x\fP"
.br
.ti -1c
.RI "int \fBlower_bound_y\fP"
.br
.ti -1c
.RI "int \fBupper_bound_x\fP"
.br
.ti -1c
.RI "int \fBupper_bound_y\fP"
.br
.ti -1c
.RI "\fBpcl::PointCloud\fP< pcl::PointXYZRGB > \fBcloud\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file pcd_grid_divider\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBpcl::PointCloud\fP<pcl::PointXYZRGB> pcd_xyzrgb_grid::cloud"

.PP
Definition at line 63 of file pcd_grid_divider\&.cpp\&.
.SS "std::string pcd_xyzrgb_grid::filename"

.PP
Definition at line 55 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::grid_id"

.PP
Definition at line 56 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::grid_id_x"

.PP
Definition at line 57 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::grid_id_y"

.PP
Definition at line 58 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::lower_bound_x"

.PP
Definition at line 59 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::lower_bound_y"

.PP
Definition at line 60 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::upper_bound_x"

.PP
Definition at line 61 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzrgb_grid::upper_bound_y"

.PP
Definition at line 62 of file pcd_grid_divider\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
