.TH "pcd_xyzi_grid" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcd_xyzi_grid \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfilename\fP"
.br
.ti -1c
.RI "int \fBgrid_id\fP"
.br
.ti -1c
.RI "int \fBgrid_id_x\fP"
.br
.ti -1c
.RI "int \fBgrid_id_y\fP"
.br
.ti -1c
.RI "int \fBlower_bound_x\fP"
.br
.ti -1c
.RI "int \fBlower_bound_y\fP"
.br
.ti -1c
.RI "int \fBupper_bound_x\fP"
.br
.ti -1c
.RI "int \fBupper_bound_y\fP"
.br
.ti -1c
.RI "\fBpcl::PointCloud\fP< pcl::PointXYZI > \fBcloud\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file pcd_grid_divider\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBpcl::PointCloud\fP<pcl::PointXYZI> pcd_xyzi_grid::cloud"

.PP
Definition at line 51 of file pcd_grid_divider\&.cpp\&.
.SS "std::string pcd_xyzi_grid::filename"

.PP
Definition at line 43 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::grid_id"

.PP
Definition at line 44 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::grid_id_x"

.PP
Definition at line 45 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::grid_id_y"

.PP
Definition at line 46 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::lower_bound_x"

.PP
Definition at line 47 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::lower_bound_y"

.PP
Definition at line 48 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::upper_bound_x"

.PP
Definition at line 49 of file pcd_grid_divider\&.cpp\&.
.SS "int pcd_xyzi_grid::upper_bound_y"

.PP
Definition at line 50 of file pcd_grid_divider\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
