.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_apollo_cnn_seg_detect/include/pcl_types.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_apollo_cnn_seg_detect/include/pcl_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pcl/common/time\&.h'\fP
.br
\fC#include 'pcl/common/transforms\&.h'\fP
.br
\fC#include 'pcl/kdtree/kdtree_flann\&.h'\fP
.br
\fC#include 'pcl/point_cloud\&.h'\fP
.br
\fC#include 'pcl/point_types\&.h'\fP
.br
\fC#include 'pcl/search/impl/kdtree\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBapollo::BoundingCube\fP"
.br
.ti -1c
.RI "struct \fBapollo::PointD\fP"
.br
.ti -1c
.RI "struct \fBapollo::PointXYZIH\fP"
.br
.ti -1c
.RI "struct \fBapollo::PointXYZIRT\fP"
.br
.ti -1c
.RI "struct \fBapollo::PointXYZIT\fP"
.br
.ti -1c
.RI "struct \fBapollo::RawPointXYZIT\fP"
.br
.ti -1c
.RI "struct \fBapollo::PointXYZIRTd\fP"
.br
.ti -1c
.RI "struct \fBapollo::PointXYZITd\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBapollo\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef pcl::PointIndices \fBapollo::PointIndices\fP"
.br
.ti -1c
.RI "typedef pcl::PointIndices::Ptr \fBapollo::PointIndicesPtr\fP"
.br
.ti -1c
.RI "typedef pcl::PointXY \fBapollo::Point2d\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< Point2d > \fBapollo::PointCloud2d\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< Point2d >::Ptr \fBapollo::PointCloud2dPtr\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< Point2d >::ConstPtr \fBapollo::PointCloud2dConstPtr\fP"
.br
.ti -1c
.RI "typedef PointXYZIH \fBapollo::Point\fP"
.br
.ti -1c
.RI "typedef pcl::PointCloud< \fBPoint\fP > \fBapollo::PointCloud\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< \fBPoint\fP >::Ptr \fBapollo::PointCloudPtr\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< \fBPoint\fP >::ConstPtr \fBapollo::PointCloudConstPtr\fP"
.br
.ti -1c
.RI "typedef pcl::PointXYZRGB \fBapollo::CPoint\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< CPoint > \fBapollo::CPointCloud\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< CPoint >::Ptr \fBapollo::CPointCloudPtr\fP"
.br
.ti -1c
.RI "typedef \fBpcl::PointCloud\fP< CPoint >::ConstPtr \fBapollo::CPointCloudConstPtr\fP"
.br
.ti -1c
.RI "typedef pcl::KdTreeFLANN< \fBPoint\fP > \fBapollo::KdTree\fP"
.br
.ti -1c
.RI "typedef ::\fBpcl::PointCloud\fP< PointD > \fBapollo::PointDCloud\fP"
.br
.ti -1c
.RI "typedef ::\fBpcl::PointCloud\fP< PointD >::Ptr \fBapollo::PointDCloudPtr\fP"
.br
.ti -1c
.RI "typedef ::\fBpcl::PointCloud\fP< PointD >::ConstPtr \fBapollo::PointDCloudConstPtr\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBapollo::PointD\fP \fBapollo::EIGEN_ALIGN16\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
