.TH "pcl_omp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcl_omp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNormalDistributionsTransform\fP"
.br
.RI "\fIA 3D Normal Distribution Transform registration implementation for point cloud data\&. \fP"
.ti -1c
.RI "class \fBRegistration\fP"
.br
.RI "\fI\fB\fBRegistration\fP\fP represents the base registration class for general purpose, ICP-like methods\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
