.TH "PlannerHNS::RoadNetwork" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::RoadNetwork \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoadNetwork\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBRoadSegment\fP > \fBroadSegments\fP"
.br
.ti -1c
.RI "std::vector< \fBTrafficLight\fP > \fBtrafficLights\fP"
.br
.ti -1c
.RI "std::vector< \fBStopLine\fP > \fBstopLines\fP"
.br
.ti -1c
.RI "std::vector< \fBCurb\fP > \fBcurbs\fP"
.br
.ti -1c
.RI "std::vector< \fBBoundary\fP > \fBboundaries\fP"
.br
.ti -1c
.RI "std::vector< \fBCrossing\fP > \fBcrossings\fP"
.br
.ti -1c
.RI "std::vector< \fBMarking\fP > \fBmarkings\fP"
.br
.ti -1c
.RI "std::vector< \fBTrafficSign\fP > \fBsigns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 798 of file RoadNetwork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBBoundary\fP> PlannerHNS::RoadNetwork::boundaries"

.PP
Definition at line 805 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBCrossing\fP> PlannerHNS::RoadNetwork::crossings"

.PP
Definition at line 806 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBCurb\fP> PlannerHNS::RoadNetwork::curbs"

.PP
Definition at line 804 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBMarking\fP> PlannerHNS::RoadNetwork::markings"

.PP
Definition at line 807 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBRoadSegment\fP> PlannerHNS::RoadNetwork::roadSegments"

.PP
Definition at line 801 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBTrafficSign\fP> PlannerHNS::RoadNetwork::signs"

.PP
Definition at line 808 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBStopLine\fP> PlannerHNS::RoadNetwork::stopLines"

.PP
Definition at line 803 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBTrafficLight\fP> PlannerHNS::RoadNetwork::trafficLights"

.PP
Definition at line 802 of file RoadNetwork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
