.TH "PlannerHNS::TrafficSign" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::TrafficSign \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoadNetwork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrafficSign\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBlaneId\fP"
.br
.ti -1c
.RI "int \fBroadId\fP"
.br
.ti -1c
.RI "\fBGPSPoint\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBTrafficSignTypes\fP \fBsignType\fP"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "double \fBfromValue\fP"
.br
.ti -1c
.RI "double \fBtoValue\fP"
.br
.ti -1c
.RI "std::string \fBstrValue\fP"
.br
.ti -1c
.RI "timespec \fBtimeValue\fP"
.br
.ti -1c
.RI "timespec \fBfromTimeValue\fP"
.br
.ti -1c
.RI "timespec \fBtoTimeValue\fP"
.br
.ti -1c
.RI "\fBLane\fP * \fBpLane\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 630 of file RoadNetwork\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::TrafficSign::TrafficSign ()\fC [inline]\fP"

.PP
Definition at line 649 of file RoadNetwork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "timespec PlannerHNS::TrafficSign::fromTimeValue"

.PP
Definition at line 644 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::TrafficSign::fromValue"

.PP
Definition at line 640 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::TrafficSign::id"

.PP
Definition at line 633 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::TrafficSign::laneId"

.PP
Definition at line 634 of file RoadNetwork\&.h\&.
.SS "\fBLane\fP* PlannerHNS::TrafficSign::pLane"

.PP
Definition at line 647 of file RoadNetwork\&.h\&.
.SS "\fBGPSPoint\fP PlannerHNS::TrafficSign::pos"

.PP
Definition at line 637 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::TrafficSign::roadId"

.PP
Definition at line 635 of file RoadNetwork\&.h\&.
.SS "\fBTrafficSignTypes\fP PlannerHNS::TrafficSign::signType"

.PP
Definition at line 638 of file RoadNetwork\&.h\&.
.SS "std::string PlannerHNS::TrafficSign::strValue"

.PP
Definition at line 642 of file RoadNetwork\&.h\&.
.SS "timespec PlannerHNS::TrafficSign::timeValue"

.PP
Definition at line 643 of file RoadNetwork\&.h\&.
.SS "timespec PlannerHNS::TrafficSign::toTimeValue"

.PP
Definition at line 645 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::TrafficSign::toValue"

.PP
Definition at line 641 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::TrafficSign::value"

.PP
Definition at line 639 of file RoadNetwork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
