.TH "PlannerHNS::WhiteLine" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::WhiteLine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoadNetwork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWhiteLine\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBroadId\fP"
.br
.ti -1c
.RI "std::vector< \fBWayPoint\fP > \fBpoints\fP"
.br
.ti -1c
.RI "\fBWayPoint\fP \fBstartpos\fP"
.br
.ti -1c
.RI "\fBWayPoint\fP \fBendpos\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 486 of file RoadNetwork\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::WhiteLine::WhiteLine ()\fC [inline]\fP"

.PP
Definition at line 497 of file RoadNetwork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWayPoint\fP PlannerHNS::WhiteLine::endpos"

.PP
Definition at line 493 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::WhiteLine::id"

.PP
Definition at line 489 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::WhiteLine::length"

.PP
Definition at line 494 of file RoadNetwork\&.h\&.
.SS "std::vector<\fBWayPoint\fP> PlannerHNS::WhiteLine::points"

.PP
Definition at line 491 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::WhiteLine::roadId"

.PP
Definition at line 490 of file RoadNetwork\&.h\&.
.SS "\fBWayPoint\fP PlannerHNS::WhiteLine::startpos"

.PP
Definition at line 492 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::WhiteLine::type"

.PP
Definition at line 495 of file RoadNetwork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
