.TH "PlannerHNS::PID_CONST" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::PID_CONST \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlannerCommonDef\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPID_CONST\fP ()"
.br
.ti -1c
.RI "\fBPID_CONST\fP (const double &\fBp\fP, const double &\fBi\fP, const double &d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBkP\fP"
.br
.ti -1c
.RI "double \fBkI\fP"
.br
.ti -1c
.RI "double \fBkD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file PlannerCommonDef\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::PID_CONST::PID_CONST ()\fC [inline]\fP"

.PP
Definition at line 42 of file PlannerCommonDef\&.h\&.
.SS "PlannerHNS::PID_CONST::PID_CONST (const double & p, const double & i, const double & d)\fC [inline]\fP"

.PP
Definition at line 47 of file PlannerCommonDef\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlannerHNS::PID_CONST::kD"

.PP
Definition at line 40 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::PID_CONST::kI"

.PP
Definition at line 39 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::PID_CONST::kP"

.PP
Definition at line 38 of file PlannerCommonDef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
