.TH "PlannerHNS::PlanningParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::PlanningParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoadNetwork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlanningParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmaxSpeed\fP"
.br
.ti -1c
.RI "double \fBminSpeed\fP"
.br
.ti -1c
.RI "double \fBplanningDistance\fP"
.br
.ti -1c
.RI "double \fBmicroPlanDistance\fP"
.br
.ti -1c
.RI "double \fBcarTipMargin\fP"
.br
.ti -1c
.RI "double \fBrollInMargin\fP"
.br
.ti -1c
.RI "double \fBrollInSpeedFactor\fP"
.br
.ti -1c
.RI "double \fBpathDensity\fP"
.br
.ti -1c
.RI "double \fBrollOutDensity\fP"
.br
.ti -1c
.RI "int \fBrollOutNumber\fP"
.br
.ti -1c
.RI "double \fBhorizonDistance\fP"
.br
.ti -1c
.RI "double \fBminFollowingDistance\fP"
.br
.ti -1c
.RI "double \fBminDistanceToAvoid\fP"
.br
.ti -1c
.RI "double \fBmaxDistanceToAvoid\fP"
.br
.ti -1c
.RI "double \fBspeedProfileFactor\fP"
.br
.ti -1c
.RI "double \fBsmoothingDataWeight\fP"
.br
.ti -1c
.RI "double \fBsmoothingSmoothWeight\fP"
.br
.ti -1c
.RI "double \fBsmoothingToleranceError\fP"
.br
.ti -1c
.RI "double \fBminStopLineRespondDistance\fP"
.br
.ti -1c
.RI "double \fBstopSignStopTime\fP"
.br
.ti -1c
.RI "double \fBadditionalBrakingDistance\fP"
.br
.ti -1c
.RI "double \fBverticalSafetyDistance\fP"
.br
.ti -1c
.RI "double \fBhorizontalSafetyDistancel\fP"
.br
.ti -1c
.RI "double \fBgiveUpDistance\fP"
.br
.ti -1c
.RI "int \fBnReliableCount\fP"
.br
.ti -1c
.RI "bool \fBenableLaneChange\fP"
.br
.ti -1c
.RI "bool \fBenableSwerving\fP"
.br
.ti -1c
.RI "bool \fBenableFollowing\fP"
.br
.ti -1c
.RI "bool \fBenableHeadingSmoothing\fP"
.br
.ti -1c
.RI "bool \fBenableTrafficLightBehavior\fP"
.br
.ti -1c
.RI "bool \fBenableStopSignBehavior\fP"
.br
.ti -1c
.RI "bool \fBenabTrajectoryVelocities\fP"
.br
.ti -1c
.RI "double \fBminIndicationDistance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 934 of file RoadNetwork\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::PlanningParams::PlanningParams ()\fC [inline]\fP"

.PP
Definition at line 980 of file RoadNetwork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlannerHNS::PlanningParams::additionalBrakingDistance"

.PP
Definition at line 962 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::carTipMargin"

.PP
Definition at line 941 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enableFollowing"

.PP
Definition at line 972 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enableHeadingSmoothing"

.PP
Definition at line 973 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enableLaneChange"

.PP
Definition at line 970 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enableStopSignBehavior"

.PP
Definition at line 975 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enableSwerving"

.PP
Definition at line 971 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enableTrafficLightBehavior"

.PP
Definition at line 974 of file RoadNetwork\&.h\&.
.SS "bool PlannerHNS::PlanningParams::enabTrajectoryVelocities"

.PP
Definition at line 977 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::giveUpDistance"

.PP
Definition at line 966 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::horizonDistance"

.PP
Definition at line 947 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::horizontalSafetyDistancel"

.PP
Definition at line 964 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::maxDistanceToAvoid"

.PP
Definition at line 950 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::maxSpeed"

.PP
Definition at line 937 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::microPlanDistance"

.PP
Definition at line 940 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::minDistanceToAvoid"

.PP
Definition at line 949 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::minFollowingDistance"

.PP
Definition at line 948 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::minIndicationDistance"

.PP
Definition at line 978 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::minSpeed"

.PP
Definition at line 938 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::minStopLineRespondDistance"

.PP
Definition at line 958 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::PlanningParams::nReliableCount"

.PP
Definition at line 968 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::pathDensity"

.PP
Definition at line 944 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::planningDistance"

.PP
Definition at line 939 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::rollInMargin"

.PP
Definition at line 942 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::rollInSpeedFactor"

.PP
Definition at line 943 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::rollOutDensity"

.PP
Definition at line 945 of file RoadNetwork\&.h\&.
.SS "int PlannerHNS::PlanningParams::rollOutNumber"

.PP
Definition at line 946 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::smoothingDataWeight"

.PP
Definition at line 952 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::smoothingSmoothWeight"

.PP
Definition at line 953 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::smoothingToleranceError"

.PP
Definition at line 954 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::speedProfileFactor"

.PP
Definition at line 951 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::stopSignStopTime"

.PP
Definition at line 960 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::PlanningParams::verticalSafetyDistance"

.PP
Definition at line 963 of file RoadNetwork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
