.TH "PlannerHNS::StopSignStopStateII" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::StopSignStopStateII \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BehaviorStateMachine\&.h>\fP
.PP
Inherits \fBPlannerHNS::BehaviorStateMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStopSignStopStateII\fP (\fBPlanningParams\fP *pParams, \fBPreCalculatedConditions\fP *pPreCalcVal, \fBBehaviorStateMachine\fP *pNextState)"
.br
.ti -1c
.RI "virtual \fB~StopSignStopStateII\fP ()"
.br
.ti -1c
.RI "virtual \fBBehaviorStateMachine\fP * \fBGetNextState\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 180 of file BehaviorStateMachine\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::StopSignStopStateII::StopSignStopStateII (\fBPlanningParams\fP * pParams, \fBPreCalculatedConditions\fP * pPreCalcVal, \fBBehaviorStateMachine\fP * pNextState)\fC [inline]\fP"

.PP
Definition at line 183 of file BehaviorStateMachine\&.h\&.
.SS "virtual PlannerHNS::StopSignStopStateII::~StopSignStopStateII ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 185 of file BehaviorStateMachine\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBehaviorStateMachine\fP * PlannerHNS::StopSignStopStateII::GetNextState ()\fC [virtual]\fP"

.PP
Implements \fBPlannerHNS::BehaviorStateMachine\fP\&.
.PP
Definition at line 506 of file BehaviorStateMachine\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
