.TH "PlannerHNS::ControllerParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::ControllerParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlannerCommonDef\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControllerParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBSimulationSteeringDelay\fP"
.br
.ti -1c
.RI "double \fBSteeringDelay\fP"
.br
.ti -1c
.RI "double \fBminPursuiteDistance\fP"
.br
.ti -1c
.RI "\fBPID_CONST\fP \fBSteering_Gain\fP"
.br
.ti -1c
.RI "\fBPID_CONST\fP \fBVelocity_Gain\fP"
.br
.ti -1c
.RI "double \fBAcceleration\fP"
.br
.ti -1c
.RI "double \fBDeceleration\fP"
.br
.ti -1c
.RI "double \fBFollowDistance\fP"
.br
.ti -1c
.RI "double \fBLowpassSteerCutoff\fP"
.br
.ti -1c
.RI "double \fBmaxAccel\fP"
.br
.ti -1c
.RI "double \fBmaxDecel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file PlannerCommonDef\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::ControllerParams::ControllerParams ()\fC [inline]\fP"

.PP
Definition at line 71 of file PlannerCommonDef\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlannerHNS::ControllerParams::Acceleration"

.PP
Definition at line 63 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::Deceleration"

.PP
Definition at line 64 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::FollowDistance"

.PP
Definition at line 65 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::LowpassSteerCutoff"

.PP
Definition at line 66 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::maxAccel"

.PP
Definition at line 67 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::maxDecel"

.PP
Definition at line 68 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::minPursuiteDistance"

.PP
Definition at line 60 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::SimulationSteeringDelay"

.PP
Definition at line 58 of file PlannerCommonDef\&.h\&.
.SS "\fBPID_CONST\fP PlannerHNS::ControllerParams::Steering_Gain"

.PP
Definition at line 61 of file PlannerCommonDef\&.h\&.
.SS "double PlannerHNS::ControllerParams::SteeringDelay"

.PP
Definition at line 59 of file PlannerCommonDef\&.h\&.
.SS "\fBPID_CONST\fP PlannerHNS::ControllerParams::Velocity_Gain"

.PP
Definition at line 62 of file PlannerCommonDef\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
