.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/PlannerCommonDef.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_planner/include/op_planner/PlannerCommonDef.h \- Definition file for control related data types\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerHNS::PID_CONST\fP"
.br
.ti -1c
.RI "class \fBPlannerHNS::ControllerParams\fP"
.br
.ti -1c
.RI "class \fBPlannerHNS::CAR_BASIC_INFO\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlannerHNS\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPlannerHNS::MAP_SOURCE_TYPE\fP { \fBPlannerHNS::MAP_AUTOWARE\fP, \fBPlannerHNS::MAP_FOLDER\fP, \fBPlannerHNS::MAP_KML_FILE\fP, \fBPlannerHNS::MAP_ONE_CSV_FILE\fP, \fBPlannerHNS::MAP_LANES_CSV_FILES\fP }"
.br
.ti -1c
.RI "enum \fBPlannerHNS::CAR_TYPE\fP { \fBPlannerHNS::Mv2Car\fP, \fBPlannerHNS::PHVCar\fP, \fBPlannerHNS::HVCar\fP, \fBPlannerHNS::RoboCar\fP, \fBPlannerHNS::SimulationCar\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition file for control related data types\&. 


.PP
\fBAuthor:\fP
.RS 4
Hatem Darweesh 
.RE
.PP
\fBDate:\fP
.RS 4
Dec 14, 2016 
.RE
.PP

.PP
Definition in file \fBPlannerCommonDef\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
