.TH "PlannerHNS::Mat3" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::Mat3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatrixOperations\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMat3\fP ()"
.br
.ti -1c
.RI "\fBMat3\fP (double transX, double transY, bool mirrorX, bool mirrorY)"
.br
.ti -1c
.RI "\fBMat3\fP (double transX, double transY)"
.br
.ti -1c
.RI "\fBMat3\fP (double rotation_angle)"
.br
.ti -1c
.RI "\fBMat3\fP (\fBGPSPoint\fP rotationCenter)"
.br
.ti -1c
.RI "\fBGPSPoint\fP \fBoperator*\fP (\fBGPSPoint\fP v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file MatrixOperations\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::Mat3::Mat3 ()\fC [inline]\fP"

.PP
Definition at line 23 of file MatrixOperations\&.h\&.
.SS "PlannerHNS::Mat3::Mat3 (double transX, double transY, bool mirrorX, bool mirrorY)\fC [inline]\fP"

.PP
Definition at line 33 of file MatrixOperations\&.h\&.
.SS "PlannerHNS::Mat3::Mat3 (double transX, double transY)\fC [inline]\fP"

.PP
Definition at line 40 of file MatrixOperations\&.h\&.
.SS "PlannerHNS::Mat3::Mat3 (double rotation_angle)\fC [inline]\fP"

.PP
Definition at line 47 of file MatrixOperations\&.h\&.
.SS "PlannerHNS::Mat3::Mat3 (\fBGPSPoint\fP rotationCenter)\fC [inline]\fP"

.PP
Definition at line 56 of file MatrixOperations\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBGPSPoint\fP PlannerHNS::Mat3::operator* (\fBGPSPoint\fP v)\fC [inline]\fP"

.PP
Definition at line 68 of file MatrixOperations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
