.TH "PlannerHNS::PolygonShape" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::PolygonShape \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoadNetwork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBPointInsidePolygon\fP (const \fBPolygonShape\fP &polygon, const \fBGPSPoint\fP &\fBp\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBGPSPoint\fP > \fBpoints\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file RoadNetwork\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int PlannerHNS::PolygonShape::PointInsidePolygon (const \fBPolygonShape\fP & polygon, const \fBGPSPoint\fP & p)\fC [inline]\fP"

.PP
Definition at line 175 of file RoadNetwork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBGPSPoint\fP> PlannerHNS::PolygonShape::points"

.PP
Definition at line 173 of file RoadNetwork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
