.TH "PlannerHNS::ObjParticles::LLP" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::ObjParticles::LLP \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BehaviorPrediction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLLP\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnew_index\fP"
.br
.ti -1c
.RI "double \fBmatch_percent\fP"
.br
.ti -1c
.RI "\fBTrajectoryTracker\fP * \fBpTrack\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 633 of file BehaviorPrediction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::ObjParticles::LLP::LLP ()\fC [inline]\fP"

.PP
Definition at line 640 of file BehaviorPrediction\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlannerHNS::ObjParticles::LLP::match_percent"

.PP
Definition at line 637 of file BehaviorPrediction\&.h\&.
.SS "int PlannerHNS::ObjParticles::LLP::new_index"

.PP
Definition at line 636 of file BehaviorPrediction\&.h\&.
.SS "\fBTrajectoryTracker\fP* PlannerHNS::ObjParticles::LLP::pTrack"

.PP
Definition at line 638 of file BehaviorPrediction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
