.TH "PlannerHNS::AutowarePlanningParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::AutowarePlanningParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <op_ROSHelpers\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutowarePlanningParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmaxSpeed\fP"
.br
.ti -1c
.RI "double \fBminSpeed\fP"
.br
.ti -1c
.RI "double \fBplanningDistance\fP"
.br
.ti -1c
.RI "double \fBmicroPlanDistance\fP"
.br
.ti -1c
.RI "double \fBcarTipMargin\fP"
.br
.ti -1c
.RI "double \fBrollInMargin\fP"
.br
.ti -1c
.RI "double \fBrollInSpeedFactor\fP"
.br
.ti -1c
.RI "double \fBpathDensity\fP"
.br
.ti -1c
.RI "double \fBrollOutDensity\fP"
.br
.ti -1c
.RI "int \fBrollOutNumber\fP"
.br
.ti -1c
.RI "double \fBhorizonDistance\fP"
.br
.ti -1c
.RI "double \fBminFollowingDistance\fP"
.br
.ti -1c
.RI "double \fBmaxFollowingDistance\fP"
.br
.ti -1c
.RI "double \fBminDistanceToAvoid\fP"
.br
.ti -1c
.RI "double \fBspeedProfileFactor\fP"
.br
.ti -1c
.RI "bool \fBenableLaneChange\fP"
.br
.ti -1c
.RI "bool \fBenableSwerving\fP"
.br
.ti -1c
.RI "bool \fBenableFollowing\fP"
.br
.ti -1c
.RI "bool \fBenableHeadingSmoothing\fP"
.br
.ti -1c
.RI "bool \fBenableTrafficLightBehavior\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file op_ROSHelpers\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::AutowarePlanningParams::AutowarePlanningParams ()\fC [inline]\fP"

.PP
Definition at line 144 of file op_ROSHelpers\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlannerHNS::AutowarePlanningParams::carTipMargin"

.PP
Definition at line 126 of file op_ROSHelpers\&.h\&.
.SS "bool PlannerHNS::AutowarePlanningParams::enableFollowing"

.PP
Definition at line 140 of file op_ROSHelpers\&.h\&.
.SS "bool PlannerHNS::AutowarePlanningParams::enableHeadingSmoothing"

.PP
Definition at line 141 of file op_ROSHelpers\&.h\&.
.SS "bool PlannerHNS::AutowarePlanningParams::enableLaneChange"

.PP
Definition at line 138 of file op_ROSHelpers\&.h\&.
.SS "bool PlannerHNS::AutowarePlanningParams::enableSwerving"

.PP
Definition at line 139 of file op_ROSHelpers\&.h\&.
.SS "bool PlannerHNS::AutowarePlanningParams::enableTrafficLightBehavior"

.PP
Definition at line 142 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::horizonDistance"

.PP
Definition at line 132 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::maxFollowingDistance"

.PP
Definition at line 134 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::maxSpeed"

.PP
Definition at line 122 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::microPlanDistance"

.PP
Definition at line 125 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::minDistanceToAvoid"

.PP
Definition at line 135 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::minFollowingDistance"

.PP
Definition at line 133 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::minSpeed"

.PP
Definition at line 123 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::pathDensity"

.PP
Definition at line 129 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::planningDistance"

.PP
Definition at line 124 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::rollInMargin"

.PP
Definition at line 127 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::rollInSpeedFactor"

.PP
Definition at line 128 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::rollOutDensity"

.PP
Definition at line 130 of file op_ROSHelpers\&.h\&.
.SS "int PlannerHNS::AutowarePlanningParams::rollOutNumber"

.PP
Definition at line 131 of file op_ROSHelpers\&.h\&.
.SS "double PlannerHNS::AutowarePlanningParams::speedProfileFactor"

.PP
Definition at line 136 of file op_ROSHelpers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
