.TH "PlannerHNS::Rotation" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlannerHNS::Rotation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RoadNetwork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 362 of file RoadNetwork\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlannerHNS::Rotation::Rotation ()\fC [inline]\fP"

.PP
Definition at line 370 of file RoadNetwork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double PlannerHNS::Rotation::w"

.PP
Definition at line 368 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::Rotation::x"

.PP
Definition at line 365 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::Rotation::y"

.PP
Definition at line 366 of file RoadNetwork\&.h\&.
.SS "double PlannerHNS::Rotation::z"

.PP
Definition at line 367 of file RoadNetwork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
