.TH "/home/deng/Project/autobot-feature-decision/ros/src/data/packages/map_file/nodes/points_map_loader/points_map_loader.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/data/packages/map_file/nodes/points_map_loader/points_map_loader.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <condition_variable>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <geometry_msgs/PoseWithCovarianceStamped\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <std_msgs/Bool\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include 'autoware_msgs/LaneArray\&.h'\fP
.br
\fC#include <map_file/get_file\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 448 of file points_map_loader\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
