.TH "PointPillarsROS" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointPillarsROS \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point_pillars_ros\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPointPillarsROS\fP ()"
.br
.ti -1c
.RI "void \fBcreateROSPubSub\fP ()"
.br
.RI "\fICreate ROS pub/sub obejct\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTestClass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file point_pillars_ros\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PointPillarsROS::PointPillarsROS ()"

.PP
Definition at line 33 of file point_pillars_ros\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void PointPillarsROS::createROSPubSub ()"

.PP
Create ROS pub/sub obejct\&. Create/Initializing ros pub/sub object 
.PP
Definition at line 56 of file point_pillars_ros\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTestClass\fP\fC [friend]\fP"

.PP
Definition at line 45 of file point_pillars_ros\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
