.TH "point_type" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point_type \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ndt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file ndt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double point_type::x"

.PP
Definition at line 184 of file ndt\&.h\&.
.SS "double point_type::y"

.PP
Definition at line 185 of file ndt\&.h\&.
.SS "double point_type::z"

.PP
Definition at line 186 of file ndt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
