.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/Point3D.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/Point3D.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iosfwd>\fP
.br
\fC#include <utility>\fP
.br
\fC#include '\&.\&./BasicDatatypes\&.hpp'\fP
.br
\fC#include '\&.\&./tools/MathToolbox\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdatatypes::Point3D\fP"
.br
.RI "\fIThis class defines a point in the three-dimensional plane\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdatatypes\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBdatatypes::operator<<\fP (std::ostream &os, const Point3D &point)"
.br
.RI "\fIText output for debugging\&. \fP"
.ti -1c
.RI "bool \fBdatatypes::operator==\fP (const Point3D &p1, const Point3D &p2)"
.br
.ti -1c
.RI "bool \fBdatatypes::operator!=\fP (const Point3D &p1, const Point3D &p2)"
.br
.ti -1c
.RI "const Point3D \fBdatatypes::operator+\fP (const Point3D &p1, const Point3D &p2)"
.br
.ti -1c
.RI "const Point3D \fBdatatypes::operator\-\fP (const Point3D &p1, const Point3D &p2)"
.br
.ti -1c
.RI "double \fBdatatypes::operator*\fP (const Point3D &p1, const Point3D &p2)"
.br
.ti -1c
.RI "const Point3D \fBdatatypes::operator*\fP (const Point3D &\fBp\fP, double factor)"
.br
.ti -1c
.RI "const Point3D \fBdatatypes::operator*\fP (double factor, const Point3D &\fBp\fP)"
.br
.ti -1c
.RI "const Point3D \fBdatatypes::operator\-\fP (const Point3D &\fBp\fP)"
.br
.ti -1c
.RI "const Point3D \fBdatatypes::operator/\fP (const Point3D &\fBp\fP, double divisor)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
