.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/filters/packages/points_preprocessor/nodes/points_concat_filter/points_concat_filter.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/filters/packages/points_preprocessor/nodes/points_concat_filter/points_concat_filter.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <message_filters/subscriber\&.h>\fP
.br
\fC#include <message_filters/sync_policies/approximate_time\&.h>\fP
.br
\fC#include <message_filters/synchronizer\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <pcl_ros/point_cloud\&.h>\fP
.br
\fC#include <pcl_ros/transforms\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <tf/tf\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <velodyne_pointcloud/point_types\&.h>\fP
.br
\fC#include <yaml\-cpp/yaml\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPointsConcatFilter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 137 of file points_concat_filter\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
