.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_point_pillars/include/lidar_point_pillars/point_pillars_ros.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_point_pillars/include/lidar_point_pillars/point_pillars_ros.h \- ROS interface for \fBPointPillars\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <pcl/io/pcd_io\&.h>\fP
.br
\fC#include 'lidar_point_pillars/point_pillars\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPointPillarsROS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ROS interface for \fBPointPillars\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Kosuke Murakami 
.RE
.PP
\fBDate:\fP
.RS 4
2019/02/26 
.RE
.PP

.PP
Definition in file \fBpoint_pillars_ros\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
