.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/Polygon2D.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/Polygon2D.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include 'Polygon2D\&.hpp'\fP
.br
\fC#include 'Box2D\&.hpp'\fP
.br
\fC#include 'Circle2D\&.hpp'\fP
.br
\fC#include 'Ellipse2D\&.hpp'\fP
.br
\fC#include 'Line2D\&.hpp'\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdatatypes\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdatatypes::projectOntoAxis\fP (const Point2D &axis, const Polygon2D &polygon, Polygon2D::floatingpoint_type &min, Polygon2D::floatingpoint_type &max)"
.br
.ti -1c
.RI "Polygon2D::floatingpoint_type \fBdatatypes::intervalDistance\fP (const Polygon2D::floatingpoint_type minA, const Polygon2D::floatingpoint_type maxA, const Polygon2D::floatingpoint_type minB, const Polygon2D::floatingpoint_type maxB)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
