.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/dp_planner/include/PolygonGenerator.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/dp_planner/include/PolygonGenerator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'op_planner/RoadNetwork\&.h'\fP
.br
\fC#include 'op_planner/PlanningHelpers\&.h'\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <visualization_msgs/Marker\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <pcl/io/io\&.h>\fP
.br
\fC#include <pcl/io/pcd_io\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerXNS::QuarterView\fP"
.br
.ti -1c
.RI "class \fBPlannerXNS::PolygonGenerator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlannerXNS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQUARTERS_NUMBER\fP   8"
.br
.ti -1c
.RI "#define \fBMIN_POINTS_PER_QUARTER\fP   1"
.br
.ti -1c
.RI "#define \fBMIN_DISTANCE_BETWEEN_CORNERS\fP   0\&.5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MIN_DISTANCE_BETWEEN_CORNERS   0\&.5"

.PP
Definition at line 27 of file PolygonGenerator\&.h\&.
.SS "#define MIN_POINTS_PER_QUARTER   1"

.PP
Definition at line 26 of file PolygonGenerator\&.h\&.
.SS "#define QUARTERS_NUMBER   8"

.PP
Definition at line 25 of file PolygonGenerator\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
