.TH "pose" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pose \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBroll\fP"
.br
.ti -1c
.RI "double \fBpitch\fP"
.br
.ti -1c
.RI "double \fByaw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file approximate_ndt_mapping\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double pose::pitch"

.PP
Definition at line 64 of file approximate_ndt_mapping\&.cpp\&.
.SS "double pose::roll"

.PP
Definition at line 63 of file approximate_ndt_mapping\&.cpp\&.
.SS "double pose::x"

.PP
Definition at line 60 of file approximate_ndt_mapping\&.cpp\&.
.SS "double pose::y"

.PP
Definition at line 61 of file approximate_ndt_mapping\&.cpp\&.
.SS "double pose::yaw"

.PP
Definition at line 65 of file approximate_ndt_mapping\&.cpp\&.
.SS "double pose::z"

.PP
Definition at line 62 of file approximate_ndt_mapping\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
