.TH "postuer_type" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
postuer_type \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ndt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBtheta\fP"
.br
.ti -1c
.RI "double \fBtheta2\fP"
.br
.ti -1c
.RI "double \fBtheta3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 192 of file ndt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double postuer_type::theta"

.PP
Definition at line 197 of file ndt\&.h\&.
.SS "double postuer_type::theta2"

.PP
Definition at line 198 of file ndt\&.h\&.
.SS "double postuer_type::theta3"

.PP
Definition at line 199 of file ndt\&.h\&.
.SS "double postuer_type::x"

.PP
Definition at line 194 of file ndt\&.h\&.
.SS "double postuer_type::y"

.PP
Definition at line 195 of file ndt\&.h\&.
.SS "double postuer_type::z"

.PP
Definition at line 196 of file ndt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
