.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/semantics/packages/object_map/nodes/potential_field/potential_field.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/semantics/packages/object_map/nodes/potential_field/potential_field.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tf/transform_listener\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <geometry_msgs/PointStamped\&.h>\fP
.br
\fC#include <grid_map_msgs/GridMap\&.h>\fP
.br
\fC#include <grid_map_ros/grid_map_ros\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <jsk_recognition_msgs/BoundingBox\&.h>\fP
.br
\fC#include <jsk_recognition_msgs/BoundingBoxArray\&.h>\fP
.br
\fC#include 'autoware_msgs/DetectedObject\&.h'\fP
.br
\fC#include 'autoware_msgs/DetectedObjectArray\&.h'\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <visualization_msgs/Marker\&.h>\fP
.br
\fC#include <visualization_msgs/MarkerArray\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPotentialField\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 333 of file potential_field\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
