.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/runtime_manager/scripts/proc_manager.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/runtime_manager/scripts/proc_manager.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBproc_manager\&.ProcManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBproc_manager\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBproc_manager\&.cap_last_cap\fP ()"
.br
.ti -1c
.RI "def \fBproc_manager\&.drop_capabilities\fP ()"
.br
.ti -1c
.RI "def \fBproc_manager\&.get_cpu_count\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBproc_manager\&.libc\fP = ctypes\&.CDLL('libc\&.so\&.6')"
.br
.ti -1c
.RI "int \fBproc_manager\&.PR_CAPBSET_DROP\fP = 24"
.br
.ti -1c
.RI "string \fBproc_manager\&.SOCK_PATH\fP = '/tmp/autoware_proc_manager'"
.br
.ti -1c
.RI "\fBproc_manager\&.manager\fP = ProcManager()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
