.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_bag_tools/nodes/nmea2kml/ReadNMEASentence.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_bag_tools/nodes/nmea2kml/ReadNMEASentence.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNMEA_PARSER::ReadNMEASentence\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNMEA_PARSER\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNMEA_PARSER::parseStatus\fP { \fBNMEA_PARSER::waitFirstChar\fP = 0, \fBNMEA_PARSER::command\fP, \fBNMEA_PARSER::data\fP, \fBNMEA_PARSER::checkSum1\fP, \fBNMEA_PARSER::checkSum2\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
