.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_rviz_plugins/rosbag_controller/src/core/recorder.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/autoware_rviz_plugins/rosbag_controller/src/core/recorder.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'recorder\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <sys/statvfs\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <set>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include <boost/regex\&.hpp>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <boost/thread/xtime\&.hpp>\fP
.br
\fC#include <boost/date_time/local_time/local_time\&.hpp>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <rosgraph_msgs/Clock\&.h>\fP
.br
\fC#include <topic_tools/shape_shifter\&.h>\fP
.br
\fC#include 'ros/network\&.h'\fP
.br
\fC#include 'ros/xmlrpc_manager\&.h'\fP
.br
\fC#include 'xmlrpcpp/XmlRpc\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrosbag_controller\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBforeach\fP   BOOST_FOREACH"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define foreach   BOOST_FOREACH"

.PP
Definition at line 81 of file recorder\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
