.TH "RectClassScore< _Tp >" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RectClassScore< _Tp > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rect_class_score\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBtoString\fP ()"
.br
.ti -1c
.RI "std::string \fBGetClassString\fP ()"
.br
.ti -1c
.RI "int \fBGetClassInt\fP ()"
.br
.ti -1c
.RI "std::string \fBtoString\fP ()"
.br
.ti -1c
.RI "std::string \fBGetClassString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Tp \fBx\fP"
.br
.ti -1c
.RI "_Tp \fBy\fP"
.br
.ti -1c
.RI "_Tp \fBw\fP"
.br
.ti -1c
.RI "_Tp \fBh\fP"
.br
.ti -1c
.RI "_Tp \fBscore\fP"
.br
.ti -1c
.RI "unsigned int \fBclass_type\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp>
.br
class RectClassScore< _Tp >"

.PP
Definition at line 22 of file rect_class_score\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _Tp> int \fBRectClassScore\fP< _Tp >::GetClassInt ()\fC [inline]\fP"

.PP
Definition at line 123 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> std::string \fBRectClassScore\fP< _Tp >::GetClassString ()\fC [inline]\fP"

.PP
Definition at line 24 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> std::string \fBRectClassScore\fP< _Tp >::GetClassString ()\fC [inline]\fP"

.PP
Definition at line 36 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> std::string \fBRectClassScore\fP< _Tp >::toString ()\fC [inline]\fP"

.PP
Definition at line 16 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> std::string \fBRectClassScore\fP< _Tp >::toString ()\fC [inline]\fP"

.PP
Definition at line 30 of file rect_class_score\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _Tp> unsigned int \fBRectClassScore\fP< _Tp >::class_type"

.PP
Definition at line 27 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> bool \fBRectClassScore\fP< _Tp >::enabled"

.PP
Definition at line 28 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> _Tp \fBRectClassScore\fP< _Tp >::h"

.PP
Definition at line 25 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> _Tp \fBRectClassScore\fP< _Tp >::score"

.PP
Definition at line 26 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> _Tp \fBRectClassScore\fP< _Tp >::w"

.PP
Definition at line 25 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> _Tp \fBRectClassScore\fP< _Tp >::x"

.PP
Definition at line 25 of file rect_class_score\&.h\&.
.SS "template<typename _Tp> _Tp \fBRectClassScore\fP< _Tp >::y"

.PP
Definition at line 25 of file rect_class_score\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
