.TH "regionCandidate" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
regionCandidate \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcv::Point\fP \fBcenter\fP"
.br
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "double \fBcircleLevel\fP"
.br
.ti -1c
.RI "bool \fBisBlacked\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file TrafficLightDetector\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcv::Point\fP regionCandidate::center"

.PP
Definition at line 9 of file TrafficLightDetector\&.cpp\&.
.SS "double regionCandidate::circleLevel"

.PP
Definition at line 11 of file TrafficLightDetector\&.cpp\&.
.SS "int regionCandidate::idx"

.PP
Definition at line 10 of file TrafficLightDetector\&.cpp\&.
.SS "bool regionCandidate::isBlacked"

.PP
Definition at line 12 of file TrafficLightDetector\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
