.TH "replace_msg_time_with_hdr" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
replace_msg_time_with_hdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBrpl_msg_time_with_hdr\fP (inbag, outbag)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBPKG\fP = 'autoware_bag_tools'"
.br
.ti -1c
.RI "\fBparser\fP"
.br
.ti -1c
.RI "\fBmetavar\fP"
.br
.ti -1c
.RI "\fBrequired\fP"
.br
.ti -1c
.RI "\fBTrue\fP"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBargs\fP = parser\&.parse_args()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def replace_msg_time_with_hdr\&.rpl_msg_time_with_hdr ( inbag,  outbag)"

.PP
Definition at line 57 of file replace_msg_time_with_hdr\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "replace_msg_time_with_hdr\&.args = parser\&.parse_args()"

.PP
Definition at line 77 of file replace_msg_time_with_hdr\&.py\&.
.SS "replace_msg_time_with_hdr\&.help"

.PP
Definition at line 75 of file replace_msg_time_with_hdr\&.py\&.
.SS "replace_msg_time_with_hdr\&.metavar"

.PP
Definition at line 75 of file replace_msg_time_with_hdr\&.py\&.
.SS "replace_msg_time_with_hdr\&.parser"
\fBInitial value:\fP
.PP
.nf
1 = argparse\&.ArgumentParser(
2       description='Create a new bagfile from an existing one replacing the message time for the header time\&.')
.fi
.PP
Definition at line 73 of file replace_msg_time_with_hdr\&.py\&.
.SS "string replace_msg_time_with_hdr\&.PKG = 'autoware_bag_tools'"

.PP
Definition at line 48 of file replace_msg_time_with_hdr\&.py\&.
.SS "replace_msg_time_with_hdr\&.required"

.PP
Definition at line 75 of file replace_msg_time_with_hdr\&.py\&.
.SS "replace_msg_time_with_hdr\&.True"

.PP
Definition at line 75 of file replace_msg_time_with_hdr\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
