.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/filters/packages/points_preprocessor/nodes/ring_ground_filter/ring_ground_filter.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/filters/packages/points_preprocessor/nodes/ring_ground_filter/ring_ground_filter.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <pcl_ros/point_cloud\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <velodyne_pointcloud/point_types\&.h>\fP
.br
\fC#include <opencv/cv\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGroundFilter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLabel\fP { \fBGROUND\fP, \fBVERTICAL\fP, \fBUNKNOWN\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLabel\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGROUND \fP\fP
.TP
\fB\fIVERTICAL \fP\fP
.TP
\fB\fIUNKNOWN \fP\fP
.PP
Definition at line 16 of file ring_ground_filter\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 343 of file ring_ground_filter\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
