.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/semantics/packages/road_occupancy_processor/include/road_occupancy_processor/road_occupancy_processor.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/semantics/packages/road_occupancy_processor/include/road_occupancy_processor/road_occupancy_processor.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br
\fC#include <sensor_msgs/point_cloud_conversion\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud\&.h>\fP
.br
\fC#include <sensor_msgs/PointCloud2\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <pcl/PCLPointCloud2\&.h>\fP
.br
\fC#include <pcl_ros/transforms\&.h>\fP
.br
\fC#include <pcl_ros/point_cloud\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <message_filters/subscriber\&.h>\fP
.br
\fC#include <message_filters/synchronizer\&.h>\fP
.br
\fC#include <message_filters/sync_policies/approximate_time\&.h>\fP
.br
\fC#include <grid_map_ros/grid_map_ros\&.hpp>\fP
.br
\fC#include <grid_map_msgs/GridMap\&.h>\fP
.br
\fC#include <grid_map_cv/grid_map_cv\&.hpp>\fP
.br
\fC#include <tf/tf\&.h>\fP
.br
\fC#include <vector_map/vector_map\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <opencv2/calib3d/calib3d\&.hpp>\fP
.br
\fC#include <opencv2/contrib/contrib\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBROSRoadOccupancyProcessorApp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__APP_NAME__\fP   'road_occupancy_processor'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __APP_NAME__   'road_occupancy_processor'"

.PP
Definition at line 63 of file road_occupancy_processor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
