.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/trafficlight_recognizer/nodes/roi_extractor/roi_extractor.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/trafficlight_recognizer/nodes/roi_extractor/roi_extractor.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'roi_extractor\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br
\fC#include <sensor_msgs/Image\&.h>\fP
.br
\fC#include <sensor_msgs/image_encodings\&.h>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include 'Context\&.h'\fP
.br
\fC#include <autoware_msgs/Signals\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 177 of file roi_extractor\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
