.TH "rosbag_controller::RecorderOptions" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rosbag_controller::RecorderOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <recorder\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecorderOptions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtrigger\fP"
.br
.ti -1c
.RI "bool \fBrecord_all\fP"
.br
.ti -1c
.RI "bool \fBregex\fP"
.br
.ti -1c
.RI "bool \fBdo_exclude\fP"
.br
.ti -1c
.RI "bool \fBquiet\fP"
.br
.ti -1c
.RI "bool \fBappend_date\fP"
.br
.ti -1c
.RI "bool \fBsnapshot\fP"
.br
.ti -1c
.RI "bool \fBverbose\fP"
.br
.ti -1c
.RI "rosbag::CompressionType \fBcompression\fP"
.br
.ti -1c
.RI "std::string \fBprefix\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "boost::regex \fBexclude_regex\fP"
.br
.ti -1c
.RI "uint32_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "uint32_t \fBchunk_size\fP"
.br
.ti -1c
.RI "uint32_t \fBlimit\fP"
.br
.ti -1c
.RI "bool \fBsplit\fP"
.br
.ti -1c
.RI "uint64_t \fBmax_size\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_splits\fP"
.br
.ti -1c
.RI "ros::Duration \fBmax_duration\fP"
.br
.ti -1c
.RI "std::string \fBnode\fP"
.br
.ti -1c
.RI "unsigned long long \fBmin_space\fP"
.br
.ti -1c
.RI "std::string \fBmin_space_str\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBtopics\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file recorder\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rosbag_controller::RecorderOptions::RecorderOptions ()"

.PP
Definition at line 110 of file recorder\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool rosbag_controller::RecorderOptions::append_date"

.PP
Definition at line 110 of file recorder\&.h\&.
.SS "uint32_t rosbag_controller::RecorderOptions::buffer_size"

.PP
Definition at line 117 of file recorder\&.h\&.
.SS "uint32_t rosbag_controller::RecorderOptions::chunk_size"

.PP
Definition at line 118 of file recorder\&.h\&.
.SS "rosbag::CompressionType rosbag_controller::RecorderOptions::compression"

.PP
Definition at line 113 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::do_exclude"

.PP
Definition at line 108 of file recorder\&.h\&.
.SS "boost::regex rosbag_controller::RecorderOptions::exclude_regex"

.PP
Definition at line 116 of file recorder\&.h\&.
.SS "uint32_t rosbag_controller::RecorderOptions::limit"

.PP
Definition at line 119 of file recorder\&.h\&.
.SS "ros::Duration rosbag_controller::RecorderOptions::max_duration"

.PP
Definition at line 123 of file recorder\&.h\&.
.SS "uint64_t rosbag_controller::RecorderOptions::max_size"

.PP
Definition at line 121 of file recorder\&.h\&.
.SS "uint32_t rosbag_controller::RecorderOptions::max_splits"

.PP
Definition at line 122 of file recorder\&.h\&.
.SS "unsigned long long rosbag_controller::RecorderOptions::min_space"

.PP
Definition at line 125 of file recorder\&.h\&.
.SS "std::string rosbag_controller::RecorderOptions::min_space_str"

.PP
Definition at line 126 of file recorder\&.h\&.
.SS "std::string rosbag_controller::RecorderOptions::name"

.PP
Definition at line 115 of file recorder\&.h\&.
.SS "std::string rosbag_controller::RecorderOptions::node"

.PP
Definition at line 124 of file recorder\&.h\&.
.SS "std::string rosbag_controller::RecorderOptions::prefix"

.PP
Definition at line 114 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::quiet"

.PP
Definition at line 109 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::record_all"

.PP
Definition at line 106 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::regex"

.PP
Definition at line 107 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::snapshot"

.PP
Definition at line 111 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::split"

.PP
Definition at line 120 of file recorder\&.h\&.
.SS "std::vector<std::string> rosbag_controller::RecorderOptions::topics"

.PP
Definition at line 128 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::trigger"

.PP
Definition at line 105 of file recorder\&.h\&.
.SS "bool rosbag_controller::RecorderOptions::verbose"

.PP
Definition at line 112 of file recorder\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
