.TH "rosbag_data_extract_sample" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rosbag_data_extract_sample \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBimg_loader_1\fP (image_msg)"
.br
.ti -1c
.RI "def \fBcloud_loader\fP (msg)"
.br
.ti -1c
.RI "def \fBsave_pcd\fP (cloud, timestamp, path)"
.br
.ti -1c
.RI "def \fBsave_image\fP (img, timestamp, path, sfx)"
.br
.ti -1c
.RI "def \fBrosbag_data_extract_sample\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsave_path\fP = None"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def rosbag_data_extract_sample\&.cloud_loader ( msg)"

.PP
Definition at line 20 of file rosbag_data_extract_sample\&.py\&.
.SS "def rosbag_data_extract_sample\&.img_loader_1 ( image_msg)"

.PP
Definition at line 14 of file rosbag_data_extract_sample\&.py\&.
.SS "def rosbag_data_extract_sample\&.rosbag_data_extract_sample ()"

.PP
Definition at line 31 of file rosbag_data_extract_sample\&.py\&.
.SS "def rosbag_data_extract_sample\&.save_image ( img,  timestamp,  path,  sfx)"

.PP
Definition at line 28 of file rosbag_data_extract_sample\&.py\&.
.SS "def rosbag_data_extract_sample\&.save_pcd ( cloud,  timestamp,  path)"

.PP
Definition at line 24 of file rosbag_data_extract_sample\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "rosbag_data_extract_sample\&.save_path = None"

.PP
Definition at line 12 of file rosbag_data_extract_sample\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
