.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/dp_planner/include/ROSHelpers.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/dp_planner/include/ROSHelpers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include 'op_planner/RoadNetwork\&.h'\fP
.br
\fC#include 'op_planner/PlannerCommonDef\&.h'\fP
.br
\fC#include 'op_planner/LocalPlannerH\&.h'\fP
.br
\fC#include 'vector_map_msgs/PointArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/LaneArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/NodeArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/StopLineArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/DTLaneArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/LineArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/AreaArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/SignalArray\&.h'\fP
.br
\fC#include 'vector_map_msgs/StopLine\&.h'\fP
.br
\fC#include 'vector_map_msgs/VectorArray\&.h'\fP
.br
\fC#include <geometry_msgs/Vector3Stamped\&.h>\fP
.br
\fC#include <geometry_msgs/PoseWithCovarianceStamped\&.h>\fP
.br
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include <jsk_recognition_msgs/BoundingBox\&.h>\fP
.br
\fC#include <jsk_recognition_msgs/BoundingBoxArray\&.h>\fP
.br
\fC#include <pcl_conversions/pcl_conversions\&.h>\fP
.br
\fC#include <pcl/io/io\&.h>\fP
.br
\fC#include <pcl/io/pcd_io\&.h>\fP
.br
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include 'autoware_msgs/CloudClusterArray\&.h'\fP
.br
\fC#include 'waypoint_follower/libwaypoint_follower\&.h'\fP
.br
\fC#include 'autoware_msgs/LaneArray\&.h'\fP
.br
\fC#include <visualization_msgs/MarkerArray\&.h>\fP
.br
\fC#include <tf/transform_broadcaster\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <tf/tf\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlannerXNS::AutowareRoadNetwork\fP"
.br
.ti -1c
.RI "class \fBPlannerXNS::AutowareBehaviorState\fP"
.br
.ti -1c
.RI "class \fBPlannerXNS::AutowareVehicleState\fP"
.br
.ti -1c
.RI "class \fBPlannerXNS::AutowarePlanningParams\fP"
.br
.ti -1c
.RI "class \fBPlannerXNS::ROSHelpers\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPlannerXNS\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPlannerXNS::AUTOWARE_STATE_TYPE\fP { \fBPlannerXNS::AW_INITIAL_STATE\fP, \fBPlannerXNS::AW_WAITING_STATE\fP, \fBPlannerXNS::AW_FORWARD_STATE\fP, \fBPlannerXNS::AW_STOPPING_STATE\fP, \fBPlannerXNS::AW_EMERGENCY_STATE\fP, \fBPlannerXNS::AW_TRAFFIC_LIGHT_STOP_STATE\fP, \fBPlannerXNS::AW_STOP_SIGN_STOP_STATE\fP, \fBPlannerXNS::AW_FOLLOW_STATE\fP, \fBPlannerXNS::AW_LANE_CHANGE_STATE\fP, \fBPlannerXNS::AW_OBSTACLE_AVOIDANCE_STATE\fP, \fBPlannerXNS::AW_FINISH_STATE\fP }"
.br
.ti -1c
.RI "enum \fBPlannerXNS::AUTOWARE_LIGHT_INDICATOR\fP { \fBPlannerXNS::AW_INDICATOR_LEFT\fP, \fBPlannerXNS::AW_INDICATOR_RIGHT\fP, \fBPlannerXNS::AW_INDICATOR_BOTH\fP, \fBPlannerXNS::AW_INDICATOR_NONE\fP }"
.br
.ti -1c
.RI "enum \fBPlannerXNS::AUTOWARE_SHIFT_POS\fP { \fBPlannerXNS::AW_SHIFT_POS_PP\fP = 0x60, \fBPlannerXNS::AW_SHIFT_POS_RR\fP = 0x40, \fBPlannerXNS::AW_SHIFT_POS_NN\fP = 0x20, \fBPlannerXNS::AW_SHIFT_POS_DD\fP = 0x10, \fBPlannerXNS::AW_SHIFT_POS_BB\fP = 0xA0, \fBPlannerXNS::AW_SHIFT_POS_SS\fP = 0x0f, \fBPlannerXNS::AW_SHIFT_POS_UU\fP = 0xff }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
