.TH "ROSImageRotatorApp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ROSImageRotatorApp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRun\fP ()"
.br
.ti -1c
.RI "\fB~ROSImageRotatorApp\fP ()"
.br
.ti -1c
.RI "\fBROSImageRotatorApp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file image_rotator_node\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ROSImageRotatorApp::~ROSImageRotatorApp ()\fC [inline]\fP"

.PP
Definition at line 127 of file image_rotator_node\&.cpp\&.
.SS "ROSImageRotatorApp::ROSImageRotatorApp ()\fC [inline]\fP"

.PP
Definition at line 131 of file image_rotator_node\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ROSImageRotatorApp::Run ()\fC [inline]\fP"

.PP
Definition at line 87 of file image_rotator_node\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
