.TH "runtime_manager_dialog.MyDialogDPM" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runtime_manager_dialog.MyDialogDPM \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrtmgr\&.MyDialogDPM\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, args, kwds)"
.br
.ti -1c
.RI "def \fBOnOk\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnLink\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnCancel\fP (self, event)"
.br
.ti -1c
.RI "def \fBOnClose\fP (self, event)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpdic_bak\fP"
.br
.ti -1c
.RI "\fBframe\fP"
.br
.ti -1c
.RI "\fBpanel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2553 of file runtime_manager_dialog\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def runtime_manager_dialog\&.MyDialogDPM\&.__init__ ( self,  args,  kwds)"

.PP
Definition at line 2554 of file runtime_manager_dialog\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def runtime_manager_dialog\&.MyDialogDPM\&.OnCancel ( self,  event)"

.PP
Definition at line 2593 of file runtime_manager_dialog\&.py\&.
.SS "def runtime_manager_dialog\&.MyDialogDPM\&.OnClose ( self,  event)"

.PP
Definition at line 2599 of file runtime_manager_dialog\&.py\&.
.SS "def runtime_manager_dialog\&.MyDialogDPM\&.OnLink ( self,  event)"

.PP
Definition at line 2585 of file runtime_manager_dialog\&.py\&.
.SS "def runtime_manager_dialog\&.MyDialogDPM\&.OnOk ( self,  event)"

.PP
Definition at line 2580 of file runtime_manager_dialog\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "runtime_manager_dialog\&.MyDialogDPM\&.frame"

.PP
Definition at line 2566 of file runtime_manager_dialog\&.py\&.
.SS "runtime_manager_dialog\&.MyDialogDPM\&.panel"

.PP
Definition at line 2567 of file runtime_manager_dialog\&.py\&.
.SS "runtime_manager_dialog\&.MyDialogDPM\&.pdic_bak"

.PP
Definition at line 2556 of file runtime_manager_dialog\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
