.TH "runtime_manager_dialog.ColorLabel" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runtime_manager_dialog.ColorLabel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Panel\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent, \fBlst\fP=[], pos=wx\&.DefaultPosition, size=wx\&.DefaultSize, style=0)"
.br
.ti -1c
.RI "def \fBset\fP (self, \fBlst\fP)"
.br
.ti -1c
.RI "def \fBOnPaint\fP (self, event)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2824 of file runtime_manager_dialog\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def runtime_manager_dialog\&.ColorLabel\&.__init__ ( self,  parent,  lst = \fC[]\fP,  pos = \fCwx\&.DefaultPosition\fP,  size = \fCwx\&.DefaultSize\fP,  style = \fC0\fP)"

.PP
Definition at line 2825 of file runtime_manager_dialog\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def runtime_manager_dialog\&.ColorLabel\&.OnPaint ( self,  event)"

.PP
Definition at line 2834 of file runtime_manager_dialog\&.py\&.
.SS "def runtime_manager_dialog\&.ColorLabel\&.set ( self,  lst)"

.PP
Definition at line 2830 of file runtime_manager_dialog\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "runtime_manager_dialog\&.ColorLabel\&.lst"

.PP
Definition at line 2827 of file runtime_manager_dialog\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
