.TH "runtime_manager_dialog.MyApp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runtime_manager_dialog.MyApp \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits App\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBOnInit\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2863 of file runtime_manager_dialog\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def runtime_manager_dialog\&.MyApp\&.OnInit ( self)"

.PP
Definition at line 2864 of file runtime_manager_dialog\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
