.TH "SavePCD" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SavePCD \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <get_PCD\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave_pcd\fP (const sensor_msgs::PointCloud2::ConstPtr &msg)"
.br
.ti -1c
.RI "void \fBsub_pcd\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBsave_pcd\fP (const sensor_msgs::PointCloud2::ConstPtr &msg)"
.br
.ti -1c
.RI "void \fBsub_pcd\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBsave_path_\fP"
.br
.ti -1c
.RI "string \fBtopic_name_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file get_PCD\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SavePCD::save_pcd (const sensor_msgs::PointCloud2::ConstPtr & msg)"

.PP
Definition at line 12 of file get_PCD\&.cpp\&.
.SS "void SavePCD::save_pcd (const sensor_msgs::PointCloud2::ConstPtr & msg)"

.SS "void SavePCD::sub_pcd (int argc, char * argv[])"

.SS "void SavePCD::sub_pcd (int argc, char * argv[])"

.PP
Definition at line 22 of file get_PCD\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "string SavePCD::save_path_"

.PP
Definition at line 20 of file get_PCD\&.hpp\&.
.SS "string SavePCD::topic_name_"

.PP
Definition at line 21 of file get_PCD\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
