.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/ScanPoint.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/datatypes/ScanPoint.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include '\&.\&./BasicDatatypes\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdatatypes::ScanPoint\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdatatypes\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBdatatypes::operator<<\fP (std::ostream &os, const ScanPoint &point)"
.br
.RI "\fIText output for debugging\&. \fP"
.ti -1c
.RI "bool \fBdatatypes::operator==\fP (const ScanPoint &p1, const ScanPoint &p2)"
.br
.RI "\fIEquality predicate\&. \fP"
.ti -1c
.RI "bool \fBdatatypes::operator!=\fP (const ScanPoint &p1, const ScanPoint &p2)"
.br
.RI "\fIInequality predicate\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
