.TH "section" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
section \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBtype\fP"
.br
.ti -1c
.RI "\fBlist\fP * \fBoptions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file parser\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBlist\fP* section::options"

.PP
Definition at line 41 of file parser\&.c\&.
.SS "char* section::type"

.PP
Definition at line 40 of file parser\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
