.TH "server" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetargs\fP ()"
.br
.ti -1c
.RI "def \fBstatus\fP ()"
.br
.ti -1c
.RI "def \fBupload\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBargs\fP = None"
.br
.ti -1c
.RI "\fBapp\fP = Flask(__name__)"
.br
.ti -1c
.RI "\fBlogger\fP = \fBcommon\&.genlogger\fP()"
.br
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBip\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def server\&.getargs ()"

.PP
Definition at line 12 of file server\&.py\&.
.SS "def server\&.status ()"

.PP
Definition at line 24 of file server\&.py\&.
.SS "def server\&.upload ()"

.PP
Definition at line 29 of file server\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "server\&.app = Flask(__name__)"

.PP
Definition at line 9 of file server\&.py\&.
.SS "server\&.args = None"

.PP
Definition at line 8 of file server\&.py\&.
.SS "server\&.host"

.PP
Definition at line 49 of file server\&.py\&.
.SS "server\&.ip"

.PP
Definition at line 49 of file server\&.py\&.
.SS "server\&.logger = \fBcommon\&.genlogger\fP()"

.PP
Definition at line 10 of file server\&.py\&.
.SS "server\&.port"

.PP
Definition at line 49 of file server\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
