.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/object_filter/packages/lidar_shape_estimation/src/shape_estimator.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/object_filter/packages/lidar_shape_estimation/src/shape_estimator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lidar_shape_estimation/shape_estimator\&.hpp'\fP
.br
\fC#include 'lidar_shape_estimation/model_interface\&.hpp'\fP
.br
\fC#include 'model/bounding_box\&.hpp'\fP
.br
\fC#include 'model/convex_hull\&.hpp'\fP
.br
\fC#include 'model/cylinder\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
