.TH "ShapeEstimationTestClass" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShapeEstimationTestClass \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapeEstimationTestClass\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShapeEstimator\fP \fBshape_estimator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file test_lidar_shape_estimation\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShapeEstimationTestClass::ShapeEstimationTestClass ()\fC [inline]\fP"

.PP
Definition at line 43 of file test_lidar_shape_estimation\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBShapeEstimator\fP ShapeEstimationTestClass::shape_estimator"

.PP
Definition at line 43 of file test_lidar_shape_estimation\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
