.TH "ShapeEstimator" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShapeEstimator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shape_estimator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapeEstimator\fP ()"
.br
.ti -1c
.RI "\fB~ShapeEstimator\fP ()"
.br
.ti -1c
.RI "bool \fBgetShapeAndPose\fP (const std::string &label, const \fBpcl::PointCloud\fP< pcl::PointXYZ > &cluster, autoware_msgs::DetectedObject &output)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file shape_estimator\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShapeEstimator::ShapeEstimator ()"

.PP
Definition at line 28 of file shape_estimator\&.cpp\&.
.SS "ShapeEstimator::~ShapeEstimator ()\fC [inline]\fP"

.PP
Definition at line 33 of file shape_estimator\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ShapeEstimator::getShapeAndPose (const std::string & label, const \fBpcl::PointCloud\fP< pcl::PointXYZ > & cluster, autoware_msgs::DetectedObject & output)"

.PP
Definition at line 32 of file shape_estimator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
