.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/lms5xx/nodes/lms511/include/lms511/SickMessage.hh" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/lms5xx/nodes/lms511/include/lms511/SickMessage.hh \- Defines the abstract parent class for all Sick messages\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSickToolbox::SickMessage< MSG_HEADER_LENGTH, MSG_PAYLOAD_MAX_LENGTH, MSG_TRAILER_LENGTH >\fP"
.br
.RI "\fIProvides an abstract parent for all Sick messages\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSickToolbox\fP"
.br
.RI "\fIEncapsulates the Sick LIDAR Matlab/C++ toolbox\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines the abstract parent class for all Sick messages\&. 

Code by Jason C\&. Derenick and Thomas H\&. Miller\&. Contact derenick(at)lehigh(dot)edu
.PP
The Sick LIDAR Matlab/C++ Toolbox Copyright (c) 2008, Jason C\&. Derenick and Thomas H\&. Miller All rights reserved\&.
.PP
This software is released under a BSD Open-Source License\&. See http://sicktoolbox.sourceforge.net 
.PP
Definition in file \fBSickMessage\&.hh\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
