.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/lms5xx/nodes/lms511/include/lms511/SickConfig.hh" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/lms5xx/nodes/lms511/include/lms511/SickConfig.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_ARPA_INET_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FCNTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETTIMEOFDAY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LINUX_SERIAL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NETINET_IN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PTHREAD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SELECT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SOCKET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDBOOL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_IOCTL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_SELECT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_SOCKET_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TIME_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TERMIOS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__BOOL\fP   1"
.br
.ti -1c
.RI "#define \fBLT_OBJDIR\fP   '\&.libs/'"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'sicktoolbox'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'jasonder@seas\&.upenn\&.edu'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'SickToolbox'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'SickToolbox 1\&.1'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'sicktoolbox'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '1\&.1'"
.br
.ti -1c
.RI "#define \fBRETSIGTYPE\fP   void"
.br
.ti -1c
.RI "#define \fBSELECT_TYPE_ARG1\fP   int"
.br
.ti -1c
.RI "#define \fBSELECT_TYPE_ARG234\fP   (fd_set *)"
.br
.ti -1c
.RI "#define \fBSELECT_TYPE_ARG5\fP   (struct timeval *)"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBTIME_WITH_SYS_TIME\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '1\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE__BOOL   1"

.PP
Definition at line 89 of file SickConfig\&.hh\&.
.SS "#define HAVE_ARPA_INET_H   1"

.PP
Definition at line 8 of file SickConfig\&.hh\&.
.SS "#define HAVE_DLFCN_H   1"

.PP
Definition at line 11 of file SickConfig\&.hh\&.
.SS "#define HAVE_FCNTL_H   1"

.PP
Definition at line 14 of file SickConfig\&.hh\&.
.SS "#define HAVE_GETTIMEOFDAY   1"

.PP
Definition at line 17 of file SickConfig\&.hh\&.
.SS "#define HAVE_INTTYPES_H   1"

.PP
Definition at line 23 of file SickConfig\&.hh\&.
.SS "#define HAVE_LINUX_SERIAL_H   1"

.PP
Definition at line 26 of file SickConfig\&.hh\&.
.SS "#define HAVE_MEMORY_H   1"

.PP
Definition at line 29 of file SickConfig\&.hh\&.
.SS "#define HAVE_MEMSET   1"

.PP
Definition at line 32 of file SickConfig\&.hh\&.
.SS "#define HAVE_NETINET_IN_H   1"

.PP
Definition at line 35 of file SickConfig\&.hh\&.
.SS "#define HAVE_PTHREAD   1"

.PP
Definition at line 38 of file SickConfig\&.hh\&.
.SS "#define HAVE_SELECT   1"

.PP
Definition at line 41 of file SickConfig\&.hh\&.
.SS "#define HAVE_SOCKET   1"

.PP
Definition at line 44 of file SickConfig\&.hh\&.
.SS "#define HAVE_STDBOOL_H   1"

.PP
Definition at line 47 of file SickConfig\&.hh\&.
.SS "#define HAVE_STDINT_H   1"

.PP
Definition at line 50 of file SickConfig\&.hh\&.
.SS "#define HAVE_STDLIB_H   1"

.PP
Definition at line 53 of file SickConfig\&.hh\&.
.SS "#define HAVE_STRCASECMP   1"

.PP
Definition at line 56 of file SickConfig\&.hh\&.
.SS "#define HAVE_STRING_H   1"

.PP
Definition at line 62 of file SickConfig\&.hh\&.
.SS "#define HAVE_STRINGS_H   1"

.PP
Definition at line 59 of file SickConfig\&.hh\&.
.SS "#define HAVE_SYS_IOCTL_H   1"

.PP
Definition at line 65 of file SickConfig\&.hh\&.
.SS "#define HAVE_SYS_SELECT_H   1"

.PP
Definition at line 68 of file SickConfig\&.hh\&.
.SS "#define HAVE_SYS_SOCKET_H   1"

.PP
Definition at line 71 of file SickConfig\&.hh\&.
.SS "#define HAVE_SYS_STAT_H   1"

.PP
Definition at line 74 of file SickConfig\&.hh\&.
.SS "#define HAVE_SYS_TIME_H   1"

.PP
Definition at line 77 of file SickConfig\&.hh\&.
.SS "#define HAVE_SYS_TYPES_H   1"

.PP
Definition at line 80 of file SickConfig\&.hh\&.
.SS "#define HAVE_TERMIOS_H   1"

.PP
Definition at line 83 of file SickConfig\&.hh\&.
.SS "#define HAVE_UNISTD_H   1"

.PP
Definition at line 86 of file SickConfig\&.hh\&.
.SS "#define LT_OBJDIR   '\&.libs/'"

.PP
Definition at line 93 of file SickConfig\&.hh\&.
.SS "#define PACKAGE   'sicktoolbox'"

.PP
Definition at line 96 of file SickConfig\&.hh\&.
.SS "#define PACKAGE_BUGREPORT   'jasonder@seas\&.upenn\&.edu'"

.PP
Definition at line 99 of file SickConfig\&.hh\&.
.SS "#define PACKAGE_NAME   'SickToolbox'"

.PP
Definition at line 102 of file SickConfig\&.hh\&.
.SS "#define PACKAGE_STRING   'SickToolbox 1\&.1'"

.PP
Definition at line 105 of file SickConfig\&.hh\&.
.SS "#define PACKAGE_TARNAME   'sicktoolbox'"

.PP
Definition at line 108 of file SickConfig\&.hh\&.
.SS "#define PACKAGE_URL   ''"

.PP
Definition at line 111 of file SickConfig\&.hh\&.
.SS "#define PACKAGE_VERSION   '1\&.1'"

.PP
Definition at line 114 of file SickConfig\&.hh\&.
.SS "#define RETSIGTYPE   void"

.PP
Definition at line 121 of file SickConfig\&.hh\&.
.SS "#define SELECT_TYPE_ARG1   int"

.PP
Definition at line 124 of file SickConfig\&.hh\&.
.SS "#define SELECT_TYPE_ARG234   (fd_set *)"

.PP
Definition at line 127 of file SickConfig\&.hh\&.
.SS "#define SELECT_TYPE_ARG5   (struct timeval *)"

.PP
Definition at line 130 of file SickConfig\&.hh\&.
.SS "#define STDC_HEADERS   1"

.PP
Definition at line 133 of file SickConfig\&.hh\&.
.SS "#define TIME_WITH_SYS_TIME   1"

.PP
Definition at line 136 of file SickConfig\&.hh\&.
.SS "#define VERSION   '1\&.1'"

.PP
Definition at line 139 of file SickConfig\&.hh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
