.TH "SickToolbox::SickThreadException" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SickToolbox::SickThreadException \- Thrown when error occurs during thread initialization, and uninitialization\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SickException\&.hh>\fP
.PP
Inherits \fBSickToolbox::SickException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSickThreadException\fP ()"
.br
.RI "\fIA constructor\&. \fP"
.ti -1c
.RI "\fBSickThreadException\fP (const std::string detailed_str)"
.br
.RI "\fIAnother constructor\&. \fP"
.ti -1c
.RI "\fB~SickThreadException\fP ()  throw ()"
.br
.RI "\fIA destructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Thrown when error occurs during thread initialization, and uninitialization\&. 
.PP
Definition at line 161 of file SickException\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SickToolbox::SickThreadException::SickThreadException ()\fC [inline]\fP"

.PP
A constructor\&. 
.PP
Definition at line 168 of file SickException\&.hh\&.
.SS "SickToolbox::SickThreadException::SickThreadException (const std::string detailed_str)\fC [inline]\fP"

.PP
Another constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdetailed_str\fP A more detailed description 
.RE
.PP

.PP
Definition at line 175 of file SickException\&.hh\&.
.SS "SickToolbox::SickThreadException::~SickThreadException ()\fC [inline]\fP"

.PP
A destructor\&. 
.PP
Definition at line 181 of file SickException\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
