.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/lms5xx/nodes/lms511/include/lms511/SickLMS5xxMessage.hh" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/lms5xx/nodes/lms511/include/lms511/SickLMS5xxMessage.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include 'SickMessage\&.hh'\fP
.br
\fC#include 'SickException\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSickToolbox::SickLMS5xxMessage\fP"
.br
.RI "\fIA class to represent all messages sent to and from the Sick LMS 5xx unit\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSickToolbox\fP"
.br
.RI "\fIEncapsulates the Sick LIDAR Matlab/C++ toolbox\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSICK_LMS_5xx_MSG_HEADER_LEN\fP   (1)"
.br
.RI "\fISick LMS 5xx message header length in bytes\&. \fP"
.ti -1c
.RI "#define \fBSICK_LMS_5xx_MSG_PAYLOAD_MAX_LEN\fP   (30000)"
.br
.RI "\fISick LMS 5xx maximum payload length\&. \fP"
.ti -1c
.RI "#define \fBSICK_LMS_5xx_MSG_TRAILER_LEN\fP   (1)"
.br
.RI "\fISick LMS 5xx length of the message trailer\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SICK_LMS_5xx_MSG_HEADER_LEN   (1)"

.PP
Sick LMS 5xx message header length in bytes\&. 
.PP
Definition at line 20 of file SickLMS5xxMessage\&.hh\&.
.SS "#define SICK_LMS_5xx_MSG_PAYLOAD_MAX_LEN   (30000)"

.PP
Sick LMS 5xx maximum payload length\&. 
.PP
Definition at line 21 of file SickLMS5xxMessage\&.hh\&.
.SS "#define SICK_LMS_5xx_MSG_TRAILER_LEN   (1)"

.PP
Sick LMS 5xx length of the message trailer\&. 
.PP
Definition at line 22 of file SickLMS5xxMessage\&.hh\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
