.TH "SickToolbox::SickConfigException" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SickToolbox::SickConfigException \- Thrown when the driver detects (or the Sick reports) an invalid config\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SickException\&.hh>\fP
.PP
Inherits \fBSickToolbox::SickException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSickConfigException\fP ()"
.br
.RI "\fIA constructor\&. \fP"
.ti -1c
.RI "\fBSickConfigException\fP (const std::string detailed_str)"
.br
.RI "\fIAnother constructor\&. \fP"
.ti -1c
.RI "\fB~SickConfigException\fP ()  throw ()"
.br
.RI "\fIA destructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Thrown when the driver detects (or the Sick reports) an invalid config\&. 
.PP
Definition at line 190 of file SickException\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SickToolbox::SickConfigException::SickConfigException ()\fC [inline]\fP"

.PP
A constructor\&. 
.PP
Definition at line 197 of file SickException\&.hh\&.
.SS "SickToolbox::SickConfigException::SickConfigException (const std::string detailed_str)\fC [inline]\fP"

.PP
Another constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdetailed_str\fP A more detailed description 
.RE
.PP

.PP
Definition at line 204 of file SickException\&.hh\&.
.SS "SickToolbox::SickConfigException::~SickConfigException ()\fC [inline]\fP"

.PP
A destructor\&. 
.PP
Definition at line 210 of file SickException\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
