.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_msgs/include/sick_ldmrs_msgs/sick_ldmrs_point_type.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_msgs/include/sick_ldmrs_msgs/sick_ldmrs_point_type.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pcl/point_types\&.h>\fP
.br
\fC#include <pcl/point_cloud\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsick_ldmrs_msgs::SICK_LDMRS_Point\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsick_ldmrs_msgs\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPCL_NO_PRECOMPILE\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsick_ldmrs_msgs::Flags\fP { \fBsick_ldmrs_msgs::FlagTransparent\fP = 0x01, \fBsick_ldmrs_msgs::FlagClutter\fP = 0x02, \fBsick_ldmrs_msgs::FlagGround\fP = 0x04, \fBsick_ldmrs_msgs::FlagDirt\fP = 0x08 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBsick_ldmrs_msgs::SICK_LDMRS_Point\fP \fBsick_ldmrs_msgs::EIGEN_ALIGN16\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PCL_NO_PRECOMPILE"

.PP
Definition at line 1 of file sick_ldmrs_point_type\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
