.TH "SignsSimulatorNS::SignsCommandParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignsSimulatorNS::SignsCommandParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <op_signs_simulator_core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCommandParams\fP (const std::string &firstSet, const std::string &secondSet)"
.br
.ti -1c
.RI "\fBSignsCommandParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< int > \fBfirstSignsIds\fP"
.br
.ti -1c
.RI "std::vector< int > \fBsecondSignsIds\fP"
.br
.ti -1c
.RI "double \fBfirstGreenTime\fP"
.br
.ti -1c
.RI "double \fBsecondGreenTime\fP"
.br
.ti -1c
.RI "double \fBfirstyellowTime\fP"
.br
.ti -1c
.RI "double \fBsecondyellowTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file op_signs_simulator_core\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SignsSimulatorNS::SignsCommandParams::SignsCommandParams ()\fC [inline]\fP"

.PP
Definition at line 89 of file op_signs_simulator_core\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void SignsSimulatorNS::SignsCommandParams::SetCommandParams (const std::string & firstSet, const std::string & secondSet)\fC [inline]\fP"

.PP
Definition at line 69 of file op_signs_simulator_core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double SignsSimulatorNS::SignsCommandParams::firstGreenTime"

.PP
Definition at line 64 of file op_signs_simulator_core\&.h\&.
.SS "std::vector<int> SignsSimulatorNS::SignsCommandParams::firstSignsIds"

.PP
Definition at line 62 of file op_signs_simulator_core\&.h\&.
.SS "double SignsSimulatorNS::SignsCommandParams::firstyellowTime"

.PP
Definition at line 66 of file op_signs_simulator_core\&.h\&.
.SS "double SignsSimulatorNS::SignsCommandParams::secondGreenTime"

.PP
Definition at line 65 of file op_signs_simulator_core\&.h\&.
.SS "std::vector<int> SignsSimulatorNS::SignsCommandParams::secondSignsIds"

.PP
Definition at line 63 of file op_signs_simulator_core\&.h\&.
.SS "double SignsSimulatorNS::SignsCommandParams::secondyellowTime"

.PP
Definition at line 67 of file op_signs_simulator_core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
