.TH "SimulationNS::ControllerParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimulationNS::ControllerParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommonSimuDefinitions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBControllerParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBSimulationSteeringDelay\fP"
.br
.ti -1c
.RI "double \fBSteeringDelay\fP"
.br
.ti -1c
.RI "double \fBminPursuiteDistance\fP"
.br
.ti -1c
.RI "\fBPID_CONST\fP \fBSteering_Gain\fP"
.br
.ti -1c
.RI "\fBPID_CONST\fP \fBVelocity_Gain\fP"
.br
.ti -1c
.RI "double \fBAcceleration\fP"
.br
.ti -1c
.RI "double \fBDeceleration\fP"
.br
.ti -1c
.RI "double \fBFollowDistance\fP"
.br
.ti -1c
.RI "double \fBLowpassSteerCutoff\fP"
.br
.ti -1c
.RI "double \fBmaxAccel\fP"
.br
.ti -1c
.RI "double \fBmaxDecel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file CommonSimuDefinitions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SimulationNS::ControllerParams::ControllerParams ()\fC [inline]\fP"

.PP
Definition at line 62 of file CommonSimuDefinitions\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double SimulationNS::ControllerParams::Acceleration"

.PP
Definition at line 54 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::Deceleration"

.PP
Definition at line 55 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::FollowDistance"

.PP
Definition at line 56 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::LowpassSteerCutoff"

.PP
Definition at line 57 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::maxAccel"

.PP
Definition at line 58 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::maxDecel"

.PP
Definition at line 59 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::minPursuiteDistance"

.PP
Definition at line 51 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::SimulationSteeringDelay"

.PP
Definition at line 49 of file CommonSimuDefinitions\&.h\&.
.SS "\fBPID_CONST\fP SimulationNS::ControllerParams::Steering_Gain"

.PP
Definition at line 52 of file CommonSimuDefinitions\&.h\&.
.SS "double SimulationNS::ControllerParams::SteeringDelay"

.PP
Definition at line 50 of file CommonSimuDefinitions\&.h\&.
.SS "\fBPID_CONST\fP SimulationNS::ControllerParams::Velocity_Gain"

.PP
Definition at line 53 of file CommonSimuDefinitions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
