.TH "SimulationNS" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimulationNS \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCAR_BASIC_INFO\fP"
.br
.ti -1c
.RI "class \fBControllerParams\fP"
.br
.ti -1c
.RI "class \fBCostRecordSet\fP"
.br
.ti -1c
.RI "class \fBInterestCircle\fP"
.br
.ti -1c
.RI "struct \fBKalman1dState\fP"
.br
.ti -1c
.RI "class \fBkalmanFilter1D\fP"
.br
.ti -1c
.RI "class \fBKFTrackV\fP"
.br
.ti -1c
.RI "class \fBPID_CONST\fP"
.br
.ti -1c
.RI "class \fBSimpleTracker\fP"
.br
.ti -1c
.RI "class \fBSimulatedTrajectoryFollower\fP"
.br
.ti -1c
.RI "class \fBTrajectoryFollower\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTRACKING_TYPE\fP { \fBASSOCIATE_ONLY\fP = 0, \fBSIMPLE_TRACKER\fP = 1, \fBCONTOUR_TRACKER\fP = 2 }"
.br
.ti -1c
.RI "enum \fBCAR_TYPE\fP { \fBMv2Car\fP, \fBPHVCar\fP, \fBHVCar\fP, \fBRoboCar\fP, \fBSimulationCar\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSimulationNS::CAR_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMv2Car \fP\fP
Mv2Car\&. 
.TP
\fB\fIPHVCar \fP\fP
PHVCar\&. 
.TP
\fB\fIHVCar \fP\fP
HVCar\&. 
.TP
\fB\fIRoboCar \fP\fP
RoboCar\&. 
.TP
\fB\fISimulationCar \fP\fP
.PP
Definition at line 17 of file CommonSimuDefinitions\&.h\&.
.SS "enum \fBSimulationNS::TRACKING_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIASSOCIATE_ONLY \fP\fP
.TP
\fB\fISIMPLE_TRACKER \fP\fP
.TP
\fB\fICONTOUR_TRACKER \fP\fP
.PP
Definition at line 24 of file SimpleTracker\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
