.TH "SimulationNS::Kalman1dState" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimulationNS::Kalman1dState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleTracker\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBMovCov\fP"
.br
.ti -1c
.RI "double \fBMeasureCov\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBp\fP"
.br
.ti -1c
.RI "double \fBk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file SimpleTracker\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double SimulationNS::Kalman1dState::k"

.PP
Definition at line 32 of file SimpleTracker\&.h\&.
.SS "double SimulationNS::Kalman1dState::MeasureCov"

.PP
Definition at line 29 of file SimpleTracker\&.h\&.
.SS "double SimulationNS::Kalman1dState::MovCov"

.PP
Definition at line 28 of file SimpleTracker\&.h\&.
.SS "double SimulationNS::Kalman1dState::p"

.PP
Definition at line 31 of file SimpleTracker\&.h\&.
.SS "double SimulationNS::Kalman1dState::x"

.PP
Definition at line 30 of file SimpleTracker\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
