.TH "/home/deng/Project/autobot-feature-decision/ros/src/system/sync/include/single_sync.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/system/sync/include/single_sync.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ros/ros\&.h'\fP
.br
\fC#include <boost/circular_buffer\&.hpp>\fP
.br
\fC#include 'impl/single_sync_impl\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSingleSynchronizer< T1, T2, T3 >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
