.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/sopas/SopasBase.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/sopas/SopasBase.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./BasicDatatypes\&.hpp'\fP
.br
\fC#include '\&.\&./datatypes/Scan\&.hpp'\fP
.br
\fC#include '\&.\&./interfaces/tcp\&.hpp'\fP
.br
\fC#include 'colaa\&.hpp'\fP
.br
\fC#include 'colab\&.hpp'\fP
.br
\fC#include <map>\fP
.br
\fC#include '\&.\&./tools/Mutex\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdevices::SopasBase\fP"
.br
.ti -1c
.RI "class \fBdevices::SopasEventMessage\fP"
.br
.RI "\fIClass that represents a message that was sent by a sensor\&. (Event message) \fP"
.ti -1c
.RI "class \fBdevices::SopasAnswer\fP"
.br
.RI "\fIClass that encapsulates a buffer that was sent as return to a sync call\&. (variable / method) \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdevices\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
