.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/sopas/SopasBase.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/sick/ldmrs/sick_ldmrs_driver/src/driver/src/sopas/SopasBase.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SopasBase\&.hpp'\fP
.br
\fC#include '\&.\&./manager\&.hpp'\fP
.br
\fC#include '\&.\&./tools/errorhandler\&.hpp'\fP
.br
\fC#include '\&.\&./tools/toolbox\&.hpp'\fP
.br
\fC#include '\&.\&./tools/Mutex\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdevices\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSOPASBASE_VERSION\fP   '1\&.0\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SOPASBASE_VERSION   '1\&.0\&.0'"

.PP
Definition at line 19 of file SopasBase\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
