.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/nodes/sp_tracker/sp_tracker_core.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/nodes/sp_tracker/sp_tracker_core.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include <geometry_msgs/TwistStamped\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <std_msgs/Float32\&.h>\fP
.br
\fC#include <visualization_msgs/Marker\&.h>\fP
.br
\fC#include 'autoware_config_msgs/ConfigWaypointFollower\&.h'\fP
.br
\fC#include 'autoware_msgs/ControlCommandStamped\&.h'\fP
.br
\fC#include 'autoware_msgs/Lane\&.h'\fP
.br
\fC#include 'stanley\&.h'\fP
.br
\fC#include 'pure_pursuit\&.h'\fP
.br
\fC#include <autoware_health_checker/node_status_publisher\&.h>\fP
.br
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpTrackerNode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
