.TH "SpinnakerCamera" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpinnakerCamera \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinnakerCamera\fP ()"
.br
.ti -1c
.RI "\fB~SpinnakerCamera\fP ()"
.br
.ti -1c
.RI "void \fBspin\fP ()"
.br
.ti -1c
.RI "void \fBpublish_image\fP (int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file spinnaker\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpinnakerCamera::SpinnakerCamera ()"

.PP
Definition at line 68 of file spinnaker\&.cpp\&.
.SS "SpinnakerCamera::~SpinnakerCamera ()"

.PP
Definition at line 224 of file spinnaker\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SpinnakerCamera::publish_image (int index)"

.PP
Definition at line 239 of file spinnaker\&.cpp\&.
.SS "void SpinnakerCamera::spin ()"

.PP
Definition at line 312 of file spinnaker\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
