.TH "Spline" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Spline \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libtraj_gen\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   double \fBs\fP"
.br
.ti -1c
.RI "   double \fBkappa_1\fP"
.br
.ti -1c
.RI "   double \fBkappa_2\fP"
.br
.ti -1c
.RI "   double \fBkappa_0\fP"
.br
.ti -1c
.RI "   double \fBkappa_3\fP"
.br
.ti -1c
.RI "   bool \fBsuccess\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "double \fBspline_value\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file libtraj_gen\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "double Spline::kappa_0"

.PP
Definition at line 175 of file libtraj_gen\&.h\&.
.SS "double Spline::kappa_1"

.PP
Definition at line 170 of file libtraj_gen\&.h\&.
.SS "double Spline::kappa_2"

.PP
Definition at line 171 of file libtraj_gen\&.h\&.
.SS "double Spline::kappa_3"

.PP
Definition at line 176 of file libtraj_gen\&.h\&.
.SS "double Spline::s"

.PP
Definition at line 169 of file libtraj_gen\&.h\&.
.SS "double Spline::spline_value[6]"

.PP
Definition at line 181 of file libtraj_gen\&.h\&.
.SS "bool Spline::success"

.PP
Definition at line 177 of file libtraj_gen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
