.TH "SSD" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSD \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSSDDetectorClasses\fP { \fBBACKGROUND\fP, \fBPLANE\fP, \fBBICYCLE\fP, \fBBIRD\fP, \fBBOAT\fP, \fBBOTTLE\fP, \fBBUS\fP, \fBCAR\fP, \fBCAT\fP, \fBCHAIR\fP, \fBCOW\fP, \fBTABLE\fP, \fBDOG\fP, \fBHORSE\fP, \fBMOTORBIKE\fP, \fBPERSON\fP, \fBPLANT\fP, \fBSHEEP\fP, \fBSOFA\fP, \fBTRAIN\fP, \fBTV\fP, \fBNUM_CLASSES\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSSD::SSDDetectorClasses\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBACKGROUND \fP\fP
.TP
\fB\fIPLANE \fP\fP
.TP
\fB\fIBICYCLE \fP\fP
.TP
\fB\fIBIRD \fP\fP
.TP
\fB\fIBOAT \fP\fP
.TP
\fB\fIBOTTLE \fP\fP
.TP
\fB\fIBUS \fP\fP
.TP
\fB\fICAR \fP\fP
.TP
\fB\fICAT \fP\fP
.TP
\fB\fICHAIR \fP\fP
.TP
\fB\fICOW \fP\fP
.TP
\fB\fITABLE \fP\fP
.TP
\fB\fIDOG \fP\fP
.TP
\fB\fIHORSE \fP\fP
.TP
\fB\fIMOTORBIKE \fP\fP
.TP
\fB\fIPERSON \fP\fP
.TP
\fB\fIPLANT \fP\fP
.TP
\fB\fISHEEP \fP\fP
.TP
\fB\fISOFA \fP\fP
.TP
\fB\fITRAIN \fP\fP
.TP
\fB\fITV \fP\fP
.TP
\fB\fINUM_CLASSES \fP\fP
.PP
Definition at line 21 of file vision_ssd_detect\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
