.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/nodes/stanley_tracker/stanley_tracker_viz.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/nodes/stanley_tracker/stanley_tracker_viz.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stanley_tracker_viz\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "visualization_msgs::Marker \fBdisplayFrontWheelPosition\fP (\fBgeometry_msgs::Point\fP position)"
.br
.ti -1c
.RI "visualization_msgs::Marker \fBdisplayNextTarget\fP (\fBgeometry_msgs::Point\fP target)"
.br
.ti -1c
.RI "visualization_msgs::Marker \fBdisplayCrossTrackError\fP (\fBgeometry_msgs::Point\fP current_pose, double crossTrackError)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBMAP_FRAME\fP = 'map'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "visualization_msgs::Marker displayCrossTrackError (\fBgeometry_msgs::Point\fP current_pose, double crossTrackError)"

.PP
Definition at line 52 of file stanley_tracker_viz\&.cpp\&.
.SS "visualization_msgs::Marker displayFrontWheelPosition (\fBgeometry_msgs::Point\fP position)"

.PP
\fBAuthor:\fP
.RS 4
hui huang  hui.huang1@siat.ac.cn 
.RE
.PP

.PP
Definition at line 10 of file stanley_tracker_viz\&.cpp\&.
.SS "visualization_msgs::Marker displayNextTarget (\fBgeometry_msgs::Point\fP target)"

.PP
Definition at line 30 of file stanley_tracker_viz\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const std::string MAP_FRAME = 'map'"

.PP
\fBAuthor:\fP
.RS 4
hui huang : hui.huang1@siat.ac.cn 
.RE
.PP

.PP
Definition at line 8 of file stanley_tracker_viz\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
