.TH "state_machine" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
state_machine \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBState\fP"
.br
.ti -1c
.RI "class \fBStateContext\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCallbackType\fP { \fBCallbackType::UPDATE\fP, \fBCallbackType::ENTRY\fP, \fBCallbackType::EXIT\fP }"
.br
.ti -1c
.RI "enum \fBTrafficLightColors\fP { \fBE_RED\fP = 0, \fBE_YELLOW\fP = 0, \fBE_GREEN\fP = 1, \fBE_COLOR_ERROR\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstate_machine::CallbackType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUPDATE \fP\fP
.TP
\fB\fIENTRY \fP\fP
.TP
\fB\fIEXIT \fP\fP
.PP
Definition at line 6 of file state_flags\&.hpp\&.
.SS "enum \fBstate_machine::TrafficLightColors\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIE_RED \fP\fP
.TP
\fB\fIE_YELLOW \fP\fP
.TP
\fB\fIE_GREEN \fP\fP
.TP
\fB\fIE_COLOR_ERROR \fP\fP
.PP
Definition at line 13 of file state_flags\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
