.TH "Status" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Status \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatus\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExpMovingAverage\fP \fBk\fP"
.br
.ti -1c
.RI "\fBExpMovingAverage\fP \fBb\fP"
.br
.ti -1c
.RI "bool \fBreset\fP"
.br
.ti -1c
.RI "int \fBlost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file vision_lane_detect\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Status::Status ()\fC [inline]\fP"

.PP
Definition at line 78 of file vision_lane_detect\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBExpMovingAverage\fP Status::b"

.PP
Definition at line 79 of file vision_lane_detect\&.cpp\&.
.SS "\fBExpMovingAverage\fP Status::k"

.PP
Definition at line 79 of file vision_lane_detect\&.cpp\&.
.SS "int Status::lost"

.PP
Definition at line 81 of file vision_lane_detect\&.cpp\&.
.SS "bool Status::reset"

.PP
Definition at line 80 of file vision_lane_detect\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
