.TH "stbi_io_callbacks" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi_io_callbacks \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stb_image\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBread\fP )(void *user, char *\fBdata\fP, int size)"
.br
.ti -1c
.RI "void(* \fBskip\fP )(void *user, int n)"
.br
.ti -1c
.RI "int(* \fBeof\fP )(void *user)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 344 of file stb_image\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int(* stbi_io_callbacks::eof) (void *user)"

.PP
Definition at line 348 of file stb_image\&.h\&.
.SS "int(* stbi_io_callbacks::read) (void *user, char *\fBdata\fP, int size)"

.PP
Definition at line 346 of file stb_image\&.h\&.
.SS "void(* stbi_io_callbacks::skip) (void *user, int n)"

.PP
Definition at line 347 of file stb_image\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
