.TH "/home/deng/Project/autobot-feature-decision/ros/src/system/sync/sync_generator2.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/system/sync/sync_generator2.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsync_generator2\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsync_generator2\&.argvs\fP = sys\&.argv"
.br
.ti -1c
.RI "\fBsync_generator2\&.argc\fP = len(argvs)"
.br
.ti -1c
.RI "string \fBsync_generator2\&.text\fP = ''"
.br
.ti -1c
.RI "\fBsync_generator2\&.f_config\fP = open(argvs[1], 'r')"
.br
.ti -1c
.RI "\fBsync_generator2\&.f_generate\fP = open(argvs[2], 'w')"
.br
.ti -1c
.RI "\fBsync_generator2\&.data\fP = yaml\&.load(f_config)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
