.TH "sync_generator" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sync_generator \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBargvs\fP = sys\&.argv"
.br
.ti -1c
.RI "\fBargc\fP = len(\fBargvs\fP)"
.br
.ti -1c
.RI "string \fBtext\fP = ''"
.br
.ti -1c
.RI "\fBf_config\fP = open(\fBargvs\fP[1], 'r')"
.br
.ti -1c
.RI "\fBf_generate\fP = open(\fBargvs\fP[2], 'w')"
.br
.ti -1c
.RI "\fBdata\fP = yaml\&.load(\fBf_config\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "sync_generator\&.argc = len(\fBargvs\fP)"

.PP
Definition at line 6 of file sync_generator\&.py\&.
.SS "sync_generator\&.argvs = sys\&.argv"

.PP
Definition at line 5 of file sync_generator\&.py\&.
.SS "sync_generator\&.data = yaml\&.load(\fBf_config\fP)"

.PP
Definition at line 18 of file sync_generator\&.py\&.
.SS "sync_generator\&.f_config = open(\fBargvs\fP[1], 'r')"

.PP
Definition at line 15 of file sync_generator\&.py\&.
.SS "sync_generator\&.f_generate = open(\fBargvs\fP[2], 'w')"

.PP
Definition at line 16 of file sync_generator\&.py\&.
.SS "string sync_generator\&.text = ''"

.PP
Definition at line 7 of file sync_generator\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
