.TH "/home/deng/Project/autobot-feature-decision/ros/src/util/packages/runtime_manager/scripts/test_pub.py" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/util/packages/runtime_manager/scripts/test_pub.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtest_pub\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBtest_pub\&.s\fP = sys\&.argv[1]iflen(sys\&.argv)>1"
.br
.ti -1c
.RI "\fBtest_pub\&.anonymous\fP"
.br
.ti -1c
.RI "\fBtest_pub\&.pub\fP = rospy\&.Publisher('to_rtmgr', std_msgs\&.msg\&.String, queue_size=10)"
.br
.ti -1c
.RI "\fBtest_pub\&.r\fP = rospy\&.Rate(10)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
