.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/test/src/test_twist_gate.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/motion/packages/waypoint_follower/test/src/test_twist_gate.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include 'test_twist_gate\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTwistGateTestSuite\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, resetVehicelCmd)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, twistCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, controlCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, remoteCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, remoteCmdEmergency)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, modeCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, gearCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, accelCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, steerCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, brakeCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, lampCmdCallback)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTwistGateTestSuite\fP, \fBstateCallback\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 263 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, resetVehicelCmd)"

.PP
Definition at line 38 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, twistCmdCallback)"

.PP
Definition at line 72 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, controlCmdCallback)"

.PP
Definition at line 85 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, remoteCmdCallback)"

.PP
Definition at line 100 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, remoteCmdEmergency)"

.PP
Definition at line 156 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, modeCmdCallback)"

.PP
Definition at line 169 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, gearCmdCallback)"

.PP
Definition at line 181 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, accelCmdCallback)"

.PP
Definition at line 193 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, steerCmdCallback)"

.PP
Definition at line 205 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, brakeCmdCallback)"

.PP
Definition at line 217 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, lampCmdCallback)"

.PP
Definition at line 229 of file test_twist_gate\&.cpp\&.
.SS "TEST_F (\fBTwistGateTestSuite\fP, \fBstateCallback\fP)"

.PP
Definition at line 243 of file test_twist_gate\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
