.TH "test_adxl345.TestImu" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_adxl345.TestImu \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUpClass\fP (cls)"
.br
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBcb_imu_raw\fP (self, msg)"
.br
.ti -1c
.RI "def \fBtest_imu_raw\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimu_raw_count\fP"
.br
.ti -1c
.RI "\fBimu_count\fP"
.br
.ti -1c
.RI "\fBimu_raw_min\fP"
.br
.ti -1c
.RI "\fBimu_raw_max\fP"
.br
.ti -1c
.RI "\fBimu_min\fP"
.br
.ti -1c
.RI "\fBimu_max\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file test_adxl345\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_adxl345\&.TestImu\&.cb_imu_raw ( self,  msg)"

.PP
Definition at line 63 of file test_adxl345\&.py\&.
.SS "def test_adxl345\&.TestImu\&.setUp ( self)"

.PP
Definition at line 53 of file test_adxl345\&.py\&.
.SS "def test_adxl345\&.TestImu\&.setUpClass ( cls)"

.PP
Definition at line 50 of file test_adxl345\&.py\&.
.SS "def test_adxl345\&.TestImu\&.test_imu_raw ( self)"

.PP
Definition at line 68 of file test_adxl345\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "test_adxl345\&.TestImu\&.imu_count"

.PP
Definition at line 55 of file test_adxl345\&.py\&.
.SS "test_adxl345\&.TestImu\&.imu_max"

.PP
Definition at line 59 of file test_adxl345\&.py\&.
.SS "test_adxl345\&.TestImu\&.imu_min"

.PP
Definition at line 58 of file test_adxl345\&.py\&.
.SS "test_adxl345\&.TestImu\&.imu_raw_count"

.PP
Definition at line 54 of file test_adxl345\&.py\&.
.SS "test_adxl345\&.TestImu\&.imu_raw_max"

.PP
Definition at line 57 of file test_adxl345\&.py\&.
.SS "test_adxl345\&.TestImu\&.imu_raw_min"

.PP
Definition at line 56 of file test_adxl345\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
