.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/semantics/packages/costmap_generator/test/src/test_costmap_generator.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/semantics/packages/costmap_generator/test/src/test_costmap_generator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'costmap_generator/costmap_generator\&.h'\fP
.br
\fC#include 'test_costmap_generator\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestSuite\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeRectanglePoints)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckAssignPoints2GridCell)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckFetchGridIndexFromPoint)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckValidIndex)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckNonValidIndex)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckCalculationPointsCostmap)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckHeightThresholdForCost)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeExpandedPoints)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, ChecMakePolygonFromObjectConvexhull)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, ChecMakePolygonFromObjectConvexhullDofferentHeight)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckSetCostInPolygon)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeCostmapFromObjects)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeCostmapFromObjectsExpandSize)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeCostmapFromObjectsBlur)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeCostmapFromObjectsBox)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBTestSuite\fP, CheckMakeCostmapFromObjectsBoxBlur)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 452 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeRectanglePoints)"

.PP
Definition at line 77 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckAssignPoints2GridCell)"

.PP
Definition at line 104 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckFetchGridIndexFromPoint)"

.PP
Definition at line 122 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckValidIndex)"

.PP
Definition at line 140 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckNonValidIndex)"

.PP
Definition at line 149 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckCalculationPointsCostmap)"

.PP
Definition at line 158 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckHeightThresholdForCost)"

.PP
Definition at line 174 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeExpandedPoints)"

.PP
Definition at line 190 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, ChecMakePolygonFromObjectConvexhull)"

.PP
Definition at line 212 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, ChecMakePolygonFromObjectConvexhullDofferentHeight)"

.PP
Definition at line 238 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckSetCostInPolygon)"

.PP
Definition at line 267 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeCostmapFromObjects)"

.PP
Definition at line 285 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeCostmapFromObjectsExpandSize)"

.PP
Definition at line 333 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeCostmapFromObjectsBlur)"

.PP
Definition at line 360 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeCostmapFromObjectsBox)"

.PP
Definition at line 388 of file test_costmap_generator\&.cpp\&.
.SS "TEST_F (\fBTestSuite\fP, CheckMakeCostmapFromObjectsBoxBlur)"

.PP
Definition at line 418 of file test_costmap_generator\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
