.TH "/home/deng/Project/autobot-feature-decision/ros/src/common/libs/amathutils_lib/test/src/test_amathutils_lib.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/common/libs/amathutils_lib/test/src/test_amathutils_lib.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'amathutils_lib/amathutils\&.hpp'\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <geometry_msgs/Point\&.h>\fP
.br
\fC#include <geometry_msgs/Pose\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestSuite\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLEFT\fP   1"
.br
.ti -1c
.RI "#define \fBRIGHT\fP   \-1"
.br
.ti -1c
.RI "#define \fBONLINE\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, Rad2Deg)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, Deg2Rad)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, Transform_mps2kph)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, Transform_kmph2mps)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetGravityAcceleration)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetAcceleration)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetTimeFromAcceleration)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetNearPointOnLine2D)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetNearPointOnLine3D)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetDistance)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, GetAngle)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, LineIntersect)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, ParallelLines)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, PointOnTheLeft)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, PointOnTheRight)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, PointOnTheLine)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LEFT   1"

.PP
Definition at line 197 of file test_amathutils_lib\&.cpp\&.
.SS "#define ONLINE   0"

.PP
Definition at line 199 of file test_amathutils_lib\&.cpp\&.
.SS "#define RIGHT   \-1"

.PP
Definition at line 198 of file test_amathutils_lib\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 252 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, Rad2Deg)"

.PP
Definition at line 14 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, Deg2Rad)"

.PP
Definition at line 19 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, Transform_mps2kph)"

.PP
Definition at line 25 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, Transform_kmph2mps)"

.PP
Definition at line 31 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetGravityAcceleration)"

.PP
Definition at line 36 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetAcceleration)"

.PP
Definition at line 41 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetTimeFromAcceleration)"

.PP
Definition at line 50 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetNearPointOnLine2D)"

.PP
Definition at line 59 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetNearPointOnLine3D)"

.PP
Definition at line 87 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetDistance)"

.PP
Definition at line 115 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, GetAngle)"

.PP
Definition at line 141 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, LineIntersect)"

.PP
Definition at line 158 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, ParallelLines)"

.PP
Definition at line 178 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, PointOnTheLeft)"

.PP
Definition at line 202 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, PointOnTheRight)"

.PP
Definition at line 219 of file test_amathutils_lib\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, PointOnTheLine)"

.PP
Definition at line 236 of file test_amathutils_lib\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
