.TH "test_adis16470.TestImu" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_adis16470.TestImu \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUpClass\fP (cls)"
.br
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBcb_imu_raw\fP (self, msg)"
.br
.ti -1c
.RI "def \fBcb_imu\fP (self, msg)"
.br
.ti -1c
.RI "def \fBtest_imu_raw\fP (self)"
.br
.ti -1c
.RI "def \fBtest_imu\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimu_raw_count\fP"
.br
.ti -1c
.RI "\fBimu_count\fP"
.br
.ti -1c
.RI "\fBimu_raw_data\fP"
.br
.ti -1c
.RI "\fBimu_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file test_adis16470\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def test_adis16470\&.TestImu\&.cb_imu ( self,  msg)"

.PP
Definition at line 72 of file test_adis16470\&.py\&.
.SS "def test_adis16470\&.TestImu\&.cb_imu_raw ( self,  msg)"

.PP
Definition at line 68 of file test_adis16470\&.py\&.
.SS "def test_adis16470\&.TestImu\&.setUp ( self)"

.PP
Definition at line 60 of file test_adis16470\&.py\&.
.SS "def test_adis16470\&.TestImu\&.setUpClass ( cls)"

.PP
Definition at line 57 of file test_adis16470\&.py\&.
.SS "def test_adis16470\&.TestImu\&.test_imu ( self)"

.PP
Definition at line 104 of file test_adis16470\&.py\&.
.SS "def test_adis16470\&.TestImu\&.test_imu_raw ( self)"

.PP
Definition at line 76 of file test_adis16470\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "test_adis16470\&.TestImu\&.imu_count"

.PP
Definition at line 62 of file test_adis16470\&.py\&.
.SS "test_adis16470\&.TestImu\&.imu_data"

.PP
Definition at line 64 of file test_adis16470\&.py\&.
.SS "test_adis16470\&.TestImu\&.imu_raw_count"

.PP
Definition at line 61 of file test_adis16470\&.py\&.
.SS "test_adis16470\&.TestImu\&.imu_raw_data"

.PP
Definition at line 63 of file test_adis16470\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
