.TH "test_pub" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_pub \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBs\fP = sys\&.argv[1]iflen(sys\&.argv)>1"
.br
.ti -1c
.RI "\fBanonymous\fP"
.br
.ti -1c
.RI "\fBpub\fP = rospy\&.Publisher('to_rtmgr', std_msgs\&.msg\&.String, queue_size=10)"
.br
.ti -1c
.RI "\fBr\fP = rospy\&.Rate(10)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "test_pub\&.anonymous"

.PP
Definition at line 23 of file test_pub\&.py\&.
.SS "test_pub\&.pub = rospy\&.Publisher('to_rtmgr', std_msgs\&.msg\&.String, queue_size=10)"

.PP
Definition at line 24 of file test_pub\&.py\&.
.SS "test_pub\&.r = rospy\&.Rate(10)"

.PP
Definition at line 25 of file test_pub\&.py\&.
.SS "int test_pub\&.s = sys\&.argv[1]iflen(sys\&.argv)>1"

.PP
Definition at line 22 of file test_pub\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
