.TH "/home/deng/Project/autobot-feature-decision/ros/src/system/autoware_health_checker/test/src/test_autoware_health_checker.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/system/autoware_health_checker/test/src/test_autoware_health_checker.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <autoware_health_checker/node_status_publisher\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutowareHealthCheckerTestSuite\fP"
.br
.ti -1c
.RI "class \fBAutowareHealthCheckerTestClass\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, CHECK_MIN_VALUE)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, CHECK_MAX_VALUE)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, CHECK_RANGE)"
.br
.ti -1c
.RI "uint8_t \fBtest_function\fP (double value)"
.br
.ti -1c
.RI "boost::property_tree::ptree \fBtest_value_json_func\fP (double value)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, CHECK_VALUE)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBTestSuite\fP, NODE_STATUS)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 176 of file test_autoware_health_checker\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, CHECK_MIN_VALUE)"

.PP
Definition at line 42 of file test_autoware_health_checker\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, CHECK_MAX_VALUE)"

.PP
Definition at line 66 of file test_autoware_health_checker\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, CHECK_RANGE)"

.PP
Definition at line 90 of file test_autoware_health_checker\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, CHECK_VALUE)"

.PP
Definition at line 133 of file test_autoware_health_checker\&.cpp\&.
.SS "TEST (\fBTestSuite\fP, NODE_STATUS)"

.PP
Definition at line 164 of file test_autoware_health_checker\&.cpp\&.
.SS "uint8_t test_function (double value)"

.PP
Definition at line 114 of file test_autoware_health_checker\&.cpp\&.
.SS "boost::property_tree::ptree test_value_json_func (double value)"

.PP
Definition at line 127 of file test_autoware_health_checker\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
