.TH "tests.test_plugins" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.test_plugins \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest_plugin_type\fP ()"
.br
.ti -1c
.RI "def \fBtest_plugin_field\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def tests\&.test_plugins\&.test_plugin_field ()"

.PP
Definition at line 19 of file test_plugins\&.py\&.
.SS "def tests\&.test_plugins\&.test_plugin_type ()"

.PP
Definition at line 8 of file test_plugins\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
