.TH "thresholds_set" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thresholds_set \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tunerBody\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue_set\fP \fBhue\fP"
.br
.ti -1c
.RI "\fBvalue_set\fP \fBsat\fP"
.br
.ti -1c
.RI "\fBvalue_set\fP \fBval\fP"
.br
.ti -1c
.RI "bool \fBisUpdated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file tunerBody\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvalue_set\fP thresholds_set::hue"

.PP
Definition at line 25 of file tunerBody\&.h\&.
.SS "bool thresholds_set::isUpdated"

.PP
Definition at line 28 of file tunerBody\&.h\&.
.SS "\fBvalue_set\fP thresholds_set::sat"

.PP
Definition at line 26 of file tunerBody\&.h\&.
.SS "\fBvalue_set\fP thresholds_set::val"

.PP
Definition at line 27 of file tunerBody\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
