.TH "TimeDuration" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeDuration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Time\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeDuration\fP ()"
.br
.ti -1c
.RI "\fBTimeDuration\fP (double seconds)"
.br
.ti -1c
.RI "void \fBset\fP (double seconds)"
.br
.ti -1c
.RI "\fBUINT32\fP \fBtotal_milliseconds\fP ()"
.br
.ti -1c
.RI "\fBTimeDuration\fP & \fBoperator=\fP (const double &seconds)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBm_duration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Time\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TimeDuration::TimeDuration ()"

.PP
Definition at line 14 of file Time\&.cpp\&.
.SS "TimeDuration::TimeDuration (double seconds)\fC [inline]\fP"

.PP
Definition at line 20 of file Time\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTimeDuration\fP & TimeDuration::operator= (const double & seconds)\fC [inline]\fP"

.PP
Definition at line 30 of file Time\&.hpp\&.
.SS "void TimeDuration::set (double seconds)\fC [inline]\fP"

.PP
Definition at line 22 of file Time\&.hpp\&.
.SS "\fBUINT32\fP TimeDuration::total_milliseconds ()\fC [inline]\fP"

.PP
Definition at line 37 of file Time\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double TimeDuration::m_duration"

.PP
Definition at line 26 of file Time\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
