.TH "time_visualizer" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time_visualizer \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcallback\fP (\fBdata\fP)"
.br
.ti -1c
.RI "def \fBvisualizer\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def time_visualizer\&.callback ( data)"

.PP
Definition at line 8 of file time_visualizer\&.py\&.
.SS "def time_visualizer\&.visualizer ()"

.PP
Definition at line 11 of file time_visualizer\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
