.TH "TLSwitch" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TLSwitch \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTLSwitch\fP (const ros::NodeHandle &nh, const ros::NodeHandle &private_nh)"
.br
.ti -1c
.RI "\fB~TLSwitch\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file tl_switch\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TLSwitch::TLSwitch (const ros::NodeHandle & nh, const ros::NodeHandle & private_nh)"

.PP
Definition at line 40 of file tl_switch\&.cpp\&.
.SS "TLSwitch::~TLSwitch ()"

.PP
Definition at line 61 of file tl_switch\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
