.TH "TwistGateTestSuite" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwistGateTestSuite \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwistGateTestSuite\fP ()"
.br
.ti -1c
.RI "\fB~TwistGateTestSuite\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTwistGateTestClass\fP \fBtest_obj_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file test_twist_gate\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TwistGateTestSuite::TwistGateTestSuite ()\fC [inline]\fP"

.PP
Definition at line 24 of file test_twist_gate\&.cpp\&.
.SS "TwistGateTestSuite::~TwistGateTestSuite ()\fC [inline]\fP"

.PP
Definition at line 25 of file test_twist_gate\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void TwistGateTestSuite::SetUp ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 30 of file test_twist_gate\&.cpp\&.
.SS "virtual void TwistGateTestSuite::TearDown ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 35 of file test_twist_gate\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTwistGateTestClass\fP TwistGateTestSuite::test_obj_"

.PP
Definition at line 27 of file test_twist_gate\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
