.TH "/home/deng/Project/autobot-feature-decision/ros/src/socket/packages/udon_socket/lib/udon_socket/udon.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/socket/packages/udon_socket/lib/udon_socket/udon.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <udon_socket/udon\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBudon_socket\fP"
.br
.ti -1c
.RI " \fBudon_socket::udon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBudon_socket::udon::send_request\fP (int fd)"
.br
.ti -1c
.RI "ssize_t \fBudon_socket::udon::send_response\fP (int fd)"
.br
.ti -1c
.RI "ssize_t \fBudon_socket::udon::send_mode\fP (int fd, std::int32_t mode)"
.br
.ti -1c
.RI "ssize_t \fBudon_socket::udon::send_location\fP (int fd, const Location &location)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
