.TH "udon_socket::udon::Location" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udon_socket::udon::Location \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <udon\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBLocation\fP &location) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file udon\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool udon_socket::udon::Location::operator!= (const \fBLocation\fP & location) const"

.PP
Definition at line 84 of file udon\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double udon_socket::udon::Location::d"

.PP
Definition at line 36 of file udon\&.hpp\&.
.SS "double udon_socket::udon::Location::x"

.PP
Definition at line 33 of file udon\&.hpp\&.
.SS "double udon_socket::udon::Location::y"

.PP
Definition at line 34 of file udon\&.hpp\&.
.SS "double udon_socket::udon::Location::z"

.PP
Definition at line 35 of file udon\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
