.TH "UtilityHNS::AisanSignalFileReader::AisanSignal" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanSignalFileReader::AisanSignal \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "int \fBVID\fP"
.br
.ti -1c
.RI "int \fBPLID\fP"
.br
.ti -1c
.RI "int \fBType\fP"
.br
.ti -1c
.RI "int \fBLinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 479 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int UtilityHNS::AisanSignalFileReader::AisanSignal::ID"

.PP
Definition at line 481 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanSignalFileReader::AisanSignal::LinkID"

.PP
Definition at line 485 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanSignalFileReader::AisanSignal::PLID"

.PP
Definition at line 483 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanSignalFileReader::AisanSignal::Type"

.PP
Definition at line 484 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanSignalFileReader::AisanSignal::VID"

.PP
Definition at line 482 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
