.TH "UtilityHNS::AisanLinesFileReader::AisanLine" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanLinesFileReader::AisanLine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBLID\fP"
.br
.ti -1c
.RI "int \fBBPID\fP"
.br
.ti -1c
.RI "int \fBFPID\fP"
.br
.ti -1c
.RI "int \fBBLID\fP"
.br
.ti -1c
.RI "int \fBFLID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int UtilityHNS::AisanLinesFileReader::AisanLine::BLID"

.PP
Definition at line 243 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanLinesFileReader::AisanLine::BPID"

.PP
Definition at line 241 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanLinesFileReader::AisanLine::FLID"

.PP
Definition at line 244 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanLinesFileReader::AisanLine::FPID"

.PP
Definition at line 242 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanLinesFileReader::AisanLine::LID"

.PP
Definition at line 240 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
