.TH "UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "int \fBLID\fP"
.br
.ti -1c
.RI "int \fBWidth\fP"
.br
.ti -1c
.RI "int \fBColor\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBLinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 681 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine::Color"

.PP
Definition at line 686 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine::ID"

.PP
Definition at line 683 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine::LID"

.PP
Definition at line 684 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine::LinkID"

.PP
Definition at line 688 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine::type"

.PP
Definition at line 687 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanWhiteLinesFileReader::AisanWhiteLine::Width"

.PP
Definition at line 685 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
