.TH "UtilityHNS::LocalizationPathReader::LocalizationWayPoint" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::LocalizationPathReader::LocalizationWayPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 152 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double UtilityHNS::LocalizationPathReader::LocalizationWayPoint::a"

.PP
Definition at line 158 of file DataRW\&.h\&.
.SS "double UtilityHNS::LocalizationPathReader::LocalizationWayPoint::t"

.PP
Definition at line 154 of file DataRW\&.h\&.
.SS "double UtilityHNS::LocalizationPathReader::LocalizationWayPoint::v"

.PP
Definition at line 159 of file DataRW\&.h\&.
.SS "double UtilityHNS::LocalizationPathReader::LocalizationWayPoint::x"

.PP
Definition at line 155 of file DataRW\&.h\&.
.SS "double UtilityHNS::LocalizationPathReader::LocalizationWayPoint::y"

.PP
Definition at line 156 of file DataRW\&.h\&.
.SS "double UtilityHNS::LocalizationPathReader::LocalizationWayPoint::z"

.PP
Definition at line 157 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
