.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_apollo_cnn_seg_detect/include/util.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/perception/detection/lidar_detector/packages/lidar_apollo_cnn_seg_detect/include/util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBF2I\fP (float val, float ori, float scale)"
.br
.ti -1c
.RI "int \fBPc2Pixel\fP (float in_pc, float in_range, float out_size)"
.br
.ti -1c
.RI "float \fBPixel2Pc\fP (int in_pixel, float in_size, float out_range)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int F2I (float val, float ori, float scale)\fC [inline]\fP"

.PP
Definition at line 39 of file util\&.h\&.
.SS "int Pc2Pixel (float in_pc, float in_range, float out_size)\fC [inline]\fP"

.PP
Definition at line 43 of file util\&.h\&.
.SS "float Pixel2Pc (int in_pixel, float in_size, float out_range)\fC [inline]\fP"

.PP
Definition at line 48 of file util\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
