.TH "UtilityHNS::AisanDataConnFileReader" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanDataConnFileReader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.PP
Inherits \fBUtilityHNS::SimpleReaderBase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDataConn\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAisanDataConnFileReader\fP (const std::string &fileName)"
.br
.ti -1c
.RI "\fB~AisanDataConnFileReader\fP ()"
.br
.ti -1c
.RI "bool \fBReadNextLine\fP (\fBDataConn\fP &\fBdata\fP)"
.br
.ti -1c
.RI "int \fBReadAllData\fP (std::vector< \fBDataConn\fP > &data_list)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 657 of file DataRW\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UtilityHNS::AisanDataConnFileReader::AisanDataConnFileReader (const std::string & fileName)\fC [inline]\fP"

.PP
Definition at line 669 of file DataRW\&.h\&.
.SS "UtilityHNS::AisanDataConnFileReader::~AisanDataConnFileReader ()\fC [inline]\fP"

.PP
Definition at line 670 of file DataRW\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int UtilityHNS::AisanDataConnFileReader::ReadAllData (std::vector< \fBDataConn\fP > & data_list)"

.PP
Definition at line 2061 of file DataRW\&.cpp\&.
.SS "bool UtilityHNS::AisanDataConnFileReader::ReadNextLine (\fBDataConn\fP & data)"

.PP
Definition at line 2041 of file DataRW\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
