.TH "UtilityHNS::SimulationFileReader::SimulationPoint" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::SimulationFileReader::SimulationPoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBc\fP"
.br
.ti -1c
.RI "double \fBv\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double UtilityHNS::SimulationFileReader::SimulationPoint::a"

.PP
Definition at line 129 of file DataRW\&.h\&.
.SS "double UtilityHNS::SimulationFileReader::SimulationPoint::c"

.PP
Definition at line 130 of file DataRW\&.h\&.
.SS "std::string UtilityHNS::SimulationFileReader::SimulationPoint::name"

.PP
Definition at line 132 of file DataRW\&.h\&.
.SS "double UtilityHNS::SimulationFileReader::SimulationPoint::v"

.PP
Definition at line 131 of file DataRW\&.h\&.
.SS "double UtilityHNS::SimulationFileReader::SimulationPoint::x"

.PP
Definition at line 126 of file DataRW\&.h\&.
.SS "double UtilityHNS::SimulationFileReader::SimulationPoint::y"

.PP
Definition at line 127 of file DataRW\&.h\&.
.SS "double UtilityHNS::SimulationFileReader::SimulationPoint::z"

.PP
Definition at line 128 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
