.TH "/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_utility/include/op_utility/UtilityH.h" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/computing/planning/common/lib/openplanner/op_utility/include/op_utility/UtilityH.h \- General Math and Control utility functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUtilityHNS::UtilityH\fP"
.br
.ti -1c
.RI "class \fBUtilityHNS::PIDController\fP"
.br
.ti -1c
.RI "class \fBUtilityHNS::LowpassFilter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUtilityHNS\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEG2RAD\fP   M_PI / 180\&."
.br
.ti -1c
.RI "#define \fBRAD2DEG\fP   180\&. / M_PI"
.br
.ti -1c
.RI "#define \fBSIGN\fP(x)   (x > 0) ? 1 : ((x < 0) ? \-1 : 0)"
.br
.ti -1c
.RI "#define \fBMIN\fP(x,  y)   (x <= y ? x : y)"
.br
.ti -1c
.RI "#define \fBMAX\fP(x,  y)   (x >= y ? x : y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
General Math and Control utility functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Hatem Darweesh 
.RE
.PP
\fBDate:\fP
.RS 4
May 14, 2016 
.RE
.PP

.PP
Definition in file \fBUtilityH\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEG2RAD   M_PI / 180\&."

.PP
Definition at line 18 of file UtilityH\&.h\&.
.SS "#define MAX(x, y)   (x >= y ? x : y)"

.PP
Definition at line 22 of file UtilityH\&.h\&.
.SS "#define MIN(x, y)   (x <= y ? x : y)"

.PP
Definition at line 21 of file UtilityH\&.h\&.
.SS "#define RAD2DEG   180\&. / M_PI"

.PP
Definition at line 19 of file UtilityH\&.h\&.
.SS "#define SIGN(x)   (x > 0) ? 1 : ((x < 0) ? \-1 : 0)"

.PP
Definition at line 20 of file UtilityH\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
