.TH "UtilityHNS::MapRaw" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::MapRaw \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapRaw\fP ()"
.br
.ti -1c
.RI "\fB~MapRaw\fP ()"
.br
.ti -1c
.RI "int \fBGetVersion\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUtilityHNS::AisanLanesFileReader\fP * \fBpLanes\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanPointsFileReader\fP * \fBpPoints\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanCenterLinesFileReader\fP * \fBpCenterLines\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanIntersectionFileReader\fP * \fBpIntersections\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanAreasFileReader\fP * \fBpAreas\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanLinesFileReader\fP * \fBpLines\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanStopLineFileReader\fP * \fBpStopLines\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanSignalFileReader\fP * \fBpSignals\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanVectorFileReader\fP * \fBpVectors\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanCurbFileReader\fP * \fBpCurbs\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanRoadEdgeFileReader\fP * \fBpRoadedges\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanWayareaFileReader\fP * \fBpWayAreas\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanCrossWalkFileReader\fP * \fBpCrossWalks\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanNodesFileReader\fP * \fBpNodes\fP"
.br
.ti -1c
.RI "\fBUtilityHNS::AisanWhiteLinesFileReader\fP * \fBpWhiteLines\fP"
.br
.ti -1c
.RI "struct timespec \fB_time_out\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 708 of file DataRW\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UtilityHNS::MapRaw::MapRaw ()\fC [inline]\fP"

.PP
Definition at line 730 of file DataRW\&.h\&.
.SS "UtilityHNS::MapRaw::~MapRaw ()\fC [inline]\fP"

.PP
Definition at line 751 of file DataRW\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int UtilityHNS::MapRaw::GetVersion ()\fC [inline]\fP"

.PP
Definition at line 845 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct timespec UtilityHNS::MapRaw::_time_out"

.PP
Definition at line 728 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanAreasFileReader\fP* UtilityHNS::MapRaw::pAreas"

.PP
Definition at line 715 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanCenterLinesFileReader\fP* UtilityHNS::MapRaw::pCenterLines"

.PP
Definition at line 713 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanCrossWalkFileReader\fP* UtilityHNS::MapRaw::pCrossWalks"

.PP
Definition at line 723 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanCurbFileReader\fP* UtilityHNS::MapRaw::pCurbs"

.PP
Definition at line 720 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanIntersectionFileReader\fP* UtilityHNS::MapRaw::pIntersections"

.PP
Definition at line 714 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanLanesFileReader\fP* UtilityHNS::MapRaw::pLanes"

.PP
Definition at line 711 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanLinesFileReader\fP* UtilityHNS::MapRaw::pLines"

.PP
Definition at line 716 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanNodesFileReader\fP* UtilityHNS::MapRaw::pNodes"

.PP
Definition at line 724 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanPointsFileReader\fP* UtilityHNS::MapRaw::pPoints"

.PP
Definition at line 712 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanRoadEdgeFileReader\fP* UtilityHNS::MapRaw::pRoadedges"

.PP
Definition at line 721 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanSignalFileReader\fP* UtilityHNS::MapRaw::pSignals"

.PP
Definition at line 718 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanStopLineFileReader\fP* UtilityHNS::MapRaw::pStopLines"

.PP
Definition at line 717 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanVectorFileReader\fP* UtilityHNS::MapRaw::pVectors"

.PP
Definition at line 719 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanWayareaFileReader\fP* UtilityHNS::MapRaw::pWayAreas"

.PP
Definition at line 722 of file DataRW\&.h\&.
.SS "\fBUtilityHNS::AisanWhiteLinesFileReader\fP* UtilityHNS::MapRaw::pWhiteLines"

.PP
Definition at line 726 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
