.TH "UtilityHNS::AisanRoadEdgeFileReader::AisanRoadEdge" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanRoadEdgeFileReader::AisanRoadEdge \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "int \fBLID\fP"
.br
.ti -1c
.RI "int \fBLinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 572 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int UtilityHNS::AisanRoadEdgeFileReader::AisanRoadEdge::ID"

.PP
Definition at line 574 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanRoadEdgeFileReader::AisanRoadEdge::LID"

.PP
Definition at line 575 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanRoadEdgeFileReader::AisanRoadEdge::LinkID"

.PP
Definition at line 576 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
