.TH "UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "int \fBAID\fP"
.br
.ti -1c
.RI "int \fBType\fP"
.br
.ti -1c
.RI "int \fBBdID\fP"
.br
.ti -1c
.RI "int \fBLinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 601 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk::AID"

.PP
Definition at line 604 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk::BdID"

.PP
Definition at line 606 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk::ID"

.PP
Definition at line 603 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk::LinkID"

.PP
Definition at line 607 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanCrossWalkFileReader::AisanCrossWalk::Type"

.PP
Definition at line 605 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
