.TH "UtilityHNS::AisanPointsFileReader::AisanPoints" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanPointsFileReader::AisanPoints \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBPID\fP"
.br
.ti -1c
.RI "double \fBB\fP"
.br
.ti -1c
.RI "double \fBL\fP"
.br
.ti -1c
.RI "double \fBH\fP"
.br
.ti -1c
.RI "double \fBBx\fP"
.br
.ti -1c
.RI "double \fBLy\fP"
.br
.ti -1c
.RI "int \fBRef\fP"
.br
.ti -1c
.RI "int \fBMCODE1\fP"
.br
.ti -1c
.RI "int \fBMCODE2\fP"
.br
.ti -1c
.RI "int \fBMCODE3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double UtilityHNS::AisanPointsFileReader::AisanPoints::B"

.PP
Definition at line 175 of file DataRW\&.h\&.
.SS "double UtilityHNS::AisanPointsFileReader::AisanPoints::Bx"

.PP
Definition at line 178 of file DataRW\&.h\&.
.SS "double UtilityHNS::AisanPointsFileReader::AisanPoints::H"

.PP
Definition at line 177 of file DataRW\&.h\&.
.SS "double UtilityHNS::AisanPointsFileReader::AisanPoints::L"

.PP
Definition at line 176 of file DataRW\&.h\&.
.SS "double UtilityHNS::AisanPointsFileReader::AisanPoints::Ly"

.PP
Definition at line 179 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanPointsFileReader::AisanPoints::MCODE1"

.PP
Definition at line 181 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanPointsFileReader::AisanPoints::MCODE2"

.PP
Definition at line 182 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanPointsFileReader::AisanPoints::MCODE3"

.PP
Definition at line 183 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanPointsFileReader::AisanPoints::PID"

.PP
Definition at line 174 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanPointsFileReader::AisanPoints::Ref"

.PP
Definition at line 180 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
