.TH "UtilityHNS::AisanStopLineFileReader::AisanStopLine" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UtilityHNS::AisanStopLineFileReader::AisanStopLine \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataRW\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "int \fBLID\fP"
.br
.ti -1c
.RI "int \fBTLID\fP"
.br
.ti -1c
.RI "int \fBSignID\fP"
.br
.ti -1c
.RI "int \fBLinkID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 417 of file DataRW\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int UtilityHNS::AisanStopLineFileReader::AisanStopLine::ID"

.PP
Definition at line 419 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanStopLineFileReader::AisanStopLine::LID"

.PP
Definition at line 420 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanStopLineFileReader::AisanStopLine::LinkID"

.PP
Definition at line 423 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanStopLineFileReader::AisanStopLine::SignID"

.PP
Definition at line 422 of file DataRW\&.h\&.
.SS "int UtilityHNS::AisanStopLineFileReader::AisanStopLine::TLID"

.PP
Definition at line 421 of file DataRW\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
