.TH "VectaCamCommand" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectaCamCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VectaCam\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBlow_nibble_address\fP"
.br
.ti -1c
.RI "unsigned char \fBhigh_nibble_address\fP"
.br
.ti -1c
.RI "unsigned char \fBcommand_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file VectaCam\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char VectaCamCommand::command_data"

.PP
Definition at line 37 of file VectaCam\&.h\&.
.SS "unsigned char VectaCamCommand::high_nibble_address"

.PP
Definition at line 36 of file VectaCam\&.h\&.
.SS "unsigned char VectaCamCommand::low_nibble_address"

.PP
Definition at line 35 of file VectaCam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
