.TH "vector_map::Key< T >" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector_map::Key< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vector_map\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKey\fP ()"
.br
.ti -1c
.RI "\fBKey\fP (int id)"
.br
.ti -1c
.RI "void \fBsetId\fP (int id)"
.br
.ti -1c
.RI "int \fBgetId\fP () const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBKey\fP< T > &right) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class vector_map::Key< T >"

.PP
Definition at line 194 of file vector_map\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBvector_map::Key\fP< T >::\fBKey\fP ()\fC [inline]\fP"

.PP
Definition at line 200 of file vector_map\&.h\&.
.SS "template<class T> \fBvector_map::Key\fP< T >::\fBKey\fP (int id)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 204 of file vector_map\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T> int \fBvector_map::Key\fP< T >::getId () const\fC [inline]\fP"

.PP
Definition at line 214 of file vector_map\&.h\&.
.SS "template<class T> bool \fBvector_map::Key\fP< T >::operator< (const \fBKey\fP< T > & right) const\fC [inline]\fP"

.PP
Definition at line 219 of file vector_map\&.h\&.
.SS "template<class T> void \fBvector_map::Key\fP< T >::setId (int id)\fC [inline]\fP"

.PP
Definition at line 209 of file vector_map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
