.TH "/home/deng/Project/autobot-feature-decision/ros/src/data/packages/vector_map_server/nodes/vector_map_server/vector_map_server.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/data/packages/vector_map_server/nodes/vector_map_server/vector_map_server.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include 'autoware_msgs/Lane\&.h'\fP
.br
\fC#include <visualization_msgs/MarkerArray\&.h>\fP
.br
\fC#include 'vector_map/vector_map\&.h'\fP
.br
\fC#include 'vector_map_server/GetDTLane\&.h'\fP
.br
\fC#include 'vector_map_server/GetNode\&.h'\fP
.br
\fC#include 'vector_map_server/GetLane\&.h'\fP
.br
\fC#include 'vector_map_server/GetWayArea\&.h'\fP
.br
\fC#include 'vector_map_server/GetRoadEdge\&.h'\fP
.br
\fC#include 'vector_map_server/GetGutter\&.h'\fP
.br
\fC#include 'vector_map_server/GetCurb\&.h'\fP
.br
\fC#include 'vector_map_server/GetWhiteLine\&.h'\fP
.br
\fC#include 'vector_map_server/GetStopLine\&.h'\fP
.br
\fC#include 'vector_map_server/GetZebraZone\&.h'\fP
.br
\fC#include 'vector_map_server/GetCrossWalk\&.h'\fP
.br
\fC#include 'vector_map_server/GetRoadMark\&.h'\fP
.br
\fC#include 'vector_map_server/GetRoadPole\&.h'\fP
.br
\fC#include 'vector_map_server/GetRoadSign\&.h'\fP
.br
\fC#include 'vector_map_server/GetSignal\&.h'\fP
.br
\fC#include 'vector_map_server/GetStreetLight\&.h'\fP
.br
\fC#include 'vector_map_server/GetUtilityPole\&.h'\fP
.br
\fC#include 'vector_map_server/GetGuardRail\&.h'\fP
.br
\fC#include 'vector_map_server/GetSideWalk\&.h'\fP
.br
\fC#include 'vector_map_server/GetDriveOnPortion\&.h'\fP
.br
\fC#include 'vector_map_server/GetCrossRoad\&.h'\fP
.br
\fC#include 'vector_map_server/GetSideStrip\&.h'\fP
.br
\fC#include 'vector_map_server/GetCurveMirror\&.h'\fP
.br
\fC#include 'vector_map_server/GetWall\&.h'\fP
.br
\fC#include 'vector_map_server/GetFence\&.h'\fP
.br
\fC#include 'vector_map_server/GetRailCrossing\&.h'\fP
.br
\fC#include 'vector_map_server/PositionState\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBPolygon\fP = std::vector< \fBgeometry_msgs::Point\fP >"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBPolygon\fP =  std::vector<\fBgeometry_msgs::Point\fP>"

.PP
Definition at line 93 of file vector_map_server\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 1038 of file vector_map_server\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
