.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/camera/packages/vectacam/nodes/vectacam/vectacam_node.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/camera/packages/vectacam/nodes/vectacam/vectacam_node.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include 'ros/package\&.h'\fP
.br
\fC#include <image_transport/image_transport\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br
\fC#include <sensor_msgs/image_encodings\&.h>\fP
.br
\fC#include <sensor_msgs/Image\&.h>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'VectaCam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBROSVectaCam\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 118 of file vectacam_node\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
