.TH "/home/deng/Project/autobot-feature-decision/ros/src/simulation/gazebo_simulator/vehicle/vehicle_gazebo_simulation_interface/src/vehicle_gazebo_info_publisher.cpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/simulation/gazebo_simulator/vehicle/vehicle_gazebo_simulation_interface/src/vehicle_gazebo_info_publisher.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <std_msgs/Float64\&.h>\fP
.br
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include <geometry_msgs/TwistStamped\&.h>\fP
.br
\fC#include <gazebo_msgs/GetLinkState\&.h>\fP
.br
\fC#include <sensor_msgs/JointState\&.h>\fP
.br
\fC#include <autoware_msgs/VehicleStatus\&.h>\fP
.br
\fC#include <tf2_ros/transform_broadcaster\&.h>\fP
.br
\fC#include <geometry_msgs/TransformStamped\&.h>\fP
.br
\fC#include <tf2/transform_datatypes\&.h>\fP
.br
\fC#include <tf2/convert\&.h>\fP
.br
\fC#include <tf2/LinearMath/Transform\&.h>\fP
.br
\fC#include <tf2_ros/transform_listener\&.h>\fP
.br
\fC#include <tf2_ros/buffer\&.h>\fP
.br
\fC#include <tf2_geometry_msgs/tf2_geometry_msgs\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVehicleGazeboInfoPublisher\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 158 of file vehicle_gazebo_info_publisher\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
