.TH "velodyne_packet_structs::GyroTempAccelBlock" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
velodyne_packet_structs::GyroTempAccelBlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <garmin_gps_18x_lvc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBgyro\fP"
.br
.ti -1c
.RI "float \fBtemp\fP"
.br
.ti -1c
.RI "float \fBaccel_x\fP"
.br
.ti -1c
.RI "float \fBaccel_y\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file garmin_gps_18x_lvc\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float velodyne_packet_structs::GyroTempAccelBlock::accel_x"

.PP
Definition at line 51 of file garmin_gps_18x_lvc\&.h\&.
.SS "float velodyne_packet_structs::GyroTempAccelBlock::accel_y"

.PP
Definition at line 52 of file garmin_gps_18x_lvc\&.h\&.
.SS "float velodyne_packet_structs::GyroTempAccelBlock::gyro"

.PP
Definition at line 49 of file garmin_gps_18x_lvc\&.h\&.
.SS "float velodyne_packet_structs::GyroTempAccelBlock::temp"

.PP
Definition at line 50 of file garmin_gps_18x_lvc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
