.TH "velodyne_packet_structs::VelodynePositioningPacket" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
velodyne_packet_structs::VelodynePositioningPacket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <garmin_gps_18x_lvc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGyroTempAccelBlock\fP \fBgyro_temp_accel\fP [3]"
.br
.ti -1c
.RI "\fBGyroTempAccelBlock\fP \fBgyro_temp_accel_xyz\fP [3]"
.br
.ti -1c
.RI "double \fBgps_timestamp\fP"
.br
.ti -1c
.RI "char \fBnmea_sentence\fP [72]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file garmin_gps_18x_lvc\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double velodyne_packet_structs::VelodynePositioningPacket::gps_timestamp"

.PP
Definition at line 60 of file garmin_gps_18x_lvc\&.h\&.
.SS "\fBGyroTempAccelBlock\fP velodyne_packet_structs::VelodynePositioningPacket::gyro_temp_accel[3]"

.PP
Definition at line 58 of file garmin_gps_18x_lvc\&.h\&.
.SS "\fBGyroTempAccelBlock\fP velodyne_packet_structs::VelodynePositioningPacket::gyro_temp_accel_xyz[3]"

.PP
Definition at line 59 of file garmin_gps_18x_lvc\&.h\&.
.SS "char velodyne_packet_structs::VelodynePositioningPacket::nmea_sentence[72]"

.PP
Definition at line 61 of file garmin_gps_18x_lvc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
