.TH "/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/hokuyo/nodes/hokuyo_3d/vsspdefs.hpp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/deng/Project/autobot-feature-decision/ros/src/sensing/drivers/lidar/packages/hokuyo/nodes/hokuyo_3d/vsspdefs.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvssp::header\fP"
.br
.ti -1c
.RI "struct \fBvssp::range_header\fP"
.br
.ti -1c
.RI "struct \fBvssp::range_index\fP"
.br
.ti -1c
.RI "struct \fBvssp::data_range_size\fP"
.br
.ti -1c
.RI "struct \fBvssp::data_range_intensity\fP"
.br
.ti -1c
.RI "struct \fBvssp::data_range_only\fP"
.br
.ti -1c
.RI "struct \fBvssp::aux_header\fP"
.br
.ti -1c
.RI "struct \fBvssp::aux_data\fP"
.br
.ti -1c
.RI "class \fBvssp::aux_factor_array\fP"
.br
.ti -1c
.RI "struct \fBvssp::table_sincos\fP"
.br
.ti -1c
.RI "class \fBvssp::xyzi\fP"
.br
.ti -1c
.RI "class \fBvssp::aux\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBvssp\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBvssp::aux_id\fP { \fBvssp::AX_MASK_ANGVEL_X\fP = 31, \fBvssp::AX_MASK_ANGVEL_Y\fP = 30, \fBvssp::AX_MASK_ANGVEL_Z\fP = 29, \fBvssp::AX_MASK_LINACC_X\fP = 28, \fBvssp::AX_MASK_LINACC_Y\fP = 27, \fBvssp::AX_MASK_LINACC_Z\fP = 26, \fBvssp::AX_MASK_MAG_X\fP = 25, \fBvssp::AX_MASK_MAG_Y\fP = 24, \fBvssp::AX_MASK_MAG_Z\fP = 23, \fBvssp::AX_MASK_TEMP\fP = 22, \fBvssp::AX_MASK_FIRST\fP = 22, \fBvssp::AX_MASK_LAST\fP = 31 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
