.TH "vssp::range_header" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vssp::range_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vsspdefs\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBheader_length\fP"
.br
.ti -1c
.RI "uint32_t \fBline_head_timestamp_ms\fP"
.br
.ti -1c
.RI "uint32_t \fBline_tail_timestamp_ms\fP"
.br
.ti -1c
.RI "int16_t \fBline_head_h_angle_ratio\fP"
.br
.ti -1c
.RI "int16_t \fBline_tail_h_angle_ratio\fP"
.br
.ti -1c
.RI "uint8_t \fBframe\fP"
.br
.ti -1c
.RI "uint8_t \fBfield\fP"
.br
.ti -1c
.RI "uint16_t \fBline\fP"
.br
.ti -1c
.RI "uint16_t \fBspot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file vsspdefs\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t vssp::range_header::field"

.PP
Definition at line 110 of file vsspdefs\&.hpp\&.
.SS "uint8_t vssp::range_header::frame"

.PP
Definition at line 109 of file vsspdefs\&.hpp\&.
.SS "uint16_t vssp::range_header::header_length"

.PP
Definition at line 104 of file vsspdefs\&.hpp\&.
.SS "uint16_t vssp::range_header::line"

.PP
Definition at line 111 of file vsspdefs\&.hpp\&.
.SS "int16_t vssp::range_header::line_head_h_angle_ratio"

.PP
Definition at line 107 of file vsspdefs\&.hpp\&.
.SS "uint32_t vssp::range_header::line_head_timestamp_ms"

.PP
Definition at line 105 of file vsspdefs\&.hpp\&.
.SS "int16_t vssp::range_header::line_tail_h_angle_ratio"

.PP
Definition at line 108 of file vsspdefs\&.hpp\&.
.SS "uint32_t vssp::range_header::line_tail_timestamp_ms"

.PP
Definition at line 106 of file vsspdefs\&.hpp\&.
.SS "uint16_t vssp::range_header::spot"

.PP
Definition at line 112 of file vsspdefs\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
