.TH "vssp::xyzi" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vssp::xyzi \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vsspdefs\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBxyzi\fP ()"
.br
.ti -1c
.RI "\fBxyzi\fP (double &v_sin, double &v_cos, double &h_sin, double &h_cos)"
.br
.ti -1c
.RI "\fBxyzi\fP \fBoperator*\fP (const \fBdata_range_intensity\fP &\fBdata\fP)"
.br
.ti -1c
.RI "\fBxyzi\fP \fBoperator*\fP (const \fBdata_range_only\fP &\fBdata\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file vsspdefs\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vssp::xyzi::xyzi ()\fC [inline]\fP"

.PP
Definition at line 168 of file vsspdefs\&.hpp\&.
.SS "vssp::xyzi::xyzi (double & v_sin, double & v_cos, double & h_sin, double & h_cos)\fC [inline]\fP"

.PP
Definition at line 171 of file vsspdefs\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBxyzi\fP vssp::xyzi::operator* (const \fBdata_range_intensity\fP & data)\fC [inline]\fP"

.PP
Definition at line 178 of file vsspdefs\&.hpp\&.
.SS "\fBxyzi\fP vssp::xyzi::operator* (const \fBdata_range_only\fP & data)\fC [inline]\fP"

.PP
Definition at line 188 of file vsspdefs\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "float vssp::xyzi::i"

.PP
Definition at line 166 of file vsspdefs\&.hpp\&.
.SS "float vssp::xyzi::x"

.PP
Definition at line 163 of file vsspdefs\&.hpp\&.
.SS "float vssp::xyzi::y"

.PP
Definition at line 164 of file vsspdefs\&.hpp\&.
.SS "float vssp::xyzi::z"

.PP
Definition at line 165 of file vsspdefs\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
