.TH "vssp::aux" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vssp::aux \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vsspdefs\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaux\fP ()"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (\fBaux_id\fP id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   double \fBx\fP"
.br
.ti -1c
.RI "   double \fBy\fP"
.br
.ti -1c
.RI "   double \fBz\fP"
.br
.ti -1c
.RI "} \fBang_vel\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   double \fBx\fP"
.br
.ti -1c
.RI "   double \fBy\fP"
.br
.ti -1c
.RI "   double \fBz\fP"
.br
.ti -1c
.RI "} \fBlin_acc\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   double \fBx\fP"
.br
.ti -1c
.RI "   double \fBy\fP"
.br
.ti -1c
.RI "   double \fBz\fP"
.br
.ti -1c
.RI "} \fBmag\fP"
.br
.ti -1c
.RI "double \fBtemp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 199 of file vsspdefs\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vssp::aux::aux ()\fC [inline]\fP"

.PP
Definition at line 222 of file vsspdefs\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double& vssp::aux::operator[] (\fBaux_id\fP id)\fC [inline]\fP"

.PP
Definition at line 229 of file vsspdefs\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. }   vssp::aux::ang_vel"

.SS "struct { \&.\&.\&. }   vssp::aux::lin_acc"

.SS "struct { \&.\&.\&. }   vssp::aux::mag"

.SS "double vssp::aux::temp"

.PP
Definition at line 220 of file vsspdefs\&.hpp\&.
.SS "double vssp::aux::x"

.PP
Definition at line 204 of file vsspdefs\&.hpp\&.
.SS "double vssp::aux::y"

.PP
Definition at line 205 of file vsspdefs\&.hpp\&.
.SS "double vssp::aux::z"

.PP
Definition at line 206 of file vsspdefs\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
