.TH "vssp::aux_factor_array" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vssp::aux_factor_array \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vsspdefs\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator[]\fP (\fBaux_id\fP id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBk\fP [\fBAX_MASK_LAST\fP+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file vsspdefs\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double vssp::aux_factor_array::operator[] (\fBaux_id\fP id)\fC [inline]\fP"

.PP
Definition at line 149 of file vsspdefs\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double vssp::aux_factor_array::k[\fBAX_MASK_LAST\fP+1]"

.PP
Definition at line 152 of file vsspdefs\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
