.TH "vssp" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vssp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBaux\fP"
.br
.ti -1c
.RI "struct \fBaux_data\fP"
.br
.ti -1c
.RI "class \fBaux_factor_array\fP"
.br
.ti -1c
.RI "struct \fBaux_header\fP"
.br
.ti -1c
.RI "struct \fBdata_range_intensity\fP"
.br
.ti -1c
.RI "struct \fBdata_range_only\fP"
.br
.ti -1c
.RI "struct \fBdata_range_size\fP"
.br
.ti -1c
.RI "struct \fBheader\fP"
.br
.ti -1c
.RI "struct \fBrange_header\fP"
.br
.ti -1c
.RI "struct \fBrange_index\fP"
.br
.ti -1c
.RI "struct \fBtable_sincos\fP"
.br
.ti -1c
.RI "class \fBvsspDriver\fP"
.br
.ti -1c
.RI "class \fBxyzi\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBaux_id\fP { \fBAX_MASK_ANGVEL_X\fP = 31, \fBAX_MASK_ANGVEL_Y\fP = 30, \fBAX_MASK_ANGVEL_Z\fP = 29, \fBAX_MASK_LINACC_X\fP = 28, \fBAX_MASK_LINACC_Y\fP = 27, \fBAX_MASK_LINACC_Z\fP = 26, \fBAX_MASK_MAG_X\fP = 25, \fBAX_MASK_MAG_Y\fP = 24, \fBAX_MASK_MAG_Z\fP = 23, \fBAX_MASK_TEMP\fP = 22, \fBAX_MASK_FIRST\fP = 22, \fBAX_MASK_LAST\fP = 31 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBvssp::aux_id\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAX_MASK_ANGVEL_X \fP\fP
.TP
\fB\fIAX_MASK_ANGVEL_Y \fP\fP
.TP
\fB\fIAX_MASK_ANGVEL_Z \fP\fP
.TP
\fB\fIAX_MASK_LINACC_X \fP\fP
.TP
\fB\fIAX_MASK_LINACC_Y \fP\fP
.TP
\fB\fIAX_MASK_LINACC_Z \fP\fP
.TP
\fB\fIAX_MASK_MAG_X \fP\fP
.TP
\fB\fIAX_MASK_MAG_Y \fP\fP
.TP
\fB\fIAX_MASK_MAG_Z \fP\fP
.TP
\fB\fIAX_MASK_TEMP \fP\fP
.TP
\fB\fIAX_MASK_FIRST \fP\fP
.TP
\fB\fIAX_MASK_LAST \fP\fP
.PP
Definition at line 69 of file vsspdefs\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
