.TH "WaveFrontNode" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WaveFrontNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <astar_util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWaveFrontNode\fP ()"
.br
.ti -1c
.RI "\fBWaveFrontNode\fP (int x, int y, double cost)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex_x\fP"
.br
.ti -1c
.RI "int \fBindex_y\fP"
.br
.ti -1c
.RI "double \fBhc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file astar_util\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WaveFrontNode::WaveFrontNode ()"

.PP
Definition at line 19 of file astar_util\&.cpp\&.
.SS "WaveFrontNode::WaveFrontNode (int x, int y, double cost)"

.PP
Definition at line 23 of file astar_util\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double WaveFrontNode::hc"

.PP
Definition at line 45 of file astar_util\&.h\&.
.SS "int WaveFrontNode::index_x"

.PP
Definition at line 43 of file astar_util\&.h\&.
.SS "int WaveFrontNode::index_y"

.PP
Definition at line 44 of file astar_util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
