.TH "WayPlannerNS::WayPlannerParams" 3 "Fri May 22 2020" "Autoware_Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WayPlannerNS::WayPlannerParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <way_planner_core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWayPlannerParams\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBKmlMapPath\fP"
.br
.ti -1c
.RI "bool \fBbEnableSmoothing\fP"
.br
.ti -1c
.RI "bool \fBbEnableLaneChange\fP"
.br
.ti -1c
.RI "bool \fBbEnableHMI\fP"
.br
.ti -1c
.RI "bool \fBbEnableRvizInput\fP"
.br
.ti -1c
.RI "bool \fBbEnableReplanning\fP"
.br
.ti -1c
.RI "double \fBpathDensity\fP"
.br
.ti -1c
.RI "\fBMAP_SOURCE_TYPE\fP \fBmapSource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file way_planner_core\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WayPlannerNS::WayPlannerParams::WayPlannerParams ()\fC [inline]\fP"

.PP
Definition at line 111 of file way_planner_core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WayPlannerNS::WayPlannerParams::bEnableHMI"

.PP
Definition at line 104 of file way_planner_core\&.h\&.
.SS "bool WayPlannerNS::WayPlannerParams::bEnableLaneChange"

.PP
Definition at line 103 of file way_planner_core\&.h\&.
.SS "bool WayPlannerNS::WayPlannerParams::bEnableReplanning"

.PP
Definition at line 106 of file way_planner_core\&.h\&.
.SS "bool WayPlannerNS::WayPlannerParams::bEnableRvizInput"

.PP
Definition at line 105 of file way_planner_core\&.h\&.
.SS "bool WayPlannerNS::WayPlannerParams::bEnableSmoothing"

.PP
Definition at line 102 of file way_planner_core\&.h\&.
.SS "std::string WayPlannerNS::WayPlannerParams::KmlMapPath"

.PP
Definition at line 101 of file way_planner_core\&.h\&.
.SS "\fBMAP_SOURCE_TYPE\fP WayPlannerNS::WayPlannerParams::mapSource"

.PP
Definition at line 108 of file way_planner_core\&.h\&.
.SS "double WayPlannerNS::WayPlannerParams::pathDensity"

.PP
Definition at line 107 of file way_planner_core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Autoware_Doxygen from the source code\&.
