var namespacedatatypes =
[
    [ "BasicData", "classdatatypes_1_1_basic_data.html", "classdatatypes_1_1_basic_data" ],
    [ "Box2D", "classdatatypes_1_1_box2_d.html", "classdatatypes_1_1_box2_d" ],
    [ "Circle2D", "classdatatypes_1_1_circle2_d.html", "classdatatypes_1_1_circle2_d" ],
    [ "Ellipse2D", "classdatatypes_1_1_ellipse2_d.html", "classdatatypes_1_1_ellipse2_d" ],
    [ "EvalCase", "classdatatypes_1_1_eval_case.html", "classdatatypes_1_1_eval_case" ],
    [ "EvalCaseResult", "classdatatypes_1_1_eval_case_result.html", "classdatatypes_1_1_eval_case_result" ],
    [ "EvalCaseResults", "classdatatypes_1_1_eval_case_results.html", "classdatatypes_1_1_eval_case_results" ],
    [ "EvalCases", "classdatatypes_1_1_eval_cases.html", "classdatatypes_1_1_eval_cases" ],
    [ "FieldDescription", "classdatatypes_1_1_field_description.html", "classdatatypes_1_1_field_description" ],
    [ "FieldDynamic", "classdatatypes_1_1_field_dynamic.html", "classdatatypes_1_1_field_dynamic" ],
    [ "FieldParameter", "classdatatypes_1_1_field_parameter.html", "classdatatypes_1_1_field_parameter" ],
    [ "FieldRadial", "classdatatypes_1_1_field_radial.html", "classdatatypes_1_1_field_radial" ],
    [ "FieldRectangle", "classdatatypes_1_1_field_rectangle.html", "classdatatypes_1_1_field_rectangle" ],
    [ "Fields", "classdatatypes_1_1_fields.html", "classdatatypes_1_1_fields" ],
    [ "FieldSegmented", "classdatatypes_1_1_field_segmented.html", "classdatatypes_1_1_field_segmented" ],
    [ "FieldSegmentedPoint", "classdatatypes_1_1_field_segmented_point.html", "classdatatypes_1_1_field_segmented_point" ],
    [ "Line2D", "classdatatypes_1_1_line2_d.html", "classdatatypes_1_1_line2_d" ],
    [ "Matrix", "classdatatypes_1_1_matrix.html", "classdatatypes_1_1_matrix" ],
    [ "Measurement", "classdatatypes_1_1_measurement.html", "classdatatypes_1_1_measurement" ],
    [ "MeasurementList", "classdatatypes_1_1_measurement_list.html", "classdatatypes_1_1_measurement_list" ],
    [ "Msg", "classdatatypes_1_1_msg.html", "classdatatypes_1_1_msg" ],
    [ "Object", "classdatatypes_1_1_object.html", "classdatatypes_1_1_object" ],
    [ "ObjectList", "classdatatypes_1_1_object_list.html", "classdatatypes_1_1_object_list" ],
    [ "Point2D", "classdatatypes_1_1_point2_d.html", "classdatatypes_1_1_point2_d" ],
    [ "Point3D", "classdatatypes_1_1_point3_d.html", "classdatatypes_1_1_point3_d" ],
    [ "Polygon2D", "classdatatypes_1_1_polygon2_d.html", "classdatatypes_1_1_polygon2_d" ],
    [ "Polygon3D", "classdatatypes_1_1_polygon3_d.html", "classdatatypes_1_1_polygon3_d" ],
    [ "Position3D", "classdatatypes_1_1_position3_d.html", "classdatatypes_1_1_position3_d" ],
    [ "PositionWGS84", "classdatatypes_1_1_position_w_g_s84.html", "classdatatypes_1_1_position_w_g_s84" ],
    [ "Scan", "classdatatypes_1_1_scan.html", "classdatatypes_1_1_scan" ],
    [ "ScannerInfo", "classdatatypes_1_1_scanner_info.html", "classdatatypes_1_1_scanner_info" ],
    [ "ScanPoint", "classdatatypes_1_1_scan_point.html", "classdatatypes_1_1_scan_point" ],
    [ "SensorStateInfo", "classdatatypes_1_1_sensor_state_info.html", "classdatatypes_1_1_sensor_state_info" ],
    [ "Trigger", "classdatatypes_1_1_trigger.html", "classdatatypes_1_1_trigger" ],
    [ "Vector", "classdatatypes_1_1_vector.html", "classdatatypes_1_1_vector" ]
];